### ISSUE TITLE
Bug: "Private Modpack" = "Hide Modpack"

### ISSUE THREAD

**Issue by Pyrii** [TechnicPack/TechnicSolder#111]
Setting a modpack as private but visible still removes it from the API response from /api/modpack/ meaning that the Technic website can't see it.

**Comment by GenPage** [comment]
This feature has been added to v0.6 and v0.7

v0.6: 44d993bbe756ab6882fb4966a5dfa648f96f9a25
v0.7: 1cc85c6c6a3744a08cd661d8f8b8f2c9293931f4
