### ISSUE TITLE
Platform/Solder issue with AAAA vs A records

### ISSUE THREAD

**Issue by Goldman60** [TechnicPack/TechnicSolder#115]
If a site has a AAAA and a A record the platform will prioritize the AAAA record and attempt a connection on ipv6.  However if the ipv6 attempt fails it will not retry with the A record for ipv4.

This causes issues with sites who serve ipv6 service but do not serve web pages on ipv6.  Browsers handle this behaviour transparently which makes this very hard to diagnose.

The launcher also fallsback gracefully,so it can be hard to tell that anything is wrong.

Cause of #114

**Comment by GenPage** [comment]
The fix for this would be to make sure you have your Solder vHost listen on IPv6

Example on the doc site: http://docs.solder.io/v0.7/docs/example-web-server-configs
