### ISSUE TITLE
Limit on file size? Can't "Add Version"

### ISSUE THREAD

**Issue by mine-my-own-bizz** [TechnicPack/TechnicSolder#160]
Is there any sort of file size limits?

I am trying to add my MAtmos Resources folder and it is rather large folder due to music expansions (150MB).

When I click add version nothing happens, I have waited upwards of 20+ minute hoping it just took longer.

I also tried uploading a ghost version so I could get an md5 at least. Edited the file and then attempted to rehash and had the same outcome.

Any suggestions?

**Comment by GenPage** [comment]
This issue seems to be resolved. Closing
