### ISSUE TITLE
Could not get MD5, URL correct ?

### ISSUE THREAD

**Issue by alexvlrt** [TechnicPack/TechnicSolder#161]
Hello guys, I have a problem, when i want to set my Download URl for my modpack, I got this error in the title. but my URL works, if you want to try it : 
http://www.craft-works.fr/geek/repo/mods/dark-industry-modpack/dark-industry-modpack-1.7.10.zip

**Comment by JagSwag2014** [comment]
I seem to be having this issue now.

Adding a version returns the error specified above. The download URL works, the file exists, the directories are exactly the same in the server as it should be on Solder, but it still returns a 404. I've even tried setting all perms to 0777 recursively, still no dice.

I did get these errors from the PHP debug bar:
http://screencast.com/t/YcBXR4kHc

Tried Googling the error, but can't find a liable source. Any suggestions?

**Comment by GenPage** [comment]
The error `URL malformed` means the path is invalid.

Double check your repo settings

**Comment by JagSwag2014** [comment]
@GenPage 
Repo settings are correct.

It is set to '/home/www/pack.craftblock.me/public/mods/'
http://screencast.com/t/b7CNTMvfIsO
Download link works fine.

**Comment by JagSwag2014** [comment]
I got it working, had to change the repo location to a link instead of a directory. Thanks anyways.

**Comment by GenPage** [comment]
This results in degraded performance when hashing the files. It gets the file data over HTTP instead of accessing the file directly. The issue is with file permissions

**Comment by JagSwag2014** [comment]
@GenPage 
File perms are set to www-data as owner and 0777 for perms, but doesn't work as a directory.

**Comment by JagSwag2014** [comment]
Got it fixed. 
I knew that public wasn't required in the installation when going to the webpage, but it completely slipped my mind that it had to be in the repo_location.

**Comment by TheDoctorsLife** [comment]
@JagSwag2014 never put files at 0777, it's bad practice as ANYONE can now edit that file/folders. When ever you are having issues, use 0775 so that the public doesn't have write access.
