### ISSUE TITLE
Unknown build number 1.0 appears in the "specific version" drop down menu of a modpack

### ISSUE THREAD

**Issue by mcsnetworks** [TechnicPack/TechnicSolder#171]
When clicking on "Modpack Options", if you select "a specific version", there is a 1.0 version at the top of the list.

This 1.0 version is not on our solder server so I don't know where it is getting version 1.0 from.

**Comment by TheGeekdu74** [comment]
So what is the solution ? I have the same problem

**Comment by GenPage** [comment]
This is a bug where the modpack is created first before importing it from solder. Delete the pack and re-import.
