### ISSUE TITLE
Searching in modlist also searches in manage button

### ISSUE THREAD

**Issue by mcmielleman** [TechnicPack/TechnicSolder#185]
Solder version: V0.7.0.3

If i search in the modlist with "manage" everything shows up, because every mod has the manage button at the last column (i think). I am using a mysql database.

So there should be a seach filter, because if i want search forge (the modloader) i dont want a long list with every mod from CurseForge.

**Comment by TheDoctorsLife** [comment]
Just as an FYI, solder it now version V0.7.0.7 Please update.
