### ISSUE TITLE
Ability to specify dependencies from Solder, per modpack

### ISSUE THREAD

**Issue by Grinch** [TechnicPack/TechnicSolder#187]
Would like the ability to add dependencies that normally would go in a verison.json file, from Solder itself.

**Comment by DeviPotato** [comment]
I would like having a minimum RAM requirement for a modpack, and perhaps a link to the java downloads if the user is using 32 bit java and can't reach the requirement. I have to explain increasing the memory allocation to all of the people who play with my pack for them to be able to play with reasonable performance, and I know that at least in a previous version of Forge (I believe it has been fixed) clients disconnecting from servers via an out of memory crash left permanent "ghosts" on the server which spammed network errors and ended up lagging it out completely after enough of them were around.

**Comment by mcmielleman** [comment]
I think this is another type of depency (dont know really what the exact topic is, maybe its this), but it would be nice to be able to specify addons, so when you add for example advanced machines to the modlist you can specify that it needs IC2 to be installed in the modpack (maybe even a specified version) and then if you add advanced machines, it warns you that ic2 is needed.

**Comment by JamiePhonic** [comment]
this would be a nice feature to have because lots of mods have "librarys" you need in order to use them, such as ichunutil for morph, CoFH lib and core for thermal expansion and MFR and many others

**Comment by raymondbh** [comment]
+1 to the kind of dependencies @mcmielleman speaks of.

**Comment by Grinch** [comment]
Any update on this?
