### ISSUE TITLE
Crash when logging out.

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#208]
I get this crash whenever I logout or when I click "Remember Me" when logging in.

Crash: http://pastebin.com/xxRHiK75

**Comment by GenPage** [comment]
Please make sure you migrated the new DB changes since the v0.7 update

**Comment by fcpwiz** [comment]
With php artisan migrate?

**Comment by GenPage** [comment]
yes

**Comment by fcpwiz** [comment]
Whenever I do that command, I get this error:

Status: 404 Not Found
X-Powered-By: PHP/5.4.33
Content-type: text/html

No input file specified.

**Comment by GenPage** [comment]
This does not make sense. `php artisan migrate` is suppose to be run from the console. You gave me a web response.

**Comment by fcpwiz** [comment]
Yes, I ran the command via root SSH. Above is what the command returned for me.

**Comment by GenPage** [comment]
Can you provide a screenshot

**Comment by fcpwiz** [comment]
Here: http://s21.postimg.org/dbxhq2hlz/image.jpg

**Comment by GenPage** [comment]
do you have php5-cli installed

**Comment by fcpwiz** [comment]
I don't know. How would I check/how do I install it?

**Comment by fcpwiz** [comment]
Hello @GenPage

**Comment by fcpwiz** [comment]
Here are the installed PHP Modules: http://s24.postimg.org/aeyz9xs7p/image.jpg

Please respond asap.

**Comment by GenPage** [comment]
sudo apt-get install php5-cli

**Comment by fcpwiz** [comment]
Here's what I get: http://s14.postimg.org/mmbehgxup/image.jpg

**Comment by GenPage** [comment]
What system are you running

**Comment by fcpwiz** [comment]
VPS running CentOS6 with Linux.

**Comment by GenPage** [comment]
sudo yum install php5-cli

**Comment by fcpwiz** [comment]
Ok. I ran that, here is what I got: http://s29.postimg.org/77j9bb82v/image.jpg

**Comment by GenPage** [comment]
remove the '5'

**Comment by fcpwiz** [comment]
Ok. Here is the new screenshot: http://s15.postimg.org/nc6el0kwr/image.jpg

**Comment by GenPage** [comment]
sudo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
sudo rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
and try again

**Comment by fcpwiz** [comment]
Still says no package available :(. Should I of been instating those .rpm files in a certain location?

**Comment by GenPage** [comment]
I have no clue why, I am going to assume that solder doesnt have proper file/folder permissions.

**Comment by fcpwiz** [comment]
How would I go about modifying the solder folder permissions?

**Comment by GenPage** [comment]
http://www.thegeekstuff.com/2010/04/unix-file-and-directory-permissions/

**Comment by fcpwiz** [comment]
What kind of permissions should solder have?

**Comment by fcpwiz** [comment]
Ok. I think I found something out. I was using the incorrect solder folder to do php artisan migrate for. Here is the screenshot of the correct version: http://s29.postimg.org/sra9b4ujr/image.jpg

What do I do to fix this?

Please respond asap.

**Comment by fcpwiz** [comment]
Hey Gen, I fixed the error above. When I do any php artisan command I get this:

{"error":{"type":"ErrorException","message":"Undefined index: timezone","file":"\/home\/mannyrothman\/public_html\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}

**Comment by GenPage** [comment]
did you run `composer install`

Please make sure you followed this guide: https://github.com/TechnicPack/TechnicSolder/wiki/Getting-Started

**Comment by fcpwiz** [comment]
Yes. I did that command many times before. I just tried again, and got the same error.

**Comment by GenPage** [comment]
That error means there is no timezone option in your `config/app.php`

**Comment by fcpwiz** [comment]
I've done everything on the Getting Started wiki page up to the php artisan migrate command. That is where the error is.

**Comment by BloodyMikey** [comment]
try <code>sudo composer install --prefer-source</code>

**Comment by fcpwiz** [comment]
@BloodyMikey thanks but I got the same error as before.

**Comment by fcpwiz** [comment]
@GenPage Ok. Now when I put in anything regarding php artisan, I get this:

http://pastebin.com/Y7mHkg4g
