### ISSUE TITLE
PDO Exception problem ( Access denied ??)

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#210]
Hello, I have a problem when I want to log in the TechnicSolder. I don't have production.sqlite because I have mysql instaleld on my pc. But I have an "Access denied for the user "solder". See this : 
http://pastebin.com/QF7XHhac

Please help me !

**Comment by rfox90** [comment]
This is nothing to do with sqlite.

a PDO Exception is a class of exception a ton of things can generate it.

"Access denied for user 'solder'@'localhost' (using password: YES)'"

Should give you a big clue about why this is not working.

This is an issue tracker and NOT a support forum.

**Comment by TheGeekdu74** [comment]
Ok, sorry but I modify the user "solder" to not have a password, but I have the same problem.
(It's a issue tracker, ok but where is the support forum ? On the website ?)

**Comment by rfox90** [comment]
Give the solder user a password and then give that password to the solder configs where you specified the rest of the database stuff.

Always test the connection using mysql on the terminal.

Don't worry about posting somewhere else for this but keep in mind that the majority of issues here should be actual bugs or features.

**Comment by TheGeekdu74** [comment]
Ok I gonna try that, and thanks for your support :)

**Comment by TheGeekdu74** [comment]
I do everything you say, but the problem persist. I got the DB "solder", the user "solder" and the password "sodler1" for user "solder". And I have got the same problem

**Comment by rfox90** [comment]
so running
`mysql -usolder -psolder1`

from the command line works.

**Comment by TheGeekdu74** [comment]
Where I do this command ? On the Windows PowerShell, the command doesn't exists

**Comment by GenPage** [comment]
Windows is not supported.
