### ISSUE TITLE
Launcher issue with solder

### ISSUE THREAD

**Issue by Neodark7** [TechnicPack/TechnicSolder#211]
I have a similar issue to https://github.com/TechnicPack/TechnicSolder/issues/171
solder seems to be enabled on the website but not on the launcher : http://imgur.com/a/WnsNe
here's my build infos : http://imgur.com/a/RWzw2

**Comment by GenPage** [comment]
The issue is with the Solder API response. Please post a link of it. The link will be formatted as so

`<solder url>`/api/modpack/<modpack slug>

**Comment by Neodark7** [comment]
http://bit.ly/1ESVPgr This ?

**Comment by GenPage** [comment]
http://ks28064.kimsufi.com/solder/public/index.php/api/modpack/neodarkpack-2

That. Looks like you dont have the same issue. Can you post the API link from the platform

**Comment by Neodark7** [comment]
http://ks28064.kimsufi.com/solder/public/index.php/api/

c1617bd23e1ef560b658e62b7b271e602a1dc1c047030f9b26fa4a2b6ca1f3f0

**Comment by GenPage** [comment]
No, the api link you put in the launcher.

**Comment by Neodark7** [comment]
hmm i've juste click install on the website i don't have another link :/

**Comment by GenPage** [comment]
just paste the link to your modpack on the site

**Comment by Neodark7** [comment]
ooh http://technicpack.net/modpack/neodarkpack-2.556205 :)

**Comment by GenPage** [comment]
Ah, your solder redirects to a flash video

**Comment by Neodark7** [comment]
owe sorry for that x) and now ?

**Comment by GenPage** [comment]
Still doesnt work

**Comment by Neodark7** [comment]
:/ i don't know what is not working

**Comment by GenPage** [comment]
http://ks28064.kimsufi.com/solder/public/index.php/api/

**Comment by Neodark7** [comment]
http://ks28064.kimsufi.com/solder/public/index.php/api and now ?

**Comment by Neodark7** [comment]
i don't know why it's redirect to http://ks28064.kimsufi.com//index.php :(

**Comment by Neodark7** [comment]
YAY, i've clone the solder/public/index.php at the root and modify

require __DIR__.'/solder/bootstrap/autoload.php';
$app = require_once __DIR__.'/solder/bootstrap/start.php';

and.. it works. Really weird

**Comment by Neodark7** [comment]
So i don't know if it's an issue of the api or just me ?

**Comment by GenPage** [comment]
Its you, and your web server settings.
