### ISSUE TITLE
i think i got php problem?

### ISSUE THREAD

**Issue by BloodyMikey** [TechnicPack/TechnicSolder#212]
i think i do i dont know here u go 
![untitled](https://cloud.githubusercontent.com/assets/7265198/5594111/acb806d6-923b-11e4-832a-c37b25f1762f.png)

**Comment by GenPage** [comment]
try `php artisan dump-autoload` to re-compile the autoloaded classes.

**Comment by BloodyMikey** [comment]
hmm sorry same error

**Comment by sct** [comment]
You haven't ran `composer install` yet

**Comment by BloodyMikey** [comment]
in the guide there was noting there i do it brb with whats gonna happen


2015-01-02 19:55 GMT+01:00 sct <notifications@github.com>:

> You haven't ran composer install yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TechnicPack/TechnicSolder/issues/212#issuecomment-68551522>
> .
>



-- 
Mvh Michael Tägtlund

**Comment by BloodyMikey** [comment]
![untitleds](https://cloud.githubusercontent.com/assets/7265198/5598851/55af770c-92bd-11e4-97e6-01a16f5910a0.png)
here

**Comment by Razorskills** [comment]
That is a guide for 0.6 solder on a Raspberry Pi

**Comment by BloodyMikey** [comment]
@Razorskills sudo composer install --prefer-source told me to do this and now it is installing il be back if i gett any errors

**Comment by BloodyMikey** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7265198/5599563/837378a8-92c9-11e4-942e-61e2263f1775.png)

**Comment by GenPage** [comment]
@BloodyMikey Are you creating from scratch or updating from 0.6

**Comment by BloodyMikey** [comment]
scratch but last time i did that command i had a permission error and i think i fixed that and then i did the command again and then i got that error and command was <code>php artisan migrate</code>

**Comment by GenPage** [comment]
https://github.com/TechnicPack/TechnicSolder/wiki/Getting-Started#database-setup

**Comment by BloodyMikey** [comment]
So what exactly should i do?

**Comment by BloodyMikey** [comment]
is therea a way do delete everything and restart?

**Comment by BloodyMikey** [comment]
I get problem with permission so now i did install WinScp and make The whole TechnicSolder 0777 And then it did work so what does it need beacuse it aint the best to have it at 0777

**Comment by GenPage** [comment]
775
