### ISSUE TITLE
1 Issue wth composer and 1 issue wtih php artisan migrate:install

### ISSUE THREAD

**Issue by Razorskills** [TechnicPack/TechnicSolder#213]
So basically, when I put in:
sudo composer install

and it downloads some files and then gets to some that need passwords.. and even if you use your git hub acc, you still need to be given access to the files..? after 5 Invalid credentials it just downloads from source..  there is about 20 of them, and it takes way longer. Plus im not sure if I even get the correct files..
```
Could not fetch https://api.github.com/repos/swiftmailer/swiftmailer/zipball/e29c7b692bae6610b137670d6749151fd6e41608, enter your GitHub credentials to go over the API rate limit
The credentials will be swapped for an OAuth token stored in /root/.composer/auth.json, your password will not be stored
To revoke access to this token you can visit https://github.com/settings/applications
Username:
Password:
Invalid credentials.
Username:
Password:
Invalid credentials.
Username:
Password:
Invalid credentials.
Username:
Password:
Invalid credentials.
Username:
Password:
Invalid credentials.
    Failed to download swiftmailer/swiftmailer from dist: Invalid GitHub credentials 5 times in a row, aborting.
    Now trying to download from source
  - Installing swiftmailer/swiftmailer (dev-master e29c7b6)
    Cloning e29c7b692bae6610b137670d6749151fd6e41608
```

After going through all that, using 
```
php artisan migrate:install
```
gives:
```

  [PDOException]
  could not find driver



migrate:install [--database[="..."]]
```

Im not sure what part I am missing, but I know im missing something..

**Comment by GenPage** [comment]
Composer did not complete successfully, that is what is causing your last two issues.

The first composer issue is because GitHub is rate-limiting you. 

Use `--prefer-source`. It's not recommended, but will fix the issue for the meantime.

**Comment by Razorskills** [comment]
Alright I will do a fresh install and see if that fixes it all.

As for the
```
 [PDOException]
  could not find driver
```

And I have installed all of these
```
php5 php5-cli php5-curl php5-gd php5-mcrypt php5-mysql curl
```
is the driver not part of php5-mysql?

**Comment by GenPage** [comment]
Check your database.php config, the default is `sqlite`.

**Comment by Razorskills** [comment]
Thank you, you are awesome. that did the trick :)
