### ISSUE TITLE
Blank Modpack Page

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#218]
/modpack/view/1 Gives me this: http://s9.postimg.org/lar72tq8f/Screen_Shot_2015_01_04_at_9_15_21_PM.png

/modpack/view/2 Works perfectly fine.

What's going on?

**Comment by GenPage** [comment]
Did you create the first modpack

**Comment by fcpwiz** [comment]
Yes, about a year ago.

**Comment by fcpwiz** [comment]
It's weird because I can access all of the builds of that pack via the dashboard. Its just that link to view the builds altogether doesn't work.

**Comment by fcpwiz** [comment]
Found answer! I had to allocate more ram in php.ini!
