### ISSUE TITLE
GitHub Api Limit reached

### ISSUE THREAD

**Issue by fueller** [TechnicPack/TechnicSolder#220]
I got an Error 500 while logging into solder:

exception 'Github\Exception\ApiLimitExceedException' with message 'You have reached GitHub hour limit! Actual limit is: 5000' in C:\Users\lawall\Desktop\laravelTests\TechnicSolder\vendor\knplabs\github-api\lib\Github\HttpClient\Listener\ErrorListener.php:46

**Comment by GenPage** [comment]
This is probably due to you installing and rate limiting yourself. Try again tomorrow. I will in the meantime have to catch the error so the application will at least be useable in the future

**Comment by GenPage** [comment]
This should be resolved now as of v0.7.1.0
