### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by FlareHAX0R** [TechnicPack/TechnicSolder#221]
Ok.... so I try to login to solder. I have set this up on a non-SSH webserver - x10hosting, by installing it on my local comp, zipping it up, then unzipping it on the webserver.

After I update solder 0.7 to the latest version, I get THIS big Error(500) in my face: http://pastebin.com/LZTQKkzk

So after, I just think it's an updating problem, and I reinstall solder and configure it... Same error again. Can't go to login page in solder.

Help please?

**Comment by FlareHAX0R** [comment]
Help please?

**Comment by GenPage** [comment]
`'ErrorException' with message 'shell_exec() has been disabled for security reasons'`

Your hosting provider has blocked certain functions from running. I am going to have to code a case function to disable the update checker in this situation.

**Comment by FlareHAX0R** [comment]
Thanks. That would help. I do have one host who has SSH, but the host has leaked info from a social network I set up once. Plus, it only supports PHP 5.2-5.4

**Comment by FlareHAX0R** [comment]
I temporairly edited UpdateUtils.zip to make getCurrentVersion() always return "cats". THIS IS A GOOD FIX FOR THOSE WHO USE SHARED HOSTING.
