### ISSUE TITLE
exception 'ErrorException' with message 'Undefined offset: 1'

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TechnicPack/TechnicSolder#223]
Im getting this error after trying to login after a fresh install of Solder, here are my Specs and the Error log.

PHP Info: http://pastebin.com/R0NaQkKQ heres a direct link: http://windmillgaming.tk/TechnicSolder/ (I made the PHP info in the root directory of TechnicSolder so people dont go rooting around the directory)

Error Log: http://pastebin.com/52dj7GnB

**Comment by xH3LLRAIZ3Rx** [comment]
oh and just letting you know I did everything on the Getting Started Wiki, I made sure to follow the Directions

**Comment by fcpwiz** [comment]
Someone recently had this issue. It got resolved here: https://github.com/TechnicPack/TechnicSolder/issues/219

**Comment by xH3LLRAIZ3Rx** [comment]
that didnt help me, I cloned from git and everything, how do I fix the issue?

**Comment by xH3LLRAIZ3Rx** [comment]
I just tried to reinstall it with the Dev branch and using sqLite, and having the same issue

**Comment by GenPage** [comment]
This means two things

1) You did not clone the git repo

2) You are rate-limited from GitHub. Try again tomorrow

**Comment by xH3LLRAIZ3Rx** [comment]
how would I know if I was rate-limited from github?

**Comment by xH3LLRAIZ3Rx** [comment]
ok so I tried to clone it again but with a VPN, same issue

**Comment by xH3LLRAIZ3Rx** [comment]
so I looked at my rate limit for github and this is what it shows

http://i.imgur.com/RWIX8IV.png

it looks like im not Rate-Limited from GitHub, and I did clone the git repo, so im not sure how to fix this issue

**Comment by GenPage** [comment]
Please test this in the root of your solder folder and paste your results

`git describe --tags`

`git log v0.7.0.6..v0.7.0.7`

**Comment by xH3LLRAIZ3Rx** [comment]
http://i.imgur.com/4deyPT7.png

**Comment by GenPage** [comment]
Interesting. And you still get the error?

**Comment by xH3LLRAIZ3Rx** [comment]
yes  http://i.imgur.com/UsHJyCH.png

**Comment by xH3LLRAIZ3Rx** [comment]
ok so it defiantly is a bug, I tried to set it up again today, and it still gave the error

**Comment by xH3LLRAIZ3Rx** [comment]
OK so I just noticed TechnicSolder atm only works in Linux, so I installed Linux

**Comment by Razorskills** [comment]
lmao
