### ISSUE TITLE
Windows Fail

### ISSUE THREAD

**Issue by Moocow9m** [TechnicPack/TechnicSolder#224]
I was waiting for the bugs to be ironed out and when I came back Windows was no longer supported! Why is this? Will it ever be supported again?

**Comment by Amaxter** [comment]
I don't think so, plus not many people use Windows any more. OS X is where it's at buddy.

**Comment by GenPage** [comment]
I have pushed off Windows support til a later release, there is too much going on with the application at this point to iron out bugs for both systems. Almost all hosting companies provide a Linux distro. 

I will also like to post that Solder is a **server-side** application and is not intended to be run on a desktop with a residential connection

**Comment by Moocow9m** [comment]
I host only because it is and always will be free.(price for internet and power excluded). I could dualboot but have yet found a 100% truly safe download(aka free)

**Comment by FlareHAX0R** [comment]
Moocow9m, http://ubuntu.com
Also, http://x10hosting.com  Free hosting. No SSH, though.

**Comment by Moocow9m** [comment]
x10 hostin wont allow install of composer or anything like that (unless i
am doing something wrong).

On Tue, Jan 6, 2015 at 5:39 AM, FlareHAX0R <notifications@github.com> wrote:

> Moocow9m, http://ubuntu.com
> Also, http://x10hosting.com Free hosting. No SSH, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TechnicPack/TechnicSolder/issues/224#issuecomment-68855581>
> .
>



-- 
Matthew Taliancich 2

**Comment by FlareHAX0R** [comment]
@Moocow9m You will need to install it locally, zip it up, and extract it on x10hosting. Also ask on the IRC for a SQL template.

**Comment by Moocow9m** [comment]
when doing composer i came up with this error message! I have checked the php website but it did not help. Please help.

Xampphtdocssoldercomposer install --no-interaction
ading composer repositories with package information
stalling dependencies (including require-dev)
ur requirements could not be resolved to an installable set of packages.

Problem 1
  - interventionimage 2.0.9 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.8 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.7 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.6 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.5 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.4 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.3 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.2 requires ext-fileinfo  - the requested PHP
ion fileinfo is missing from your system.
  - interventionimage 2.0.17 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.
  - interventionimage 2.0.16 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.
  - interventionimage 2.0.15 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.
  - interventionimage 2.0.14 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.
  - interventionimage 2.0.13 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.
  - interventionimage 2.0.12 requires ext-fileinfo  - the requested PH
sion fileinfo is missing from your system.

**Comment by Moocow9m** [comment]
Also if i just skip that step and manualy do mwhat the wiki says it does i get this.

Warning: require(C:\Xampp\htdocs\solder\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Xampp\htdocs\solder\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\Xampp\htdocs\solder\bootstrap/../vendor/autoload.php' (include_path='.;C:\Xampp\php\PEAR') in C:\Xampp\htdocs\solder\bootstrap\autoload.php on line 17

**Comment by SniperHauss89** [comment]
I'm at the same brick wall as you are moocow9m. can anyone explain at least somewhat what this means?

**Comment by TheDoctorsLife** [comment]
Your missing the fileinfo extension, enable it, and try again.

**Comment by Moocow9m** [comment]
The thing is, iI have no idea where it is, or if I even have it!

On Thu, Jan 15, 2015 at 11:53 PM, Benjamin Hoffmeyer <
notifications@github.com> wrote:

> Your missing the fileinfo extension, enable it, and try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TechnicPack/TechnicSolder/issues/224#issuecomment-70211566>
> .
>



-- 
Matthew Taliancich 2

**Comment by Moocow9m** [comment]
Sorry.
I found my php.ini file had extension=php_fileinfo.dll  like this ;extension=php_fileinfo.dll
so i removed the simi-colon and it worked. Thanks.

**Comment by Moocow9m** [comment]
exception 'ErrorException' with message 'Undefined offset: 1' in C:\Xampp\htdocs\solder\app\libraries\UpdateUtils.php:124
Stack trace:
#0 C:\Xampp\htdocs\solder\app\libraries\UpdateUtils.php(124): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\Xampp\\htdocs...', 124, Array)
#1 C:\Xampp\htdocs\solder\app\libraries\UpdateUtils.php(81): UpdateUtils::getLocalChangeLog()
#2 C:\Xampp\htdocs\solder\app\controllers\DashboardController.php(16): UpdateUtils::getChangeLog()
#3 [internal function]: DashboardController->getIndex()
#4 C:\Xampp\htdocs\solder\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#5 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5834): Illuminate\Routing\Controller->callAction('getIndex', Array)
#6 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(DashboardController), Object(Illuminate\Routing\Route), 'getIndex')
#7 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'DashboardContro...', 'getIndex')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5385): call_user_func_array(Object(Closure), Array)
#10 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 C:\Xampp\htdocs\solder\bootstrap\compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 C:\Xampp\htdocs\solder\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 C:\Xampp\htdocs\solder\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 C:\Xampp\htdocs\solder\bootstrap\compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 C:\Xampp\htdocs\solder\bootstrap\compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 C:\Xampp\htdocs\solder\bootstrap\compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\Xampp\htdocs\solder\bootstrap\compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\Xampp\htdocs\solder\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 C:\Xampp\htdocs\solder\public\index.php(49): Illuminate\Foundation\Application->run()
#20 {main}

**Comment by Moocow9m** [comment]
When i logged in

**Comment by FlareHAX0R** [comment]
you might have to used my modified UpdateUtils.

**Comment by Moocow9m** [comment]
First how does it work(like how does it get installed) and what does it do(as in what does it do to fix it) and yes i want it if it will help.

**Comment by SniperHauss89** [comment]
I have the same issue following the composer installation step as Moocow9m. I would also like to know what he asked above regarding your modified UpdateUtils.

**Comment by Moocow9m** [comment]
Then we are both waiting for him to reply then.

On Fri, Jan 16, 2015 at 11:26 AM, SniperHauss89 <notifications@github.com>
wrote:

> I have the same issue following the composer installation step as
> Moocow9m. I would also like to know what he asked above regarding your
> modified UpdateUtils.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TechnicPack/TechnicSolder/issues/224#issuecomment-70289042>
> .
>



-- 
Matthew Taliancich 2

**Comment by SniperHauss89** [comment]
(update): so I changed the offset numbers:
			$commitData = array('hash' => $rawCommitData[0],
								'abr_hash' => $rawCommitData[1],
								'message' => $rawCommitData[3],
								'time_elapsed' => $rawCommitData[2]);
from the original above to all zeros:
			$commitData = array('hash' => $rawCommitData[0],
								'abr_hash' => $rawCommitData[0],
								'message' => $rawCommitData[0],
								'time_elapsed' => $rawCommitData[0]);
and it seems to load the dashboard now and says it's in need of an update and everything else seems to be working just fine. is that how you edited yours flareHAX0R?

**Comment by FlareHAX0R** [comment]
@Moocow9m my modified UpdateChecker prevents ALL shell_exec calls in updatechecker, and also stops offset checking. Reccomended if you get unknown offset or shell_exec is blocked

**Comment by Moocow9m** [comment]
Then please dropbox it and send me a link please

**Comment by FlareHAX0R** [comment]
hey, update solder. 0.7.0.8 just fixed some bugz! including this one!

**Comment by Moocow9m** [comment]
k
