### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by FrostySigh** [TechnicPack/TechnicSolder#225]
Is it possible to have a log file that will contain any errors during install?

**Comment by fcpwiz** [comment]
There should be a file called "error_log" in your solder folder.

**Comment by FrostySigh** [comment]
It seams like it doesn't generate one..

**Comment by fcpwiz** [comment]
Make sure you can see invisible files.

**Comment by GenPage** [comment]
There is a log that catches all errors/warns/logs

`app/storage/logs`

Logs are split by dates

**Comment by FrostySigh** [comment]
Ah, found it, Thanks!
