### ISSUE TITLE
Access to Solder problem

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#232]
Hello. I am on Debian 7.7. I have installed the solder, and put all of the files in /var/www/, but when I wan't to access it with http://localhost/index.php, the page said me "404 Not found". Do you have a solution ?
(I can drop you the config of files if you want)

**Comment by FlareHAX0R** [comment]
try http://127.0.0.1/index.php or http://localhost/public/index.php

Do you have apache/nginx AND php 5.5> installed?

**Comment by TheDoctorsLife** [comment]
I had this issue, normally, something is wrong with your nginx conf. Although It was @GenPage who helped me when I asked about what was wrong

**Comment by TheGeekdu74** [comment]
So, I got Apache 2, Nginx and PHP 5 installed on my Debian. When I do http://127.0.0.1/index.php, I got teh same error, but in a Terminal, I use "chmod -R 775 app/storage" and when I do http://localhost/public/index.php, I got "Internal server error"

**Comment by FlareHAX0R** [comment]
you have php 5.5, right? also Nginx and apache at the same time? Don't.

**Comment by TheGeekdu74** [comment]
Yes, I got PHP 5.6.3 and Nginx and Apache, what ?

**Comment by ET-Bent** [comment]
PHP 5.6.3 should work, no problem there. But you only need one websever either Nginx or Apache. You have to decide. Running both webservers on the same root directory could lead to problems. 

Important is that you set the right root directory in your Nginx or Apache config. The root directory should be your public folder inside your root solder folder so it should look something like this:

	root /var/www/[your-solder-root-folder-goes-here]/public/;
	index index.html index.htm index.php;

The example above is for a Nginx webserver.

The second line tells the server to look for a index.php aswell as index.htm. See if your config has a similar line.

**Comment by FlareHAX0R** [comment]
I personally reccomend NGINX, since Solder reccomends Nginx too.

**Comment by TheGeekdu74** [comment]
Ok Thanks for your help. I reinstall Debian, because I have a lot of problem with ports and SSH connection. So I do this after the reinstallation.

**Comment by FlareHAX0R** [comment]
I HIGHLY reccomend Ubuntu more.

**Comment by TheGeekdu74** [comment]
Sure, but I hate Ubuntu because this god d*** sudo crashed always so I passed under Debian

**Comment by TheGeekdu74** [comment]
So I have PHP 5.6.3, Apache 2 and teh Solder installed, but when I wan't to connect to it, I got this error : http://pastebin.com/nQ6WdfMt

The file in line 47 : 

![capture 5](https://cloud.githubusercontent.com/assets/9696697/5692422/9c28577e-98f5-11e4-829a-b6b40f47a78f.PNG)

**Comment by FlareHAX0R** [comment]
@TheGeekdu74 do you have the php curl, GD, and mcrypt extensions installed?
