### ISSUE TITLE
Issue with api link

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TechnicPack/TechnicSolder#234]
Since I have a Website with TechnicSolder in it, the issue is when I go to this link http://windmillgaming.tk/TechnicSolder/Solder/public/api/, it redirects me to my website because of the Trailing Slash, without the Trailing Slash after api it takes me to the correct api link for Solder, is there any way I can fix that? here is my .htaccess file for my Website: http://pastebin.com/rMwhHnD8

**Comment by xH3LLRAIZ3Rx** [comment]
oh and im using the LAMP stack on Ubuntu 14.04, I tried installing the LEMP Stack, but Nginx is very confusing when it comes to Rewrites

**Comment by GenPage** [comment]
You should probably look into setting up virtual hosts on your Apache server.

**Comment by xH3LLRAIZ3Rx** [comment]
how does one do that?

**Comment by xH3LLRAIZ3Rx** [comment]
ok so i got the Virtual Host Working at solder.windmillgaming.tk, now im having an issue where this shows Error in exception handler.

**Comment by xH3LLRAIZ3Rx** [comment]
ok nvm, forgot to set read/write perms

**Comment by xH3LLRAIZ3Rx** [comment]
ok so it still tries to redirect me to http://solder.windmillgaming.tk/api

**Comment by xH3LLRAIZ3Rx** [comment]
ok it works with http://solder.windmillgaming.tk/TechnicSolder/public/index.php/api/ sadly I cant use .htaccess but its fine

**Comment by xH3LLRAIZ3Rx** [comment]
ok good its working now :D
