### ISSUE TITLE
Solder link problem

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#236]
Hello, I have a problem with teh linking of the Solder. When I want to link the solder with this adress : http://odysse.myftp.org:46000/TechnicSolder/public/index.php/api/
I have this error : Whoops, looks like something went wrong
My profile number is 1166872, so GenPage, if you can help me, it's very cool !

**Comment by GenPage** [comment]
I am unable to access your api that you linked.

Most likely the issue is with the web server config.

**Comment by TheGeekdu74** [comment]
This is a problem with my port. I know how to fix that. I ask you if I need help

**Comment by ET-Bent** [comment]
Is your port 46000 opened or used somewhere else?

**Comment by TheGeekdu74** [comment]
My port 46000 is opened but badly redirected. I gonna fix that

**Comment by TheGeekdu74** [comment]
When I want to link the Solder, I have this error : [curl] 23: Failed writing body (0 != 39) [url] http://odysse.myftp.org:46000/TechnicSolder/public/index.php/api/verify/c5af03180b8cfe2803c6bedbb4c7256426a33f991cb47b8df364e68b2cc7d870
How I can fix that ?
