### ISSUE TITLE
Feature Request: Latest Version

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#238]
When creating a new pack, or adding mods to an existing pack, the selected version of the mod should be the latest available version automatically. It gets annoying when you add a bunch of mods to a build and you have to click each dropdown and make them the latest version manually.

**Comment by mcmielleman** [comment]
How does the system know wich version is latest?

**Comment by fcpwiz** [comment]
By the date of the version created.

**Comment by mcmielleman** [comment]
@fcpwiz that might not necessarily be true

**Comment by fcpwiz** [comment]
@mcmielleman if the dates won't work, then they could implement a system for this.
