### ISSUE TITLE
Feature request: Handle webserver timeouts better when updating minecraft version cache

### ISSUE THREAD

**Issue by jmarler** [TechnicPack/TechnicSolder#242]
Currently, whenever the Technic Platform is unavailable, we are unable to add new modpack versions when the Technic platform web cluster times out. 

In app/libraries/MinecraftUtils.php:

        public static function getMinecraftVersions() {
                $response = '';
                Cache::forget('minecraftversions');

                if (UrlUtils::checkRemoteFile('http://www.technicpack.net/api/minecraft', 15)){
                        $response = UrlUtils::get_url_contents('http://www.technicpack.net/api/minecraft', 15);
                        $response = json_decode($response, true);
                        krsort($response);
                        Cache::put('minecraftversions', $response, 60);
                } else {
                        $response = self::getMojangVersions();
                        Cache::put('minecraftversions', $response, 60);
                }

                return $response;
        }

When the technic platform web cluster times-out in it's response, the following error is generated:

> exception 'ErrorException' with message 'file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0' in /var/www/solder/app/libraries/MinecraftUtils.php:37'

Full pastebin of stack trace at: http://pastebin.com/mLvnHRKH 

The code needs to be able to recover from a web server timeout better. It may also be a good idea to ensure that a new version list is available before invalidating the cache. The error given is very misleading as it is a timeout that has occurred, not an PHP permissions error.

To recreate the web server timeout every time, I use [pathod](http://pathod.net/docs/pathod) to simulate a 100 second timeout with the command:

         # pathod -l 192.168.1.1 -p 80 -a "/api/minecraft=200:b@5k:p0,100"

I then add a /etc/hosts entry for www.technicpack.net pointing to pathod to simulate the timeout. You can also use pathod to simulate returning garbage, or a partial version file, etc. For example, if you feed it garbage, the ksort call fails and the application crashes.

**Comment by TheDoctorsLife** [comment]
I have found that making sure the minecraft version cache is up do date every time I start working prevents this from happening.

**Comment by sct** [comment]
There should definitely be some sort of catch here for when it fails to get the version information. I think @GenPage has it caching for at least an hour now but if you can't get the initial data it should at least give you a proper error instead of a stack trace :)

**Comment by GenPage** [comment]
@jmarler Thanks for the issue!

Yeah the issue here is actually with the the MinecraftUtils::getMojangVersions(). I did write this library in a rushed manner when the Technic Platform's Minecraft API was unavailable. I plan on swapping out `file_get_contents` for our UrlUtils library. It will be more stable. 

> It may also be a good idea to ensure that a new version list is available before invalidating the cache.

This is actually a very good idea and part of the reason why the versions are cached. I will implement this as well in the next update.

**Comment by jmarler** [comment]
Thanks for taking a look at this @GenPage. I really appreciate it.
