### ISSUE TITLE
Feature Request: Auto MC Version

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#243]
When you create a new build for a modpack, Solder automatically selects the latest available MC version (currently 1.8.1). It would be great when you create a new build, it would automatically select the currently used MC version used in the last build.

**Comment by Pyker** [comment]
But... 1.8.1 IS the currently used MC version. Sure, not for modded Minecraft, but they can't just guess that.

**Comment by fcpwiz** [comment]
@pyker Yes, but can't it look at the last used MC version on the last build?

**Comment by Pyker** [comment]
How would you propose they do that?

**Comment by fcpwiz** [comment]
@pyker by using the raw db data from the modpack builds

**Comment by sct** [comment]
This is a small QoL change that I don't think is really necessary. If someone were to PR it though I don't think anyone would really be against it being pulled in.

**Comment by fcpwiz** [comment]
@sct ok. it would be nice for the future though!
