### ISSUE TITLE
[Bug] [Minor] Radio buttons and check boxes rearrange their selections

### ISSUE THREAD

**Issue by Brycey92** [TechnicPack/TechnicSolder#244]
If you open a modpack's build management page and it has multiple builds, (mine has 5, but it happened with 4 too) and leave the page open for a while (a few hours?) while browsing in other tabs, and then come back to it, the selections of the Rec, Latest, Published, and Private radio buttons and check boxes flip over the horizontal axis. A refresh returns them to normal. This was present in both the last Solder 0.6 version and 0.7.0.7. I have not tested any other versions. I have thus far only tested on Google Chrome.

**Comment by Pyker** [comment]
This is weird. It might've been related to an autofill issue that was fixed with 0.7.6.
