### ISSUE TITLE
error after logging into solder...

### ISSUE THREAD

**Issue by SniperHauss89** [TechnicPack/TechnicSolder#245]
This is what I get after entering the default log in details:

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Github\Client' not found' in C:\xampp\htdocs\solder\app\libraries\UpdateUtils.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main}

It refers to line 47 in UpdateUtils.php.....

**Comment by GenPage** [comment]
You did not do `composer install`. This installs the Github Client.

**Comment by SniperHauss89** [comment]
that doesn't surprise me at all that it came back to that...
