### ISSUE TITLE
php artisan migrate Error

### ISSUE THREAD

**Issue by LyingCak3** [TechnicPack/TechnicSolder#246]
Hello,

Trying to set up solder on a ubuntu 14.10 and when I run the "php artisan migrate" I get this error.

[ErrorException]
  file_put_contents(/var/www/TechnicSolder/app/storage/cache/af/88/af8890ecbd
  59dc9cf10009f595624546): failed to open stream: No such file or directory

I checked, and doubled checked the database.php file to make sure it is set up correctly and it is.  Not sure were to go from here.

**Comment by sct** [comment]
You need to give the storage folder write permissions.

`chmod -R 775 app/storage/`
