### ISSUE TITLE
Error After Linking to Solder

### ISSUE THREAD

**Issue by Redlotus99** [TechnicPack/TechnicSolder#247]
Whenever I create a new modpack then click the Link to Solder button on the Technic site everything works fine.  I then click "Back to Modpack" link and I get a "Whoops Looks like something went wrong". I get this on the page http://www.technicpack.net/modpack/modpack-name

Any reason this would happen? 

Things I have tried:

Creating a new modpack
Creating a few build under the modpack in question
Checking permissions
Verifying URLs and settings
Verify API is accessible (http://70.188.224.146:8080/api)

Current page getting error http://www.technicpack.net/modpack/new-minereapers-test.566017

**Comment by Redlotus99** [comment]
It appears I got this working. I believe I have my mods setup correctly and as a test currently have 2 in Solder but neither are showing up. I just get "There was a problem pulling down the mod list for this modpack."

**Comment by sct** [comment]
This is happening because your packs don't have a recommended or latest version set. This is a bug in the platform that isn't catching that and is trying to render the mod list anyways. Set a latest/recommended version for the pack in solder and it will fix itself within an hour.
