### ISSUE TITLE
linking solder to TechnicPlatform account

### ISSUE THREAD

**Issue by SniperHauss89** [TechnicPack/TechnicSolder#248]
Hello, so I have everything in place but when I go to link solder to my account and add the api link which works by itself like it is supposed to but it doesn't want to link it just says:
[curl] 28: Connection timed out after 30000 milliseconds [url] http://.....

what could be the reason for this? also I noticed that navigating around my profile and profile settings is a little slow so is there something wrong on the website end or...?

**Comment by TheDoctorsLife** [comment]
Could you leave your solder's API link?

**Comment by SniperHauss89** [comment]
ok well the full API link is http://solderhauss.zapto.org/api/ it's through NO-IP. it's been working for everything else...

**Comment by TheDoctorsLife** [comment]
I won't work for me, are you sure you setup ports correctly?
