### ISSUE TITLE
Permission Issues, new mod pack

### ISSUE THREAD

**Issue by LyingCak3** [TechnicPack/TechnicSolder#252]
Hello again,

Using solder 0.7.0.8 and I can make a new modpack but solder says it does not have the correct permissions for the resource folder.  I have check the permissions and reassigned them just to make sure and still nothing.

Also I get this 500 error if I try to save it after modifying it:

exception 'ErrorException' with message 'mkdir(): Permission denied' in /var/www/TechnicSolder/app/controllers/ModpackController.php:268
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'mkdir(): Permis...', '/var/www/Techni...', 268, Array)
#1 /var/www/TechnicSolder/app/controllers/ModpackController.php(268): mkdir('/var/www/Techni...', 509, true)
#2 [internal function]: ModpackController->postEdit('2')
#3 /var/www/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#4 /var/www/TechnicSolder/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('postEdit', Array)
#5 /var/www/TechnicSolder/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(ModpackController), Object(Illuminate\Routing\Route), 'postEdit')
#6 /var/www/TechnicSolder/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ModpackControll...', 'postEdit')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#8 /var/www/TechnicSolder/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#9 /var/www/TechnicSolder/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/TechnicSolder/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/TechnicSolder/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/TechnicSolder/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/TechnicSolder/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/TechnicSolder/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/TechnicSolder/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/TechnicSolder/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/TechnicSolder/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/TechnicSolder/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main}

**Comment by GenPage** [comment]
This is still not Solder's problem. It's even telling you that permissions aren't correct.

The check is here: https://github.com/TechnicPack/TechnicSolder/blob/master/app/controllers/ModpackController.php#L214

**Comment by LyingCak3** [comment]
Not to be rude, but the permissions are set, I have checked them several times and even had other look at them to make sure everything is set up right.  We have not been able to figure it out, and everything was working correctly before the 0.7.08 update.

**Comment by sct** [comment]
Run `chmod -R 775 public/resources/`

Solder needs write permissions to that folder. This should be added to the install guide if it isn't already @GenPage

**Comment by LyingCak3** [comment]
It is, and I have confirmed the permissions, even tried 777 permissions with no luck.

**Comment by sct** [comment]
It has to be something on your end I don't know what to tell you.

**Comment by LyingCak3** [comment]
Not sure either, just tried a completely fresh install and getting the same 500 database error and permission errors when ever I work with the mod packs.

**Comment by GenPage** [comment]
Did you change the owner/group of the folders to your web server user? Permissions don't do anything if they still apply to `root`

Web server user is usually `www-data`. You may need to double check your web server config

**Comment by LyingCak3** [comment]
Had to change permissions for the whole TechnicSolder directory under var/www/, not sure if the directions are messed up or if didnt follow them correctly but now it is working.
