### ISSUE TITLE
Issue with Dashboard

### ISSUE THREAD

**Issue by zlepper** [TechnicPack/TechnicSolder#253]
Trying to access the dashboard after the latest solder update gives this error: http://paste.ubuntu.com/9766521/

**Comment by james58899** [comment]
I have the same error:
http://pastebin.com/1eyHCUFJ

**Comment by TheDoctorsLife** [comment]
Same error, http://pastebin.com/D7dPtAPx

**Comment by GenPage** [comment]
Logout and log back in.

**Comment by fcpwiz** [comment]
Ah! Thanks gen!

**Comment by TheDoctorsLife** [comment]
@fcpwiz just go to <urlofsolder>/login it will force log you out, but still, it would be nice if the session cookie would be invalidate after an update.
