### ISSUE TITLE
Error 500 while deleting a build

### ISSUE THREAD

**Issue by Tomson124** [TechnicPack/TechnicSolder#254]
I just wanted to delete a build from my modpack. It is the only build at the time but after clicking on "delete" I get this error:
http://pastebin.com/EkjKegja
I don't know what to do.

EDIT: After going back to the modpacks and checking the build... it's gone. But why is there this weird error?

Tomson

**Comment by GenPage** [comment]
This error can happen if you try to delete the build twice in quick succession. After the build is deleted, it doesnt exist. Hence the error
