### ISSUE TITLE
Having a '+' in the build number will fail to set the recommended/latest build

### ISSUE THREAD

**Issue by Nentify** [TechnicPack/TechnicSolder#255]
00:05 <Nentify> http://i.nentify.me/qSxp1S9T.png
00:05 <Nentify> http://i.nentify.me/SxAFBceS.png

2nd screenie is after I select 'Tekkify' again in the modpack selection on the navigation.

**Comment by TheDoctorsLife** [comment]
So that's the issue you were complaining about earlier.

**Comment by CannibalVox** [comment]
spaces do the same I believe.
