### ISSUE TITLE
Unable to Add Builds/Update Cache After Update From Last Night 1/16/2015

### ISSUE THREAD

**Issue by HalestormXV** [TechnicPack/TechnicSolder#256]
Directly after build 0.7.0.8 went live it became impossible to add a new build and to force update the Cache from the dashboard. Here is the error from when trying to add a new build:
http://pastebin.com/t3rbt6bw

How to reproduce - created a new modpack set originating version of modpack to 1.0.0. Then when to modpack managment and clicked "Create New Build"

Replication of forcing the cache update error:
Go to the main configs - click update cache and it spits "Error caching Minecraft versions. error: Internal Server Error"

Here is the error_log where you can see all of the errors:
http://pastebin.com/xzbCFyS4

Seems to be a possible syntax error in the MinecraftUtils.php file.

**Comment by monotonehell** [comment]
I'm seeing the same error under the same circumstances.

**Comment by monotonehell** [comment]
Seems there is a misnamed variable and a missing curly brace in app/libraries/MinecraftUtils.php
If I readx this diff correctly, this may have already been fixed here?.. https://github.com/TechnicPack/TechnicSolder/commit/a258685bd16977597b22aa6ccbeaf636c591bb57#diff-4

**Comment by GenPage** [comment]
This is already fixed with the latest hotfix.
