### ISSUE TITLE
0.7.0.8 Doesn't sort properly

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#258]
On the modpack list, it isn't alphabetically listed.

Version: 0.7.0.8

Here is a screenshot: http://s28.postimg.org/x7x93knv1/Screen_Shot_2015_01_17_at_9_43_44_PM.png

**Comment by TheDoctorsLife** [comment]
Looking at the api response from my solder http://solder.thedoctorslife.com/api/modpack/the-best-modpack-i-ever-made/0.1/ as you can see, mods aren't sent alphabetically.

**Comment by fcpwiz** [comment]
But wasn't that functionality added in 0.7.0.8? @TheDoctorsLife

**Comment by fcpwiz** [comment]
@TheDoctorsLife here is the commit: https://github.com/TechnicPack/TechnicSolder/commit/048b04e9e603405f7f723d06bd95b31375343e3c

**Comment by TheDoctorsLife** [comment]
it was supposed to be but it doesn't work.

**Comment by TheDoctorsLife** [comment]
cause the mods list gets the data from your solder

**Comment by fcpwiz** [comment]
Right. Do you know if it will be implemented in the next version?

**Comment by TheDoctorsLife** [comment]
I just told @GenPage in the IRC, give him some time to figure out why it doesn't work and how to fix it.

**Comment by fcpwiz** [comment]
Ok, thanks! Quick question, what is IRC? haha

**Comment by TheDoctorsLife** [comment]
look it up
