### ISSUE TITLE
Error 500 on any attempt to change settings.

### ISSUE THREAD

**Issue by drkmachine** [TechnicPack/TechnicSolder#259]
I cannot seem to track this down. Any attempt to edit/add users, mods, packs even logging out generates the error 500 page with this text.

http://pastebin.com/a7rq3a3U

I'm sure it is something simple that I have missed. Any assistance would be greatly appreciated.

**Comment by fcpwiz** [comment]
try: php artisan migrate

**Comment by drkmachine** [comment]
When I run the php artisan migrate it shows an error 

 SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'minecraft_md5' (SQL: alter table `builds` add `minecraft_md5` varchar(255) not null default '')

Seems that my db isn't set quite right. Going to see if I can work through that now.

I used this guide to help. 
https://github.com/TechnicPack/TechnicSolder/wiki/How-To-Install-TechnicSolder-for-Linux-%7BWIP%7D

**Comment by GenPage** [comment]
Don't use that guide. It hasn't been updated/checked yet. 

If you don't have any data you are worried about. `php artisan migrate:refresh` will roll everything back and re-migrate.

**Comment by drkmachine** [comment]
ok, thanks, that left me with 
[ErrorException]
  Undefined variable: mojangVersions

**Comment by drkmachine** [comment]
nevermined, I got it. odd permissions issue on the server. thanks
