### ISSUE TITLE
Modpack in the cloud

### ISSUE THREAD

**Issue by Spooky4672** [TechnicPack/TechnicSolder#260]
Is there a way to put the mods of the modpack, in a cloud drive (like google drive or mediafire) ? If yes, does the transfer pass trough my solder server or the technic client is receiving the mods directly from the cloud ?

Thanks in advance

**Comment by ET-Bent** [comment]
No it is not possible until there will be an implementation of the google drive api into solder. You could mount your google drive folder to your filesystem using this google-drive-ocamlfuse (https://github.com/astrada/google-drive-ocamlfuse), but this won't allow users to download the files directly from google. The files inside the mounted Gdrive folder link to the google server, but if you distribute your modpack via solder, your bandwidth will still be used.

**Comment by GenPage** [comment]
Solder only works as a index service. If you were to setup a repo on another server the only bandwidth being used on your Solder server is the API response being passed to the launcher which is negligible. Solder passes the URLs of the repo to the launcher and then the launcher initiates a new request to the repo server. We (Technic) have our mods hosted on a seperate mirror that can handle more bandwidth than what our Solder servers can.  

If you wish to host your mods on Dropbox/Amazon S3, I can research what it would take to add support.

**Comment by Razorskills** [comment]
Hey that would be kind of cool

**Comment by Spooky4672** [comment]
How do you do that ? I just set the repo_location to a dropbox ?
