### ISSUE TITLE
Undefined variable: mojangVersions

### ISSUE THREAD

**Issue by Zehir** [TechnicPack/TechnicSolder#261]
Hello, I get this error when I tried to create a new build;

exception 'ErrorException' with message 'Undefined variable: mojangVersions' in /home/www-data/minecraft/solder/app/libraries/MinecraftUtils.php:41

More details: http://pastebin.com/huZPqKqu

I use this version:
Current Version: v0.7.0.8
Current Commit: a258685bd16977597b22aa6ccbeaf636c591bb57

**Comment by Zehir** [comment]
It now works as I have absolutely nothing changed. This is probably a third-party site where the program downloads information that no longer worked.

**Comment by TheDoctorsLife** [comment]
Go to main settings, and make sure minecraft versions are cached so that way this doesn't happen again.

**Comment by Zehir** [comment]
Yes I just do it, thank
