### ISSUE TITLE
0.7.0.8 - Undefined index commit

### ISSUE THREAD

**Issue by cadyyan** [TechnicPack/TechnicSolder#262]
I'm getting the following error after updating to the latest stable release 0.7.0.8:
http://pastebin.com/GXfaFPuG

When updating I went from 0.7.0.0 to the latest version and used the steps from the wiki for updating.

    php artisan down
    git pull
    composer update
    php artisan migrate
    php artisan up

That error is given when going to the dashboard. Other pages seem to work alright if you know the URL.

What I've done so far:
 1) I tried checking for any missed updates
 2) I tried checking that the file permissions were there
 3) I tried reinstalling Solder
 4) I tried rebuilding the views
 5) I tried using the latest on the dev branch

Is there a step that I missed? If you need more information just let me know

Thanks for any help that you can give!

**Comment by TheDoctorsLife** [comment]
goto <solderurl>/login

**Comment by cadyyan** [comment]
Ah that does seem to fix it. It's strange though because when I would manually enter the URL to a page it would say I'm still logged in. Is that some problem with caching on my end do you think?

**Comment by TheDoctorsLife** [comment]
No @GenPage did something so if your logged in when you update it breaks your solder interface till you logout and back in again  (not anything outside of solde though, like it wouldn't affect other people just the ones visiting your site outside of /api) I think he's working on making it auto-log you out when you update for now on.

**Comment by cadyyan** [comment]
Ah gotcha. Thanks for your help!

**Comment by TheDoctorsLife** [comment]
np
