### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by Spooky4672** [TechnicPack/TechnicSolder#263]
I have a fresh install on a raspberry pi, (debian) I installed Solder, everything was fine, I added mods, I touched a bit everything ... etc and today : http://pastebin.com/BuriFGYq

**Comment by IdleGandalf** [comment]
Can confirm this happening, fresh solder install.

**Comment by Spooky4672** [comment]
Fresh how ? What have you done ? Like me ?

**Comment by IdleGandalf** [comment]
Fresh install after this install guide: https://github.com/TechnicPack/TechnicSolder/wiki/Getting-Started (git+composer)

**Comment by Spooky4672** [comment]
To restart nginx also restarts mysql db and every other installed things?

**Comment by Spooky4672** [comment]
I have updated solder, same thing ...

**Comment by Spooky4672** [comment]
This is weird : when I try to access solder with the local address (raspberrypi.*******) from my network, I get the error but not with the external address, so it's not a problem with solder itself

**Comment by Spooky4672** [comment]
Could be two things : 
-solder is not accessible locally
-the hostname (of th pi) is not the same internally and externally and solder don't like it

**Comment by TheGeekdu74** [comment]
So what is the solution ?

**Comment by Spooky4672** [comment]
I don't know, everything works fine from Internet, but locally I can access to solder just with the IP address, solder do not like domain name this is weird because it only when I use a browser (firefox), with putty or filezilla, no problem, ip or hostname ....

**Comment by Spooky4672** [comment]
Now I have the same error even with the IP, while there is no problem with putty

**Comment by Spooky4672** [comment]
I found the problem : http://raspberrypi.*******.me/ was automatically redirected to http://raspberrypi.spooky4672.me/dashboard even if I was not logged in.
If I replace to : http://raspberrypi.spooky4672.me/login, that works fine
