### ISSUE TITLE
Create a page

### ISSUE THREAD

**Issue by Moocow9m** [TechnicPack/TechnicSolder#264]
Quick question how would one create a new page(say for example a create accounts for new users with a modpack created at the same time with the username as the modpack name and permissions to edit it)? I would like to host a solder for who would want to use it but creating users manually is long and hard. I tried to add it but I don't know where to put it or how to add it in the index.php(Is that the right place?).

**Comment by GenPage** [comment]
We have no plans to add a public registration option to Solder at this time.
