### ISSUE TITLE
0.7.0.8 json error

### ISSUE THREAD

**Issue by mcpirate** [TechnicPack/TechnicSolder#265]
Good afternoon! I have a problem:
Launcher 
Response launcher
[B#0] 2015/01/21 13:44:54 [SEVERE] net.technicpack.rest.RestfulAPIException: Error parsing response JSON at URL [http://platform.grimcube.ru/api/modpack/vanilla]
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:106)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfo(HttpPlatformApi.java:55)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfoForBulk(HttpPlatformApi.java:49)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.pullAndCache(ModpackCachePlatformApi.java:132)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.getPlatformPackInfo(ModpackCachePlatformApi.java:96)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.launcher.ui.components.modpacks.ModpackSelector$6.run(ModpackSelector.java:301)
[B#0] 2015/01/21 13:44:54 [SEVERE] Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 63
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.Gson.fromJson(Gson.java:803)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.Gson.fromJson(Gson.java:768)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.Gson.fromJson(Gson.java:717)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at com.google.gson.Gson.fromJson(Gson.java:689)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:90)
[B#0] 2015/01/21 13:44:54 [SEVERE] 	... 5 more
PS. Latest version of the launcher
Json
{"name":"vanilla","display_name":"Vanilla","url":null,"icon":"http:\/\/platform.grimcube.ru\/resources\/vanilla\/icon.png","icon_md5":"","logo":"http:\/\/platform.grimcube.ru\/resources\/default\/logo.png","logo_md5":"70a114d55ff1fa4c5eef7f2fdeeb7d03","background":"http:\/\/platform.grimcube.ru\/resources\/default\/background.png","background_md5":"d91d4ba1ca99b3d0375c120e81186536","recommended":"2","latest":"2","builds":["1","2"]}

**Comment by GenPage** [comment]
Are you still having issues? This isn't an issue with Solder as the response is valid JSON. Its possible that you experienced a network drop momentarily that altered the Solder response. 

Here's where I checked: http://jsonformatter.curiousconcept.com/

**Comment by mcpirate** [comment]
[2015-01-21 21:27:28] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /usr/home/mcpirate/www/launcher.grimcube.ru/platfor$
Stack trace:
#0 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(5060): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(5048): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, tru$
#6 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /usr/home/mcpirate/www/launcher.grimcube.ru/platform/public/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
