### ISSUE TITLE
Solder Script for Mac: Speed Up Updating Mods!

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#267]
Hey all! I would like to introduce you to 'Solder Mod Updater'. This app lets you select a .jar file, then the app properly sets the .jar up to work in the Solder repo. The final output .zip gets sent to a folder on your desktop called "Finished Mods". This will significantly speed up updating a large quantity of mods. This app if for mac only, I think.

GitHub releases: [HERE](https://github.com/fcpwiz/SolderModUpdater/releases)

**Comment by fcpwiz** [comment]
Just updated to 1.1. Fixed up file path, changed button names, and cleaner file movement.

**Comment by GenPage** [comment]
This is not a advertisement board, please advertise this elsewhere on Technic's social media (reddit, forums, etc). Thanks!
