### ISSUE TITLE
Internal server error in dashboard

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#270]
Hello, I have a problem with teh dashboard of the TechnicSolder 0.7.0.8. When I click on "Dashboard", I have this error : http://pastebin.com/euzhLKnj 
Anybody can help me ? I am on Debian 7.7

**Comment by fcpwiz** [comment]
Go to /login after your solder domain.

**Comment by TheGeekdu74** [comment]
Ok thanks !
