### ISSUE TITLE
Bug: Mobile Login Page

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#273]
Hi, the login page on a mobile platform looks a bit weird. The logo isn't centered.

Here is a [screenshot](http://s2.postimg.org/jmrvpkfl5/image.jpg)

**Comment by mcmielleman** [comment]
well lower priority than this is impossable xD ;)

**Comment by fcpwiz** [comment]
Haha I know. It would be nice in a "perfect world" though.
