### ISSUE TITLE
Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Giulio1708** [TechnicPack/TechnicSolder#274]
Hi, I have installed solder on my Debian 7 (86x) VPS.
I installed it in /etc/ folder, my app and public directories have 755 CHMOD (and 777 for app/storage and public/resources) ... but when I try to login it returns me this error: http://pastebin.com/vN5QMweS

If you want to test it out by yourself, the URL is: http://vps124898.ovh.net
User and password are default ones (admin@admin.com with admin password)

How can I solve this issue?
Thanks,
Giulio.

**Comment by fcpwiz** [comment]
Huh. Did you migrate the database?

**Comment by Giulio1708** [comment]
No, I didn't.
I use the pre-setup SQLite included in the distribution. I didn't did nothing on the databse, is there some edits that i shoud do before getting it working?

**Comment by fcpwiz** [comment]
Are you updating to 0.7.0.8 or starting from scratch?

**Comment by Giulio1708** [comment]
This is the first time that I use Solder, so ti's from scratch.

**Comment by fcpwiz** [comment]
Hmm ok. Do you have all these installed?

PHP
PHP MCrypt
PHP Curl
PHP GD
MySQL
Composer
FileInfo
Mbstring

**Comment by Giulio1708** [comment]
Yes, I have installed them all.

**Comment by fcpwiz** [comment]
Doof. I'm sorry. Go to http://vps124898.ovh.net/login

**Comment by Giulio1708** [comment]
Yep, of course I did it but, when I log-in, it returns me the 500 error.

**Comment by fcpwiz** [comment]
That error has to do with PDO. But it looks like you have it installed. Huh.

**Comment by Giulio1708** [comment]
Uhm "General error: 14 unable to open database file" maybe a CHMOD problem? But I checked the  production.sqlite and is "755"

**Comment by sct** [comment]
Even if you are using sqlite you still have to run the initial migration. ``php artisan migrate``

**Comment by Giulio1708** [comment]
Nothing
![image](https://cloud.githubusercontent.com/assets/9356195/5891903/c296a60a-a4ac-11e4-883e-1193f3ff5c43.png)

**Comment by Giulio1708** [comment]
Alright, the issue is about the sqlite database.
I created a mysql database, migrating tables and everything seems working fine.
Thank you all for the help.
