### ISSUE TITLE
Solder linking problem

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#275]
Hello, I have a problem when I want to link my solder to the website TechnicPack.net. I got this error : 

[curl] 23: Failed writing body (0 != 39) [url] http://odysse.myftp.org:46000/TechnicSolder/public/index.php/api/verify/c5af03180b8cfe2803c6bedbb4c7256426a33f991cb47b8df364e68b2cc7d870

Anybody can help me please ? Genpage ? : D
I'm on Debian 7.7 and I using Solder 0.7.0.9 and in update checker I have this : 

Shell Access: Yes
Git Installed: Yes
Git Repository Found: Yes

**Comment by sct** [comment]
Link your Solder please.

**Comment by TheGeekdu74** [comment]
I try to do it, but if failed

**Comment by sct** [comment]
http://odysse.myftp.org:46000/TechnicSolder/public/index.php

Is this your solder install? Because if it is, I can't access it.

**Comment by TheGeekdu74** [comment]
Yes it's my solder install

**Comment by sct** [comment]
I don't know, that's on your end bud.
