### ISSUE TITLE
Change Build Sorting

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#276]
Currently, builds are sorted by build number. The issue is that 1.2a is sorted above then 1.2.6. That is because 'a' is higher than '.'  It would be great if builds were sorted automatically by "#" and not "Build Number".

Here is a [screenshot](http://s11.postimg.org/lnwictjab/image.jpg)
Red is what it should be sorting by. blue is what it is currently sorting by.

**Comment by TheDoctorsLife** [comment]
I agree

**Comment by Razorskills** [comment]
Maybe there could be a settings page that could have the option of switching between some sorting settings. because if they switch it to sort by Build number, Some people may not agree.

Although I do agree with this since sometimes I have that small annoyance.
