### ISSUE TITLE
Solder Update Error

### ISSUE THREAD

**Issue by Tomson124** [TechnicPack/TechnicSolder#277]
I wanted to update solder but when doing ´git pull´ I get this error: http://pastebin.com/kmwtL7Pf
Hope anyone can help me.

**Comment by sct** [comment]
Have you modified any of these files? Either way the quickest way to fix this would be to run `git reset --hard`. This will reset your tracked files to the most recent local commit and then you will be able to `git pull` the latest changes without issue.

**Comment by sct** [comment]
Whoops didn't mean to close that. Let me know if it works!

**Comment by Tomson124** [comment]
No I don't modified one of them but if I reset the files will my modpack folder with all mods and builds deleted as well?

**Comment by sct** [comment]
No they will not.

**Comment by Tomson124** [comment]
okay good, then I try it.

**Comment by Tomson124** [comment]
Thanks, that fixed it.
