### ISSUE TITLE
Question solder

### ISSUE THREAD

**Issue by mcpirate** [TechnicPack/TechnicSolder#279]
Updated launcher, put Solder latest version.
When the launcher put the link to Solder launcher writes an error to JSON.
My solder: http://platform.grimcube.ru/api/modpack/vanilla
Technic: http://api.technicpack.net/modpack/vanilla
What did I do wrong that such a huge difference?

**Comment by sct** [comment]
You cant name your solder pack the same name as an official pack? I don't think you understand really how solder works. Read the wiki to learn how to link your solder to the platform.
