### ISSUE TITLE
Cannot redeclare mb_substr_count()

### ISSUE THREAD

**Issue by DAOWAce** [TechnicPack/TechnicSolder#283]
Followed the directions to setup Solder by the book, but I've run into an error.

When running the *composer install --no-interaction* command it goes through a whole bunch of stuff then spits out this error.

>Writing lock file
Generating autoload files
PHP Fatal error:  Cannot redeclare mb_substr_count() (previously declared in /var/www/html/solder/vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup/mbstring.php:37) in /var/www/html/solder/vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup/mbstring.php on line 49
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
                                                                                                       
>  [RuntimeException]                                                                                   
  Error Output: PHP Fatal error:  Cannot redeclare mb_substr_count() (previously declared in /var/www/html/solder/vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup/mbstring.php:37) in /var/www/html/solder/vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup/mbstring.php on line 49

The php artisan commands don't work.

I have PHP5.5 and the required extensions using a MySQL database.

I don't know what's wrong, at all.  This is my first time managing a linux webserver.  I'm running an AWS EC2 server with Amazon Linux as well.

Been learning to setup AWS services all day so I'm really burned out and heading to bed.

Also, the SSH git command doesn't work for me, gives a "permission denied (publickey)" error, but the HTML git works just fine so this isn't much of an issue.

**Comment by GenPage** [comment]
This is most likely because the PHP module "mbstring" is not enabled. You can check for it using this `php -m | grep mb` 

`php -m` returns a list of all installed/enabled php modules, `grep mb` filters the output

HTML git is perfectly fine to use.

**Comment by DAOWAce** [comment]
Not just not enabled, but not even installed!

php-common is installed, but it seem we still have to install a bunch of other extensions not included.

Installed, worked fine.

>Writing lock file
Generating autoload files
Generating optimized class loader
Compiling common classes
Compiling views
Application key xxx set successfully.

I guess I should look up what's commonly installed with PHP packages; doing it manually (and upgrading to PHP5, which is not the default on AWS; it's old 5.3) has missed a lot.

**Comment by DAOWAce** [comment]
Bah, now I'm getting *Error in exception handler.* when I access the directory for soldier in a browser.

**Comment by sct** [comment]
Probably haven't given the storage folder write permissions.

**Comment by DAOWAce** [comment]
Didn't catch your comment (never refreshed webpage or checked e-mail).

I gave the two directories full write permissions and it gets around the error, but as mentioned in my edit it's redirecting to a dashboard location which just doesn't exist at all.

I tried to start over from scratch again to reset all the ownership I was messing around with but no dice; still no dashboard folder.

Giving up banging my head against it at this point. Expected to be on my own for many more hours, but hopefully I can get further advice on this issue.

**Comment by TheDoctorsLife** [comment]
There is no dashboard folder, the dashboard as well as every other page in the application are served via the index.php file.

**Comment by DAOWAce** [comment]
The guide only mentioned 2 folders, public/resources and app/storage.  And 775 didn't work, it had to be 777 (which is bad).

I'm using a LAMP setup on Amazon Linux (which makes it hard to mirror commands as they're different from something like ubuntu which most people use), my user is ec2-user and my group is just www and has ownership of the entire www folder and its subfolders.

When I accessed the solder/public folder after fixing the permissions it immediately re-directs to public/dashboard.  I didn't try going to the index.php file directly as that's what browsers load by default.

I'll try to look into it again after I take a break, but unless I'm being an idiot somewhere, everything should be setup properly.

**Comment by sct** [comment]
Check the logs in `app/storage/logs` and let me know if that has anything.

**Comment by DAOWAce** [comment]
There's nothing but .gitignore in the log folder.

**Comment by sct** [comment]
Well if for whatever reason Solder doesn't have write permissions to your sqlite database I could see this happening.

**Comment by DAOWAce** [comment]
Well.. I just sorted out the issue, mostly.

It was a mismatch between ownership of the public_html directory (/var/www/html).  The server is owned by *root*, but public_html is all owned by the AWS EC2 user, *ec2-user*.

For some reason, ec2-user didn't have access to things it wasn't the owner of, despite being in the same www group root is in.  I am too uneducated in this to understand why.

So, solder is working and I have access to the dashboard, though I still have to access index.php.  I don't know why accessing the bare /public directory in a browser won't make it work.

Unfortunately, the problems haven't ended yet.  I can't change users or add mods/modpacks.  It throws the same 'exception handler' error, which is apparently a permissions error from this whole experience.

At this point, I'm about to just blow up the server and start from scratch and not touch permissions, as during setup it said to do a whole bunch of things (followed this tut: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-LAMP.html).  I really don't know what else I can do.

All this just to stop a 250MB download for my modpack when I make a single change. *sigh*

**Comment by sct** [comment]
Doesn't EC2 have ubuntu distributions? It would have probably made this a lot easier.

**Comment by TheDoctorsLife** [comment]
I can help you out with this @DAOWAce just ring me up on skype, and I can help you out, it's not the hardest thing to install, just takes some trial and error.
Skype: The_Doctors_Life

**Comment by DAOWAce** [comment]
> Doesn't EC2 have ubuntu distributions? It would have probably made this a lot easier.

Aside from the fact I haven't used Ubuntu either..

I administer Windows based PCs, not Linux or Mac; my experience with those is extremely limited, moreso if they're webservers I have to SSH into without having full remote control like a normal desktop PC.

> I can help you out with this @DAOWAce just ring me up on skype

Thanks, but I'm one of the few people who don't actually use Skype, though I threw it on a VM just to test it out so I suppose I could talk there.
