### ISSUE TITLE
Help creating modpack

### ISSUE THREAD

**Issue by Giulio1708** [TechnicPack/TechnicSolder#284]
Hi there,
I have a trouble creating a modpack. I'm Italian and I have some trouble understanding how to create a new modpack and where to put zips, jars, etc.
Can someone link me a step by step tutorial or tell me how to create a modpack with the right hierarchy?

Thank you

**Comment by sct** [comment]
This is an area for bug reporting not help using the software. Try starting here: https://github.com/TechnicPack/TechnicSolder/wiki
