### ISSUE TITLE
When I open solder webpage it says it can't open requiered file

### ISSUE THREAD

**Issue by mymindstorm** [TechnicPack/TechnicSolder#292]
![screenshot 80](https://cloud.githubusercontent.com/assets/6856311/6007603/1db3e18a-aae1-11e4-8244-6a2613c0b0b0.png)

**Comment by fcpwiz** [comment]
Are you sure that all of your needed solder files are uploaded? It looks like it's missing a file.

**Comment by mymindstorm** [comment]
Here's my solder folder, can you see anything wrong?

On February 4, 2015, at 4:43 PM, fcpwiz <notifications@github.com> wrote:

Are you sure that all of your needed solder files are uploaded? It looks like it's missing a file.

**Comment by fcpwiz** [comment]
I can't see the file. Try responding on this site instead of via email.

**Comment by mymindstorm** [comment]
Anything wrong here?
![screenshot_2015-02-04-16-46-21_kindlephoto-76412596](https://cloud.githubusercontent.com/assets/6856311/6051466/ea48fcfa-ac8d-11e4-89c6-dd886ec92f3b.jpg)

**Comment by fcpwiz** [comment]
Do you have a directory under 'vender'?

**Comment by fcpwiz** [comment]
The error above is asking for a file in the vendor directory. You can get that folder by using this command: composer install --no-interaction

This will take a few minutes to complete due to the many dependencies that are being downloaded.

**Comment by mymindstorm** [comment]
@fcpwiz I don't have it because I uploaded this from my computer and xampp had so many files I got confused and uploaded what I could see in the repo

**Comment by fcpwiz** [comment]
Ok. Well just use: `composer install --no-interaction` and you're good!

**Comment by mymindstorm** [comment]
@fcpwiz I already did, just had no idea that I needed it
