### ISSUE TITLE
[Feature] Launcher/Solder Multi-File Download and Reassembly

### ISSUE THREAD

**Issue by Brycey92** [TechnicPack/TechnicSolder#293]
I hereby request the ability to specify certain groups of files in solder that would be downloaded and reassembled into 1 file in the modpack directory. For example, I have a 32mb audio resource litemod that I don't want users to have to redownload every time I add a music file to it. Instead, ideally, I would add another file to the group in solder. Upon updating the pack, the launcher would download this small file, and repack it with the other files of the same group that are already in the modpack's cache folder.

Related feature requests:
https://github.com/TechnicPack/LauncherV3/issues/35
https://github.com/TechnicPack/TechnicSolder/issues/294
https://github.com/TechnicPack/LauncherV3/issues/36

**Comment by Brycey92** [comment]
https://github.com/TechnicPack/LauncherV3/issues/35

**Comment by fcpwiz** [comment]
Smart idea! I hope Gen sees this!

**Comment by mcmielleman** [comment]
Yes

**Comment by spannerman79** [comment]
What (I assume) your asking for is [delta file](https://en.wikipedia.org/wiki/Delta_update) updating?

**Comment by Brycey92** [comment]
Yes, essentially @spannerman79.

**Comment by Pyker** [comment]
Closing this: https://github.com/TechnicPack/LauncherV3/issues/35#issuecomment-716065394
