### ISSUE TITLE
[Feature] Download Resource Packs and Inessential Mods After Initial Download

### ISSUE THREAD

**Issue by Brycey92** [TechnicPack/TechnicSolder#294]
In addition to my earlier request, I propose a feature where the launcher downloads essential mods and allows the user to launch the pack, but continues to download files such as resource packs and other large inessential files. Such files would be marked in solder as something like "post-initial-download."

If my other feature, Launcher/Solder Multi-File Download and Reassembly, is implemented, I also request compatibility with this feature, for even more streamlined modpack deployments.

Related feature requests:
https://github.com/TechnicPack/LauncherV3/issues/36
https://github.com/TechnicPack/LauncherV3/issues/35
https://github.com/TechnicPack/TechnicSolder/issues/293

**Comment by Pyker** [comment]
Why would we implement this? You'd end up with broken modpacks, this is not how Minecraft loads things.
