### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by mymindstorm** [TechnicPack/TechnicSolder#295]
So I get everything setup and it gives me this:
![image](https://cloud.githubusercontent.com/assets/6856311/6052904/516ee826-ac9e-11e4-923e-e98b2fa03512.png)
All my files:
![image](https://cloud.githubusercontent.com/assets/6856311/6052933/9de7ed10-ac9e-11e4-885b-1368cb6687db.png)

**Comment by fcpwiz** [comment]
Doesn't look like you have composer.lock

**Comment by mymindstorm** [comment]
@fcpwiz is it possible that you could send me a picture of your directory, in windows use snipping tool
