### ISSUE TITLE
SQL Tables Not Found

### ISSUE THREAD

**Issue by figtito** [TechnicPack/TechnicSolder#296]
I'm getting some table not found errors at various points. I tried the entire installation process twice on one machine and setup a new computer and tried it again but keep getting the same errors.

When I click on client config I get this

 *500 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'solder.clients' doesn't exist (SQL: select * from `clients`)*

Whenever I try to add an user or edit the existing I'm getting this

* 500 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'solder_keys' in 'field list' (SQL: update `user_permissions` set `solder_full` = 1, `solder_users` = 0, `mods_create` = 0, `mods_manage` = 0, `mods_delete` = 0, `updated_at` = 2015-02-05 12:13:40, `solder_keys` = 0, `solder_clients` = 0, `modpacks_create` = 0, `modpacks_manage` = 0, `modpacks_delete` = 0 where `id` = 1)*

![1](https://cloud.githubusercontent.com/assets/10869253/6065113/5b409a04-ad28-11e4-82f8-51e5cfebeef6.png)

Any ideas?

**Comment by fcpwiz** [comment]
Are you updating from 0.6 or creating from scratch?

**Comment by figtito** [comment]
Its a new install with a fresh Nginx and Mysql install as well.

**Comment by fcpwiz** [comment]
This looks similar: https://github.com/TechnicPack/TechnicSolder/issues/259

**Comment by figtito** [comment]
I was able to run this command as referenced in 259 and all the tables were added. Thanks!
php artisan migrate:refresh

**Comment by fcpwiz** [comment]
Anytime
