### ISSUE TITLE
"The Modpack Location you entered is not a valid location."

### ISSUE THREAD

**Issue by xJon** [TechnicPack/TechnicSolder#297]
I am trying to roll back from solder after some issues with the host, now I can't put my zip file, getting [this](http://i.imgur.com/VZISFFB.png) error, I can't  understand that at all.
Thanks for any reply.

**Comment by daytimepanther** [comment]
Hello John, I got this error when I tried to host solder on a computer on my local network. If you're not doing this can you check to see if the launcher sees that the pack has solder enabled? I attached an example of what it would look like.
![screen shot 2015-02-05 at 9 34 06 pm](https://cloud.githubusercontent.com/assets/10703491/6073635/d70bb6d6-ad7e-11e4-9106-f5b6e26795e2.png)

**Comment by xJon** [comment]
@daytimepanther I don't really care about the solder at this point, I just wish to put my normal download link and I [can't](http://i.imgur.com/VZISFFB.png) - Why is that?

**Comment by daytimepanther** [comment]
I do not think that url is correct because when I try to access it I have to login to a Microsoft account. Try using Dropbox. Do [this](https://www.dropbox.com/en/help/201) to the link to make it a direct download and paste the direct link into the modpack location.

**Comment by The-1-7-10-Pack** [comment]
@daytimepanther Try [this](https://onedrive.live.com/?cid=a82ebd44a04efe2c&id=A82EBD44A04EFE2C%213182) download link, is it working for you?

**Comment by xJon** [comment]
@daytimepanther Try [this](https://onedrive.live.com/?cid=a82ebd44a04efe2c&id=A82EBD44A04EFE2C%213182) download link, is it working for you?

**Comment by daytimepanther** [comment]
Yes that downloaded perfectly! If you have a problem with that link this is definitely a Technic issue that needs to be looked at and is beyond my ability to help.

**Comment by daytimepanther** [comment]
Ok so I tested this and it didn't work with a fresh modpack. So I started to download it, canceled it, went to my downloads in chrome, copied the link it was downloading from ("https://k2ppsa.bn1301.livefilestore.com/y2mVOZ5OpQ3o9RJY55mXMQjYWDXTGu1UAdZGCaiNuvqa8-8Q_g_3geCYZv8GsIcy4ruM-9tKzFeGTY_RVLR_GLXSZFNVCA1dDOv7FzUUGXFsaKSztO5a88Viz26JoM1owUgFonqM0L5UpeyM661d7s_hQ/The%201.7.10%20Pack%20v0.7.0.zip?download&psid=1"). This link works in the modpack location but the one you posted earlier oddly does not.

**Comment by xJon** [comment]
@daytimepanther That's very weird, I hope that the Technic Staff will be able to help me.
I don't want to use the long link because it specified from what server exactly it'll download from onedrive.

**Comment by daytimepanther** [comment]
I understand, would you like for me to remove the link? You could try dropbox but I understand if you want to stick with what you've been using.

**Comment by xJon** [comment]
@daytimepanther No it doesn't really matters. Dropbox has low bandwitch limit, I have a big account on onedrive.

**Comment by xJon** [comment]
Well I guess that I can close that.
