### ISSUE TITLE
Modpack offline

### ISSUE THREAD

**Issue by tieran02** [TechnicPack/TechnicSolder#299]
i have tried getting my solder modpack to download in the client however every time i do so it keeps saying its not installed or corrupt and can't be played offline. i cant seem to find a solution or even find what the problem is.
 
i have not added any mods yet because i need to see if it works before hand.

**Comment by mcmielleman** [comment]
your modpack needs a version, i dont think you made one

**Comment by tieran02** [comment]
I have just made a version within my Solder and waited 10 minutes and still it is offline.

**Comment by tieran02** [comment]
never mind i got it to work i had to wait a bit more after adding a version thankyou
