### ISSUE TITLE
Client failed to download but in browser the download works

### ISSUE THREAD

**Issue by AragurLP** [TechnicPack/TechnicSolder#303]
Hey, I made a modpack, with solder all worked.
But then I saw there's a new version.
I reinstalled the software (on Debian) and made the modpack new.
But now, if I want to install the modpack, the download fails.

Modpack-Link: http://www.technicpack.net/modpack/m3d13valcraft.590242

**Comment by fcpwiz** [comment]
Your modpack link doesn't seem to work.

**Comment by AragurLP** [comment]
Yes but why?

**Comment by fcpwiz** [comment]
It doesn't look like "m3d13valcraft" is in the Technic Platform directory. You are going to have to make a new modpack here: http://www.technicpack.net/modpack/create

and link that pack to your solder.

**Comment by AragurLP** [comment]
Okay, thank you. 
I think last time the import failed.
