### ISSUE TITLE
Solder Reverse Proxy ?

### ISSUE THREAD

**Issue by joshuader6** [TechnicPack/TechnicSolder#304]
Im trying to access Solder using a reverse Proxy in nginx but it doesnt seem to work.

This is the Reverse Proxy:
```
location ~ ^/solder($|./*) {
        proxy_pass        	http://127.0.0.1:85;
	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

This is the Actual Solder Server: 

```
server {
        # The port to listen on. By default, any webserver is on port 80
        listen 85;
        # The location for the root of your web server
        root /usr/share/nginx/TechnicSolder/public/;
        # The files to look for to open when no file is specified. For example, 192.168.1.111 will open the index.php page
        index index.php;

		
        # Forward all requests to the TechnicSolders main file
        location / {
             try_files $uri $uri/ /index.php$is_args$args;
        }

        # Pass the PHP scripts to FastCGI server listening on /var/run/php5-fpm.sock
        location ~ \.php$ {
                try_files $uri /index.php =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

**Comment by TheDoctorsLife** [comment]
It don't work isn't to specific, is there an error? what happens when you go to your ip to access solder.

**Comment by joshuader6** [comment]
Actually i cant provide an error. Or a Log or something like that. 

I can Access Solder directly through Port 85. But when i try accessing it via the Reverse Proxy i get: Error in exception handler.

I think this is an nginx rrror page. I have seen this before. In order to fix this problem i always had to change the urlbase of the site to match the location set for the reverse Proxy.

because its the same page i would get if i try to access solder using http://myip:85/solder/
Notice the /solder at the end.

Sorry i didn't specify this enough.

**Comment by TheDoctorsLife** [comment]
"Error in exception handler." chmod -R 775 /<yourtechnicsolderfolder>

**Comment by joshuader6** [comment]
Nope didnt work

1. Nginx as root
2. Technicsolder Location chmod -R 775 & chown -R root

Still the same 

It seems to be related to the /solder Uri in the Location of the reverse proxy

**Comment by Pyker** [comment]
Try `location ~ ^/solder($|/.*) {` instead of `location ~ ^/solder($|./*) {`.
