### ISSUE TITLE
[wiki] Adding mods to the Mod Library incomplete / difficult to understand.

### ISSUE THREAD

**Issue by zudomc** [TechnicPack/TechnicSolder#305]
Whoever wrote it didn't do a particularly good job.

> Go to the FTP or folder that you are hosting the repo in
> Create a new folder called "mods" (no quotes) inside the repo folder

I don't know if this means in the root folder of solder (i.e. /var/www/TechnicSolder) or somewhere else.

> Go to the Directory that you have your mod in that would like to use

What does this even mean?

> Mod packages are unzipped to the root modpack directory. As such, they have to be packaged accordingly.

That doesn't tell me what to do.

#### Can we please have some more details?

**Comment by mcmielleman** [comment]
First off all, at the bottom of that page is an example, look at it.

1. It doesnt specify where the repo should be, its your choice, so it doesnt say where...

2.go to the directory (in which the mod is saved) <-- (which you want to use) 
not vital information

3. Look at the example, this is not a hold-your-hand piece of software, figure it out, try things

**Comment by zudomc** [comment]
Hmm.
