### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by benjicraft** [TechnicPack/TechnicSolder#307]
I get this error:

Warning: require(C:\xampp\htdocs\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\bootstrap\autoload.php on line 17

I am using XAMPP with Technic solder

**Comment by vlee489** [comment]
Windows Isn't supported and you will not get help.
