### ISSUE TITLE
500: shell_exec() has been disabled for security reasons

### ISSUE THREAD

**Issue by FlareHAX0R** [TechnicPack/TechnicSolder#309]
I install solder via a local copy of solder... and a local database... blah blah blah... transfer it to Hostinger.... and I launch it

and I get  500: shell_exec() has been disabled for security reasons

**Comment by FlareHAX0R** [comment]
Help me plz.

**Comment by GenPage** [comment]
What is your solder version?

**Comment by FlareHAX0R** [comment]
0.7.0.9

Also, after changing isExecEnabled to always return false


In UpdateChecker,
return str_replace(array("\r", "\n"), "", shell_exec('git rev-parse --abbrev-ref HEAD')); (line 27?)
errors with an ErrorException. It does NOT have a shell_exec checker.

**Comment by kaidenyo** [comment]
Can you connect via ssh console to the webhost ? If not that might be the problem. Most freehosters do support ssh connections

**Comment by FlareHAX0R** [comment]
GenPage helped me with this and I got it to work. And @kaidenyo SSH is not REQUIRED.
