### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by vlee489** [TechnicPack/TechnicSolder#311]
I keep getting a error 404 when I setup the server and go on to it, and there is no errors in the log.

the address is "http://178.62.94.84/TechnicSolder/public/index.php/dashboard"

(The address is down as i pay for every hour of up time)

**Comment by TheDoctorsLife** [comment]
chmod -R 775 <locationtoyoursolderlocaction>

**Comment by vlee489** [comment]
didn't help

    -rw-r--r-- 1 root root      537 Mar  4  2014 50x.html
    -rw-r--r-- 1 root root      612 Mar  4  2014 index.html
    drwxrwsr-x 7 root www-data 4096 Feb 19 12:24 TechnicSolder
    -rw-r--r-- 1 root root       21 Feb 18 13:30 vlee.php

**Comment by TheDoctorsLife** [comment]
chown -R root:www-data (solderinstallation)

**Comment by vlee489** [comment]
now it's giving me a 403 error

**Comment by TheDoctorsLife** [comment]
can you post your nginx config?

**Comment by vlee489** [comment]
its at http://vlee.me/other/nginx.txt as i can't be bothered adding 4 space at the front of each time for markdown

**Comment by GenPage** [comment]
Because your nginx config is wrong. (e.g. `try_files $uri =404;` in both your root and php locations)

Refer to these examples for help: http://docs.solder.io/v0.7/docs/example-web-server-configs

**Comment by vlee489** [comment]
thanks got it to work.
