### ISSUE TITLE
Solder pack is not downloaded

### ISSUE THREAD

**Issue by BlackwingDave** [TechnicPack/TechnicSolder#313]
hi i have just installed Solder me on my webspce and linked . But now when I want to download my pack , does not appear in the launcher that is activated Solder but on the site it will. If I want to click on the download launcher download a zip that does not exist rather than what I set in Solder have .

Here is the link to my pack and the error displayed by the console.

http://technicpack.net/modpack/forgetestrising2.596857

http://pastebin.com/78iDnc6K

**Comment by TheDoctorsLife** [comment]
your solder link is invalid. http://37.120.162.176/technicsolder/public/api/modpack/forgetestrising2

**Comment by BlackwingDave** [comment]
I have the solder installation also deleted with me. The whole thing is a bit too complicated for me .
