### ISSUE TITLE
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicSolder#314]
When I try to edit a modpack, I get this:

curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

I get that on UrlUtils, line 68.

I get that when I try to change a modpack's settings. Idk about builds.

**Comment by FlareHAX0R** [comment]
Builds return the SAME errors.

**Comment by FlareHAX0R** [comment]
some1 help plz

**Comment by TheDoctorsLife** [comment]
Report it on the irc channel.

**Comment by FlareHAX0R** [comment]
@TheDoctorsLife I am, but GenPage is not on right now.

**Comment by sct** [comment]
The error is pretty self explanatory. You have open_basedir set in php.ini and curl doesnt like that.

**Comment by FlareHAX0R** [comment]
Wait.... phpInfo says open_baseDir has no value!

**Comment by sct** [comment]
Do you have safe_mode set in php.ini?

**Comment by FlareHAX0R** [comment]
This is shared hosting. They said they use open basedir as a security feature. BUT, I've seen code online that is used to use followlocation whatever when open basedir is enabled.

**Comment by FlareHAX0R** [comment]
WOW
Just discovered the conflict is from a bug from a FREAKING DECADE ago.

**Comment by zombold** [comment]
I need Help too. I can't create some Builds.
I became the same Error.

**Comment by FlareHAX0R** [comment]
Could someone make an external webapp for creating builds/editing modpacks?

**Comment by TheDoctorsLife** [comment]
http://forums.technicpack.net/topic/81569-solder-helper-a-modpack-packer-now-updating-solder/

**Comment by Pyker** [comment]
Closing this since it's not a Solder bug.
