### ISSUE TITLE
SVN?

### ISSUE THREAD

**Issue by Flukethoughts** [TechnicPack/TechnicSolder#316]
Why doesn't technic soldier preform like a svn directory that would take out so much hassle.

**Comment by TheDoctorsLife** [comment]
Define SVN

**Comment by sct** [comment]
SVN what is this 2005?

**Comment by TheDoctorsLife** [comment]
Sure seems like it

**Comment by GenPage** [comment]
We will be re-designing how Solder handles mods in 0.8
