### ISSUE TITLE
Error When Adding Pack

### ISSUE THREAD

**Issue by CloudTheWolf** [TechnicPack/TechnicSolder#317]
Ok so I have setup Solder following the guide step by step but when I go to add my pack to my launcher:

[B#282] net.technicpack.rest.RestfulAPIException: Error parsing response JSON at URL [http://networkstudios.tv/solder/public/index.php/api/modpack/]
[B#282] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:155)
[B#282] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#282] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#282] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#282] 	at java.lang.Thread.run(Unknown Source)
[B#282] Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[B#282] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:803)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:768)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:717)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:689)
[B#282] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:139)
[B#282] 	... 7 more
[B#282] Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[B#282] 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[B#282] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
[B#282] 	... 12 more
[B#282] net.technicpack.rest.RestfulAPIException: Error parsing response JSON at URL [http://networkstudios.tv/solder/public/index.php/api/modpack/]
[B#282] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:155)
[B#282] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#282] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#282] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#282] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#282] 	at java.lang.Thread.run(Unknown Source)
[B#282] Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[B#282] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:803)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:768)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:717)
[B#282] 	at com.google.gson.Gson.fromJson(Gson.java:689)
[B#282] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:139)
[B#282] 	... 7 more
[B#282] Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[B#282] 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[B#282] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
[B#282] 	... 12 more

I have edited app/config/solder.php and set the Repo and Mirror location to http://cloudpackfreedom.s3-website-eu-west-1.amazonaws.com/

Have I missed something?

**Comment by TheDoctorsLife** [comment]
http://networkstudios.tv/solder/public/index.php/api/modpack/ takes me to https://networkstudios.tv/index.php/api/modpack with a 404 error.

**Comment by CloudTheWolf** [comment]
Managed to fix it now by commenting out this line from .htaccess
RewriteRule ^(.*)/$ /$1 [L,R=301]
