### ISSUE TITLE
Error: undefined when adding Mod Version

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TechnicPack/TechnicSolder#319]
im getting the error Error: undefined when adding mod version, it worked for the first mod I added, but the second mod its giving the error, I gave all perms for files, so im not sure what the issue is

**Comment by xH3LLRAIZ3Rx** [comment]
and it seems like it only happens to the mod with the sling aether-2, so far anyways

**Comment by xH3LLRAIZ3Rx** [comment]
ok so it seems like it only happens to Aether 2, all the other mods work

**Comment by TheDoctorsLife** [comment]
Use a different slug.

**Comment by xH3LLRAIZ3Rx** [comment]
I tried that, I did the-aeither, aeither-2, aether, still have the issue with that mod

**Comment by TheDoctorsLife** [comment]
Increase the mod hash time.

**Comment by Razorskills** [comment]
It is a large mod you might have a php file limit that isn't large enough to get a md5 for that. I believe php has a config somewhere that you can increase the limit.

**Comment by GenPage** [comment]
Check your log files. They are located in `app/storage/logs`

**Comment by xH3LLRAIZ3Rx** [comment]
ahh it was the Memory Size

**Comment by xH3LLRAIZ3Rx** [comment]
now I have this issue: http://api.technicpack.net/modpack/wg-atlas where it says 401 Error Unauthorized Access

**Comment by TheDoctorsLife** [comment]
http://solder.windmillgaming.net/public/index.php/api/modpack/wg-atlas gives me a nice kitten 404 page. and you can no longer access api urls without a build #. try a tool like http://www.circlecraft.info/platform/index.php to check what is set in your api url.

**Comment by xH3LLRAIZ3Rx** [comment]
thats because I just put my Website on there, gotta make a Virtual Site for Technic

**Comment by xH3LLRAIZ3Rx** [comment]
for now im gonna assume its fixed, not sure, didn't test, will reopen if the issue happens again
