### ISSUE TITLE
Unable to change mod versions in build

### ISSUE THREAD

**Issue by Tankernn** [TechnicPack/TechnicSolder#320]
Suddenly I just can't change mod versions in my builds. Sometimes a yellow box shows up and says "Unable to change modversion", sometimes nothing happens at all when the "change" button is clicked.
I don't know if I'm the one doing something wrong or if this is a bug, how can I troubleshoot it?

**Comment by TheDoctorsLife** [comment]
Can you change the modpack version in mysql?

**Comment by Tankernn** [comment]
Yes, that worked, and I was able to download the correct version with the launcher after changing it in MySQL.

**Comment by Tankernn** [comment]
I'm so sorry, I have wasted your time. When I click "change" the first time it works, but there is no message saying that it has worked. So I click again, but because it has already been changed it can't be changed again: "Unable to change modversion". My suggestion is that there should be a "Success"-message when the change works. Sorry.

**Comment by GenPage** [comment]
Hey there,

There was a success version but people were getting annoyed with the spam. 

What I'll do is modify the "Unable to change modversion" message to better clarify that the version has already been changed

**Comment by Tankernn** [comment]
OK, thanks!
