### ISSUE TITLE
Error Accessing Modpacks

### ISSUE THREAD

**Issue by RocketwareGames** [TechnicPack/TechnicSolder#321]
![whoops there was an error - mozilla firefox_001](https://cloud.githubusercontent.com/assets/11239627/6424699/b900b420-bed1-11e4-93ba-590f855fcb15.png)
So i have solder set up correctly, i can add mods, the versions work, but when ever i try to add the modpack to the platform, it says we've hit a snag. if i remove the modpack from solder, it works perfectly fine. i also get that error in the picture when trying to delete a build.

**Comment by GenPage** [comment]
If you already deleted the modpack, the build gets deleted as well.
