### ISSUE TITLE
Change the required version of PHP

### ISSUE THREAD

**Issue by GibbsFrance** [TechnicPack/TechnicSolder#322]
Hi,

After the upgrade to 0.7.1 of Solder, I wanted to edit a modpack and I got a 500 error with the following description : `Call to undefined function boolval()`.

After verifying the PHP documentation it would appear that this function is available since PHP 5.5, so the minimum version required by Solder is out of date.

Have a nice day.

**Comment by LightningMan01** [comment]
it should also be noted that using apt-get to install anything php related pulls 5.4 for the most requiring source installs as that has been a major hang up for me on my rasbian os (debian wheezy)
