### ISSUE TITLE
no "f88ef0b32d48780d573641400fa5c815" file in the github api cache folder

### ISSUE THREAD

**Issue by LightningMan01** [TechnicPack/TechnicSolder#324]
Thus one cannot simply access there dashboard nor the update checker making the big point of the entire update (from the way your worded your update post) rather fruitless since it revolved around the better update checking, no? also I saw that someone put something like this up an hour or two before, but for whatever reason the OP immediately closed it. So consider this the post that clarify's his post.

**Comment by vlee489** [comment]
Check your permissions

**Comment by vlee489** [comment]
if you getting

    500  Cannot put content in file "/usr/share/nginx/html/TechnicSolder/app/storage/github-api-cache/f88ef0b32d48780d573641400fa5c815"

its a permissions problem most likely.

**Comment by LightningMan01** [comment]
nope like the other guy checked and everything; the file simply doesn't exist anywhere including the source

**Comment by vlee489** [comment]
well do a 

   chown -R root:www-data (solderinstallation)

**Comment by GenPage** [comment]
Permissions need to be set for the folder since its new. `GitHub-api-cache`

**Comment by LightningMan01** [comment]
did so, actively did nothing so I restarted it and still nothing. I'm running an debian os so I did the whole chmod 777 and still got nothing, Since I didn't redo any permissions or anything, the storage folder should of had sufficient read-write as it was but obviously in the case if it didn't it should have already solved it.
