### ISSUE TITLE
Updating problem 

### ISSUE THREAD

**Issue by vlee489** [TechnicPack/TechnicSolder#325]
when i do "git pull" this happens 

    root@Solder:/usr/share/nginx/html/TechnicSolder# git pull
    remote: Counting objects: 45, done.
    remote: Compressing objects: 100% (44/44), done.
    remote: Total 45 (delta 10), reused 0 (delta 0), pack-reused 0
    Unpacking objects: 100% (45/45), done.
    From https://github.com/TechnicPack/TechnicSolder
       203399e..41d8fa3  master     -> origin/master
       a789521..512b0fe  dev        -> origin/dev
       7a7d6ca..44d993b  legacy/master -> origin/legacy/master
     * [new tag]         v0.7.1.0   -> v0.7.1.0
    Updating 203399e..41d8fa3
    error: Your local changes to the following files would be overwritten by merge:
            .gitattributes
            .gitignore
            .travis.yml
            CONTRIBUTING.md
            README.md
            app/config-sample/solder.php
            app/controllers/ApiController.php
            app/controllers/BaseController.php
            app/controllers/ClientController.php
            app/controllers/DashboardController.php
            app/controllers/KeyController.php
            app/controllers/ModController.php
            app/controllers/ModpackController.php
            app/controllers/SolderController.php
            app/controllers/UserController.php
            app/database-sample/production.sqlite
            app/database/migrations/2014_10_26_172144_new_permission_system.php
            app/database/migrations/2014_12_12_235012_update_users_table_security.ph                                                                                     p
            app/filters.php
            app/libraries/UpdateUtils.php
            app/models/Client.php
            app/models/Modpack.php
            app/models/Modversion.php
            app/start/global.php
            app/tests/ExampleTest.php
            app/views/client/create.blade.php
            app/views/client/list.blade.php
            app/views/dashboard/index.blade.php
            app/views/key/create.blade.php
            app/views/key/list.blade.php
            app/views/layouts/master.blade.php
            app/views/mod/list.blade.php
            app/views/mod/versions.blade.php
            app/views/modpack/create.blade.php
            app/views/modpack/edit.blade.php
            app/views/modpack/list.blade.php
            app/views/modpack/view.blade.php
            app/views/solder/configure.blade.php
            app/views/solder/update.blade.php
            composer.json
            public/css/solder.css
            public/resources/default/background.png
    Please, commit your changes or stash them before you can merge.
    Aborting

Then I try "git reset --hard" and continue with update and then I am greeted with 

     Look's like we've hit a snag!

     Something went terribly wrong when we were fetching the page you requested. Please try your request again in a few minutes or follow the help link to find your issue.

     500  Cannot put content in file "/usr/share/nginx/html/TechnicSolder/app/storage/github-api-cache/f88ef0b32d48780d573641400fa5c815"

**Comment by GenPage** [comment]
A "hard" resets permissions as well. Make sure your "app/storage" folder had write access to it and it's sub folders

**Comment by vlee489** [comment]
Oh! (I hope i can remember how to set Perms)

**Comment by GenPage** [comment]
Hint: `chmod` and `chown` are your friends :)

**Comment by vlee489** [comment]
got a 
    Error in exception handler.

**Comment by GenPage** [comment]
Set `debug` to true in your app config for more info.

**Comment by vlee489** [comment]
ok then

**Comment by vlee489** [comment]
got 

    Error in exception handler: The stream or file "/usr/share/nginx/html/TechnicSolder/app/storage/logs/solderlog-2015-02-28.txt" could not be opened: failed to open stream: Permission denied in /usr/share/nginx/html/TechnicSolder/bootstrap/compiled.php:9094

**Comment by vlee489** [comment]
my permissions are 

    drwxrwsr-x 15 root www-data   4096 Feb 28 13:22 app
    -rw-r--r--  1 root www-data   2452 Feb 28 13:22 artisan
    drwxrwsr-x  2 root www-data   4096 Feb 28 13:55 bootstrap
    -rw-r--r--  1 root www-data   2036 Feb 28 13:22 composer.json
    -rwxrwxr-x  1 root www-data 103329 Feb 28 13:23 composer.lock
    -rw-r--r--  1 root www-data   1470 Feb 28 13:22 CONTRIBUTING.md
    -rw-r--r--  1 root www-data   2230 Feb 28 13:22 LICENSE
    -rw-r--r--  1 root www-data    997 Feb 28 13:22 phpunit.php
    -rw-r--r--  1 root www-data    567 Feb 28 13:22 phpunit.xml
    drwxrwsr-x  9 root www-data   4096 Feb 28 13:22 public
    -rw-r--r--  1 root www-data   2434 Feb 28 13:22 README.md
    -rw-r--r--  1 root www-data    519 Feb 28 13:22 server.php
    drwxrwsr-x 31 root www-data   4096 Feb 28 13:55 vendor

**Comment by GenPage** [comment]
Check "app/storage/logs"

**Comment by vlee489** [comment]
log got 28th at http://vlee.me/other/solder/logs/solderlog-2015-02-28.txt

**Comment by GenPage** [comment]
It's not an issue with the actual log file. It's the permissions of the logs folder or log files in it

**Comment by vlee489** [comment]
is it the ones in /var/log/nginx/

**Comment by vlee489** [comment]
as it doesn't look like it

is it the ones at 

/usr/share/nginx/html/TechnicSolder/vendor/monolog/monolog/src/Monolog/Handler

**Comment by vlee489** [comment]
Solved it.

    chmod -R 775 (TechnicSolderDirectory)

**Comment by sct** [comment]
That is a terrible thing to do and I don't recommend it to anyone.

Never chmod your entire directory, only the storage directory.

**Comment by vlee489** [comment]
That's true. Do not chmod the whole directory. But I had enough for one day.
