### ISSUE TITLE
Error in ModpackController.php

### ISSUE THREAD

**Issue by NeturonicAngelz** [TechnicPack/TechnicSolder#329]
Not sure what is wrong here, this is what I've done to install the Solder, and everytime I install it it gives me this particular error, not sure if its something that is issuing in the newest build or what. Though its causing issues for me.

How I installed my Solder:
- git clone https://github.com/TechnicPack/TechnicSolder.git
- get composer (localy)
- Update composer (locally)
- php composer.phar install --no-dev --no-interaction
- restart apache
- Login to the admin panel
- update API keys and such
- ensure that the app/config/solder.php is up to date.

Error:
![ss 2015-03-01 at 03 44 26](https://cloud.githubusercontent.com/assets/5571347/6430083/0298d71e-bfc9-11e4-9005-4bdfc892680a.png)

**Comment by GibbsFrance** [comment]
Hi,

You probably have PHP 5.4 on your server, however, this function is only available since PHP 5.5 (see issue #322).

Have a nice day.

**Comment by NeturonicAngelz** [comment]
GibbsFrance I actually have PHP 5.5 on my server.

**Comment by GibbsFrance** [comment]
You do not have several versions of PHP that could run? Can you check by creating a file that displays the PHP settings? (See http://php.net/manual/en/function.phpinfo.php)
