### ISSUE TITLE
Updating Modpack Client Access fail

### ISSUE THREAD

**Issue by M1r077** [TechnicPack/TechnicSolder#333]
While trying to "Save" changes under "Client Access" in the following page :
> /solder/public/index.php/modpack/edit/4

I get this error :
> Call to undefined function boolval()

The work around I found is to inject manually an entry in the database :
```SQL
INSERT INTO  `solder`.`client_modpack` (
`id` ,
`client_id` ,
`modpack_id` ,
`created_at` ,
`updated_at`
)
VALUES (
NULL ,  '9',  '4',  '0000-00-00 00:00:00',  '0000-00-00 00:00:00'
);
```

**Comment by sct** [comment]
This is fixed in 0.7.1.1. Update solder.
