### ISSUE TITLE
Request to create a .NET version

### ISSUE THREAD

**Issue by oliverkane** [TechnicPack/TechnicSolder#337]
Everyone, +1 me in the comments if you'd like to see a ASP.NET fork to host as well!  Not all of us can use Linux or have a host around.

TechnicPack guys,
Love your work!  I've been using Solder to power my Sevenless 2 pack on your platform for quite some time now.

My linux skills are not so good and I'd rather not rent or spin up a VM just to host this thing though. I'm a fairly skilled ASP.NET developer who'd like to re-create a version of Solder's API and interface in some ASP.NET MVC. I understand the hashing, storage of files and database stuff well enough, but don't has a grasp on how your custom web server responds to your platform.

Could you provide your expected API so that I can re-create it in .NET?  I'd be happy to maintain it and add to your eco-system.  I think many others would apperciate it as well.  

I'd basically be looking for a list of things like (where ~ is the site root, for me it's http://ec2-52-10-63-41.us-west-2.compute.amazonaws.com/)

# API REST Format

## Installed Version Number
Returns a json body describing the installed application.  Sample response:

    [GET] 
    ~/api
    {
       api: "TechnicSolder",
       version: "v0.7.0.9",
       stream: "DEV-ASPNET"
    }

Returns a json body describing the installed application.  Sample response: 

## Get the listed modpacks
    [GET]
    ~/api/modpack/?cid={CLIENTID}
        
      {
                    modpacks: {
                       sevenless-2: "Sevenless-2"
                },
        mirror_url: "http://ec2-52-10-63-41.us-west-2.compute.amazonaws.com/modpack/"
        }

**Comment by oliverkane** [comment]
How do you get your client ID?

**Comment by oliverkane** [comment]
## Get Specific modpack details. Returns JSON of the packs there

    ~/api/modpack/?cid={CID}


    {
        modpacks: {
            sevenless-2: "Sevenless-2"
        },
        mirror_url: "http://ec2-52-10-63-41.us-west-2.compute.amazonaws.com/modpack/"
}

**Comment by Pyker** [comment]
The code is all there. Just port it to .NET. If you don't understand it then tough luck, cuz I don't think anyone sane would want to port something written in PHP, which is pretty much universal, to ASP.NET, which is mainly for Windows servers.

FYI, PHP runs on Linux, Windows and Mac (and probably others).

**Comment by oliverkane** [comment]
@Pyker , can you at least tell me how to get the "client ID" or whatever "cid" references?  I've been looking at wireshark traffic and I don't ever see that sent to the client to store.  But I do see it show up for specific requests.

**Comment by GibbsFrance** [comment]
Client ID is an UUID of one installation of Launcher. It is to restrict view of modpacks or builds.

**Comment by oliverkane** [comment]
@GibbsFrance , thanks. I'm glad to see someone actually being helpful rather than basically saying "well our stack is pretty good so go figure it out yourself".

@Pyker The current version of the product does amazing things, but I found the install process tedious and prone to error.  The WIKI explaining instalation, and upgrade are in shambles and I'm basically trying to provide the community a bit more "turn-key".  I'm sorry that you are not more willing to help.

**Comment by oliverkane** [comment]
Actually, I'll delete this whole thread. I just discovered taht the wiki was migrated to solder.io, which has just what I'm looking for. :D  Thanks again all!

**Comment by Pyker** [comment]
> I'd rather have people be able to just double click an EXE

To quote the big, red warning in the documentation: "This application is intended for experienced system administrators (...)"
