### ISSUE TITLE
Direct Download Possibility for mods

### ISSUE THREAD

**Issue by Tomson124** [TechnicPack/TechnicSolder#339]
I hope it is no double post... If it is just close it ;-)
But it would be really cool if there would be the possibility to say Solder it has to download a mod from the mod authors downloadlink. Then the TechnicLauncher useres would get the permissions for mods like JourneyMap.
But keep up the good work, Solder is such an easy way to build and maintain packs ;-)

Tomson

**Comment by TheDoctorsLife** [comment]
There is already an issue on this https://github.com/TechnicPack/TechnicSolder/issues/206

**Comment by Tomson124** [comment]
okay thanks for telling me @TheDoctorsLife

**Comment by TheDoctorsLife** [comment]
np
