### ISSUE TITLE
Add Config Feature

### ISSUE THREAD

**Issue by RetroCraft** [TechnicPack/TechnicSolder#342]
Can you guys add a feature to add .cfg files to modpacks? Some mods I use (like HQM or Better Title Screen) require the .json or .cfg files in the /config/ directory. Currently there is no way to do this.

Example (in repository):
* /config/
    * mod-name.cfg

Or something like that.

**Comment by Loscillo** [comment]
You can add any file you want in mods, with any structure (/mods,
/config,...). Zip file is extracted at root of the modpack,so if you call
call a folder config, it is extracted at /modpack-slug/config
