### ISSUE TITLE
[BUG] Private or Hidden Modpaks are always shown

### ISSUE THREAD

**Issue by hitech95** [TechnicPack/TechnicSolder#343]
A small oversight, it is possible that one of the API key is "string (0)"
In this case the control:
```
    if ($key->api_key == Input::get('key')) {
        $this->key = $key;
    }
```
returns "TRUE"

I have found this bug on APIController, may be extended.
It would have to verify that the `Input::get ('key')` is not empty.

**Comment by GenPage** [comment]
That is true, but would also require a blank API to be set by the user in Solder.

**Comment by hitech95** [comment]
Yes, but old install have the "Default" key empty.
For example I have my own launcher and I don't need the Platform.

**Comment by GenPage** [comment]
Ah, I didn't realize old installs had an empty key.

**Comment by hitech95** [comment]
No problem :D

**Comment by GenPage** [comment]
Thank you for your fix!

**Comment by hitech95** [comment]
Proud to have helped!
