### ISSUE TITLE
Fresh Solder Install - Isn't working at all.

### ISSUE THREAD

**Issue by PocoCraft** [TechnicPack/TechnicSolder#345]
Okay, I am using http://docs.solder.io/ as a tutorial on how to install Solder, although I am completely unable to get it even remotely working. My Solder's root www-dir is /var/www/technic-solder/ . Although when I finished installing it according to the tutorial I get redirected to http://technicsolder.<mydomain>.org/dashboard/ Which in turn returns a 404 error! The Apache2 virtualhost is pointing technicsolder.<my domain>.org to /var/www/technic-solder/ So, if anyone can provide maybe a modified tutorial because I can't have Solder in the root directory of my web server, since every service is on another virtualhost for seperation, if that's the problem after all..

Thanks in advanced!

**Comment by GenPage** [comment]
The example web configs on docs.solder.io state that the root directory for the Solder application is the public folder contained within it,

**Comment by PocoCraft** [comment]
I understand, I've tried to edit them to use for my setup, although I am still getting errors. If I attempt to login with the default username and password at http://technicsolder.pococraft.org/index.php/login I get : Error in exception handler.

**Comment by PocoCraft** [comment]
Email: admin@admin.com Password: admin Is what the tutorial said are the default credentials, which I haven't changed.

**Comment by Loscillo** [comment]
Hi,

You have a permission problem. Check user and group owner of your installation (in Unix with ls -l). If you use Apache, files must belong to the www-data group and must have write access

**Comment by PocoCraft** [comment]
Oh, let me change the directory's group access real quick then. I will get back with a reply ASAP. Thanks for your help, even if this isn't the only problem!

**Comment by PocoCraft** [comment]
Okay, progress! Now when I login into http://technicsolder.pococraft.org/index.php/login I get: Look's like we've hit a snag!

Something went terribly wrong when we were fetching the page you requested. Please try your request again in a few minutes or follow the help link to find your issue.

 Take me back to where I was!  I need help!

 500  could not find driver

**Comment by PocoCraft** [comment]
Do I make the owner www-data as well? And not just the group www-data?

**Comment by GenPage** [comment]
No, the issue now is that you are missing a required driver, most likely PhP-sqlite or PhP-mysql

**Comment by PocoCraft** [comment]
Oh, well I was never prompted to install the package: php5-sqlite. It seems to work now! Thanks a lot! If there's a seperate, unrelated issue I will reopen another thread on GitHub. Thanks for everyone's help. :D

**Comment by GenPage** [comment]
You are very welcome
