### ISSUE TITLE
Mods are unzipped to named folders at root

### ISSUE THREAD

**Issue by Rhodizzle** [TechnicPack/TechnicSolder#350]
Hey guys,

First of all, thanks for all of your hard work on this. Over the last three days I've come to appreciate the complexity of the project. So far I've gotten the code up and running on a GoDaddy shared hosting account, added several mods, gotten everything linked to my Technic account. While I've had to do a lot of trial and error, it works! I can find my modpack in the Technic Launcher and download all of the mods that I have assigned to the pack.

This is where my problem arises. I have the .zip files structured as if each one is the root of the minecraft install, containing a folder (mods, bin, resourcepack, whatever) followed by the appropriate .jar or whatever it is that I'm trying to load, yet when I install the pack, it has unzipped each mod into a folder with the same name as the zip at the root of the minecraft folder. Based on my zip structure, this is not the behavior that I was expecting. I could make one monolithic "mods" mod and put everything in there I suppose, but that defeats the beauty of solder only having to download those items that have changed.

Any ideas as to what is going wrong?

Zip Structure:
soandsomod-version.zip
-----mods
----------soandsomod-version.jar

Installed structure:
modpack root
-----soandsomod-version
----------mods
---------------soandsomod-version.jar

Expected Installed Structure:
modpack root
-----mods
----------soandsomod-version.jar

**Comment by disconsented** [comment]
Could you link your .zips for us?

**Comment by Rhodizzle** [comment]
Thanks for the reply disconsented. Try this one:
http://solder.almostvanilla.org/mods/ars-magica-2/ars-magica-2-1.4.0.008.zip

**Comment by disconsented** [comment]
You structured them wrong. You have them as /modslug/mods/mod.jar instead of /mods/mod.jar . You also have a bunch of random mac files which you don't need to distribute

**Comment by Rhodizzle** [comment]
Friggin OS X.

Hey man, I really appreciate it. Sorry to have wasted your time on that one...

**Comment by disconsented** [comment]
No worries people make mistakes
