### ISSUE TITLE
SQLSTATE[42S02]

### ISSUE THREAD

**Issue by fabm3n** [TechnicPack/TechnicSolder#352]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'solder.users' doesn't exist (SQL: select * from `users` where `email` = admin@admin.com limit 1) thats my error

**Comment by fabm3n** [comment]
Ok its fixed

**Comment by Avalanche7CZ** [comment]
how?

**Comment by Pyker** [comment]
> how?

@Avalanche7CZ Run the migrations: <https://docs.solder.io/reference/getting-started#database-configuration>
