### ISSUE TITLE
In HHVM the User Management settings fail to display.

### ISSUE THREAD

**Issue by NineCat** [TechnicPack/TechnicSolder#355]
User Management settings will not display in HHVM, however it also wont throw an error or exception leaving only a blank screen. Nothing in HHVM logs or Solder logs and not possible to edit details. Web Server returns 200 OK.

**Comment by JzJad** [comment]
Sounds like an HHVM problem honestly. Could be one of the many incompatibilities it has, Try posting it on their Git

**Comment by GenPage** [comment]
Should be fixed in 0ca3074dcac22abda008477cd8864fcedd9d4da2

There was an extra `@endsection` in the code
