### ISSUE TITLE
Technic solder not unpacking correctly

### ISSUE THREAD

**Issue by Flukethoughts** [TechnicPack/TechnicSolder#361]
Sorry if this is a duplicate be and my partner have been having an issue where technic solder doesn't download the mod correctly to the mod pack. Instead of being the original size of 10megs it ends up being 1,5. This is mainly happening with the mod PneumaticCraft-1.7.10-1.6.5-67-universal.jar

**Comment by spannerman79** [comment]
Then your zip file is incorrect
Take note of http://docs.solder.io/v0.7/docs/zip-file-structure

Your not transferring the complete zip to the required location for your repo
When I compress and have the required file structure within the needed zip this is what I have to upload http://imgur.com/9Ktw5EH

**Comment by GenPage** [comment]
This was fixed during your time on our IRC I believe, please update the issue.
