### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by Doridian** [TechnicPack/TechnicSolder#374]
Whenever I try to delete a user, I get an error page stating:
`Call to undefined method Illuminate\Database\Query\Builder::sync()`

I am currently using the latest version of the master branch.

**Comment by fcpwiz** [comment]
Umm try: `composer update --no-dev --no-interaction`

**Comment by Doridian** [comment]
Did not find any update and did not fix the problem, sadly :(

**Comment by Tomson124** [comment]
Did you try `php artisan migrate` ?

**Comment by Doridian** [comment]
Yields `Nothing to migrate`

**Comment by GenPage** [comment]
This is a confirmed bug. I will push a hotfix shortly
