### ISSUE TITLE
Wrong version downloading?

### ISSUE THREAD

**Issue by Master-Guy** [TechnicPack/TechnicSolder#375]
I've followed the manuals at http://docs.solder.io/ to set up my server and create my first modpack to test. After adding the mods to the modpack, and setting the build to "recommended" and "latest" I've added the modpack to the platform and copied the installation URL to my launcher.

http://www.technicpack.net/modpack/mdtest.634839
http://masterductions.com/TechnicSolder/public/api/modpack/mdtest/1

When trying to install the modpack, it gives the following error:
"Attempting to extract file mdtest-1.0.zip, but it did not exist."

I've not added any mod named mdtest with version 1.0 to my modpack, and it doesn't show up either.
The launcher logs show the following:

[B#283] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://masterductions.com/TechnicSolder/public/api/modpack/]
[B#283] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:157)
[B#283] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#283] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#283] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#283] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#283] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#283] 	at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
[B#283] 	at java.lang.Thread.run(Unknown Source)
[B#283] Caused by: java.io.FileNotFoundException: http://masterductions.com/api/modpack
[B#283] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#283] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#283] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:137)
[B#283] 	... 7 more

Can anyone tell me what I'm doing wrong?
Thanks ahead,
MG

PS: Yes, I know the parent directory is accessable, but it's a test/dev environment.

**Comment by spannerman79** [comment]
What is your exact api url?
If you just point a browser at the api url you get a string of data.

With yours I've tried;
http://masterductions.com/api/modpack
http://masterductions.com/api/
http://masterductions.com/TechnicSolder/public/api/ which redirects to http://masterductions.com/api

All are invalid (404's) - so your Solder install is faulty

**Comment by Master-Guy** [comment]
So that would be this one?
http://masterductions.com/TechnicSolder/public/api/modpack/mdtest/1

Nowhere in my configurations (both on my PC and on the platform) can I find a link to masterductions.com/api
The installation is done in masterductions.com/TechnicSolder/public/

**Comment by Pyker** [comment]
This isn't a bug. Read through the documentation and install Solder correctly.

**Comment by FlareHAX0R** [comment]
Make a subdomain that points to your public folder.
