### ISSUE TITLE
SQLSTATE - Field does not have default value

### ISSUE THREAD

**Issue by ET-Bent** [TechnicPack/TechnicSolder#377]
We are still using the 0.6-DEV version of solder because there was a version that has mod uploads integrated. Everything woked well until today. We are getting the following error upon creating a new build for a modpack:

```
Unhandled Exception

Message:

SQLSTATE[HY000]: General error: 1364 Field 'private' doesn't have a default value

SQL: INSERT INTO `builds` (`modpack_id`, `version`, `minecraft`, `minecraft_md5`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?, ?, ?)

Bindings: array (
  0 => '6',
  1 => '1.0.0.5',
  2 => '1.7.10',
  3 => '',
  4 => '2015-04-15 17:58:57',
  5 => '2015-04-15 17:58:57',
)
Location:

/var/www/[SOME-URL]/laravel/database/connection.php on line 263
Stack Trace:

#0 /var/www/[SOME-URL]/laravel/database/connection.php(183): Laravel\Database\Connection->execute('INSERT INTO `bu...', Array)
#1 /var/www/[SOME-URL]/laravel/database/query.php(823): Laravel\Database\Connection->query('INSERT INTO `bu...', Array)
#2 [internal function]: Laravel\Database\Query->insert_get_id(Array, 'id')
#3 /var/www/[SOME-URL]/laravel/database/eloquent/query.php(283): call_user_func_array(Array, Array)
#4 /var/www/[SOME-URL]/laravel/database/eloquent/model.php(390): Laravel\Database\Eloquent\Query->__call('insert_get_id', Array)
#5 /var/www/[SOME-URL]/laravel/database/eloquent/model.php(390): Laravel\Database\Eloquent\Query->insert_get_id(Array, 'id')
#6 /var/www/[SOME-URL]/application/controllers/modpack.php(128): Laravel\Database\Eloquent\Model->save()
#7 [internal function]: Modpack_Controller->action_do_addbuild('6')
#8 /var/www/[SOME-URL]/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#9 /var/www/[SOME-URL]/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('do_addbuild', Array)
#10 /var/www/[SOME-URL]/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('do_addbuild', Array)
#11 /var/www/[SOME-URL]/laravel/routing/route.php(153): Laravel\Routing\Controller::call('modpack@do_addb...', Array)
#12 /var/www/[SOME-URL]/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#13 /var/www/[SOME-URL]/laravel/laravel.php(167): Laravel\Routing\Route->call()
#14 /var/www/[SOME-URL]/public/index.php(34): require('/var/www/solder...')
#15 {main}
```

What default value does the private field have?

**Comment by GenPage** [comment]
See the migrations folder:

https://github.com/TechnicPack/TechnicSolder/blob/master/app/database/migrations/2013_03_13_200706_update_builds_md5.php#L17

**Comment by ET-Bent** [comment]
Thanks, I looked up the file and added the ```->default('');``` to it. But this did not change anything. What bothers me is why did this error even happen, because we have changed nothing on our setup.

**Comment by GenPage** [comment]
Yes, you would have to.

Are you using sqlite or MySQL?

**Comment by ET-Bent** [comment]
We use MySQL. How do I force the migration process? I did it with the composer command and used ```--force``` but it said there ist nothing to migrate.

**Comment by GenPage** [comment]
If your still on 0.6-DEV there will be nothing. You'll need to do a `migrate:refresh` to re-run the migrations which will erase your data. 

My suggestion is to turn off MySQL's strict mode as a workaround

Open the "my.ini" file within the MySQL installation directory and look for something like...
# Set the SQL mode to strict
sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict

**Comment by ET-Bent** [comment]
I looked up the ```my.ini``` file (on linux at /etc/mysql/my.cnf) and there was no strict mode set so I disabled it anyway with the help of this tutorial:

https://support.realtyna.com/index.php?/Knowledgebase/Article/View/535/0/how-can-i-turn-off-mysql-strict-mode

also after running the suggested ```SET @@global.sql_mode= '';``` didn't help either. I am getting the same error when creating a new build. This error seems really strange, couldn't I just fill in a value ? But then what is the right value? As far as I can see it's a md5 has but I don't know where to get this from.

Thanks for you help though!

**Comment by ET-Bent** [comment]
Okay I solved the problem. The problem was that there are two config files for the mysql-server and each one overrides the other one.

```locate my.cnf```

$ /etc/mysql/my.cnf
$ /usr/my.cnf

So basically after adding the line:

```sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" ```

to both files and restarting the mysql-server everything is working fine again.

Thanks Gen for your help, looking forward to the 0.8.X release with the mod upload functionality!

**Comment by GenPage** [comment]
Anytime man, glad to see you got it working!
