### ISSUE TITLE
can't add a mod

### ISSUE THREAD

**Issue by checkplysgamer** [TechnicPack/TechnicSolder#378]
On add a mod to my technic solder im getting this error: http://i.imgur.com/Di3XFf5.png
But my download link (http://txcraftnetwork.esy.es/public/mod/view/mods/build-craft/build-craft-4.2.2for1.6.4.zip) works correctly.
Please help me.
Im using 777 permission for the mod files.
Before updating technic solder this works correctly.

**Comment by spannerman79** [comment]
You shouldn't have 777 for files sitting on a web server

Change directory's to 775 and files to 644

Check your logs as it's not creating md5 checksums

**Comment by checkplysgamer** [comment]
Im change the permissions and te error is the same.

**Comment by spannerman79** [comment]
Then check the log file as I have already said it's not creating a md5 checksum when you add - hence the internal server error

**Comment by checkplysgamer** [comment]
Im not have anyone error log.

**Comment by spannerman79** [comment]
Ok...that sentence makes no sense what so ever..........

Solder is an Advanced system.
Log file location is outlined in your config

**Comment by checkplysgamer** [comment]
Im found the log now 
http://pastebin.com/82xhjt9Q

**Comment by spannerman79** [comment]
Line 893 and down
As I stated before - you don't have your Web server setup correctly as it's not creating md5 checksums 

Read up on the requirements of Solder on solder.io

**Comment by checkplysgamer** [comment]
Is need composer instaled on webserver to solder works?
Im instaled solder and setup solder on my computer after upload the files to my webserver.
My webserver have PHP 5.4+, PHP MCrypt Extension, PHP Curl Extension, PHP GD Extension and 
A sqllite, mysql, pgsql, or sqlsrv database (Im use mysql). But not have composer. 
It is needed on webserver?

**Comment by checkplysgamer** [comment]
solder as give me a curl error but I have Curl installed.

**Comment by checkplysgamer** [comment]
The erro is form  open_basedir but I can't disable it :tired_face:

**Comment by spannerman79** [comment]
Once again you haven't read the documentation.
You cannot use shared web hosting - which is clearly stated in the documentation.

@GenPage please tag this as non-solder and close

**Comment by GenPage** [comment]
@spannerman79 is correct. We do not officially support shared hosting. You can attempt it, some work, some dont. 

The issue is with some the security features of PHP (safe_mode and open_basedir). These are common on shared hosting sites.
