### ISSUE TITLE
Can't replace Pictures in Modpack

### ISSUE THREAD

**Issue by NitroxydeX** [TechnicPack/TechnicSolder#381]
Solder seems not to replace old pictures with new ones. If I want upload a new picture as modpack-background it seems to upload but the old one did not get replaced in soldier. 

Any known problems here?

**Comment by GenPage** [comment]
Can you check your 'app/storage/logs' for any errors? 

I am assuming it fails silently since you provided no error message or screenshot

**Comment by NitroxydeX** [comment]
No errorlog created for it. So it seems not to fail with a error message.

**Comment by GenPage** [comment]
Are you using Amazon S3?

**Comment by NitroxydeX** [comment]
Nope. I have an own Linux-Server.

**Comment by NitroxydeX** [comment]
Okay. It's changed now. Maybe this only appears when it's pushed to the Launcher?

**Comment by GenPage** [comment]
Yes, Modpack resources are now mainly distributed from the Platform. Solder is just a back-up source now.
