### ISSUE TITLE
Error: Could not get MD5. URL Incorrect?

### ISSUE THREAD

**Issue by tnert** [TechnicPack/TechnicSolder#382]
![screen shot 2015-04-23 at 8 44 09 pm](https://cloud.githubusercontent.com/assets/12092685/7310891/9ba1088c-e9f9-11e4-9cd9-caf0af9ac32b.png)

I can click the link and it lets me download. i have tried several different things and cannot figure out the problem. I feel like i am missing something simple, i just cant find it.

![screen shot 2015-04-23 at 8 45 29 pm](https://cloud.githubusercontent.com/assets/12092685/7310898/b90e4718-e9f9-11e4-9b80-8c65ea061910.png)

**Comment by TheDoctorsLife** [comment]
make sure the file path is correct in your settings. (the should be two urls one for solder to get MD5's and one for the launcher to download the files, they can be the same.)

**Comment by tnert** [comment]
![screen shot 2015-04-24 at 12 33 03 pm](https://cloud.githubusercontent.com/assets/12092685/7324722/7d12d5a0-ea7e-11e4-9683-cc8730dce436.png)

**Comment by tnert** [comment]
I have tried every different path I can think of

**Comment by TheDoctorsLife** [comment]
ahh, that's your issue, You need to put the Repository location to the FULL path, not the relitive path from your solder.

**Comment by tnert** [comment]
So it would be http://tnert.ddns.net/public/

**Comment by tnert** [comment]
Fixed it, i had to do localhost:8888/public/
