### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Giulio1708** [TechnicPack/TechnicSolder#384]
Hi, I've just installed solder on my VPS but when I try to reach the URL is says the classic "500 Internal Server Error".
Here it is my error.log: http://pastebin.com/bgcyW2Mn
Here it is my nginx config: http://pastebin.com/jA8xXHhy

I can't figure out the error, because my "public" folder has a 755 CHMOD (And I've also tryied with 777), can someone help me?
Thanks,
Giulio.

**Comment by Roversword** [comment]
Which user does nginx run under (www-data?)?
I had similar issues (after an update usually) and I have to chown ALL directories and files to www-data again....
However, without further information it is hard to tell what it could be...it is very very likely a permission problem though (quite obviously from the error.log)

**Comment by GenPage** [comment]
Your nginx config has a lot of unneeded settings and directives. Please reference the example config on the Solder Docs: http://docs.solder.io/v0.7/docs/example-web-server-configs#nginx
