### ISSUE TITLE
Error in exception handler

### ISSUE THREAD

**Issue by evilarceus** [TechnicPack/TechnicSolder#385]
Hello,

When I get to the login screen of Technic Solder and try to enter something and log in, I get this error message:

Error in exception handler: The stream or file "/home/matthew/TechnicSolder/app/storage/logs/solderlog-2015-04-26.txt" could not be opened: failed to open stream: Permission denied in /home/matthew/TechnicSolder/bootstrap/compiled.php:9098

I tried modifying the permissions of the specified file(s), but it still gives me the same error. It is my first time trying to set this up.

Help would be appreciated!

**Comment by TheDoctorsLife** [comment]
try '''chown -R root:www-data TechnicSolder/"' then a '''chmod -R 775 TechnicSolder/'''
