### ISSUE TITLE
Possibility to download a mod version from outside source: JourneyMap etc..

### ISSUE THREAD

**Issue by Razorskills** [TechnicPack/TechnicSolder#388]
![moddownloadlinks](https://cloud.githubusercontent.com/assets/6126264/7406581/6ffda794-eec2-11e4-8a41-3f202f246d4e.png)

Basically all that I want, is a way to point the client where to download a file from, and what folder to place it into. And if it cannot download the file, ex website is down, then have a "file backup" that solder can provide in the meantime.

If this can be done, then modpacks using technic solder would be allowed to use JourneMap in their modpack. I mean, obviously my picture is a rough setup, could be better in many ways. But this feature would be for mods that require the modpack launcher/installer to download from their own URL.

This is kind of similar to: #206 except that its not an optional mod, it would be a required mod in the pack. But allowing us to have proper permissions. It is also the same as #339 but that issue was thought to be the same thing as the optional mods issue and was closed. (ps. I don't think they are the same, but they both mention JourneyMap)

**Comment by ET-Bent** [comment]
Wanted to suggest the same thing today. +1 Would be a really great feature and would make modpack permissions way easier to get.

**Comment by TheDoctorsLife** [comment]
+1

**Comment by disconsented** [comment]
Would love to see this as you could also allow alternative mirrors for redundancy :)

**Comment by wolrah** [comment]
I posted this initially over on #206 but realized it fit better here.

Depending on your web server config you can create a /api/mod/<modname>/ tree under the "public" directory and just make files named version numbers containing the MD5 and the outside URL.  It'll override the response from Solder and should cause the client to download from the other URL instead.  Obviously this would need to be manually updated, but if your mod author is cooperative this should work for now.

Doing this does result in the HTTP Content Type being application/octet-stream rather than application/json which means browsers will treat it as a download rather than something to display when checking it.  No idea if that matters to the actual Technic client, I haven't tested doing this in a real modpack yet.

That part is easy to solve if it actually matters though, just drop this in your nginx config:

    location /api/ {
        default_type application/json;
    }

**Comment by bochen415** [comment]
The idea mentioned above breaks solder in some ways.
The launcher searches for a download list rather in 
/api/modpack/modpack_name/modpack_build/client_cid than in /api/mod but the directory structure made in the public directory doesn't take into consideration that the launcher is also searching for modpacks depending on its cid (solder client config) giving a 403 error.

There's a workaround available but that needs the modders help to work:
a simple nginx (or other web server) redirection in the solder mods repository site to a external url (with a solder compatible zip file) will take care of this.

Example:
The JourneyMap author made a solder friendly zip and uploaded it to curseforge
http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2242259

I added 
```
    location /mods/journeymap/journeymap-1.7.10-5.1.0rc3-unlimited.zip {
        return 301 http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2242259/download;
    }
```
in my nginx mods repository configuration so the server will answer with 'moved' to a new url.
a simple 'wget -S mod_url' will verify that

**Comment by Razorskills** [comment]
And right now, this is working for you? If so Im going to have to try doing that.

**Comment by bochen415** [comment]
Working like a charm

**Comment by Razorskills** [comment]
Ok, i will try get it working when i get home. This is awesome news. Although im not sure i fully understand what you did, but il probably figure it out.

**Comment by GenPage** [comment]
Basically when Solder or the Launcher attempt the URL in your mod repository, the nginx server instead redirects them to a different url (using the proper HTTP 301 redirect code)

**Comment by Razorskills** [comment]
hmmmm I can't seem to get it to redirect properly with the Technic launcher this:
```
        location /mods/journeymap/journeymap-5.1.0rc3-unlimited.zip {
            return 301 http://minecraft.curseforge.com/mc-mods/32274-journeymap$
        }
```
does download correctly in the browser, but in the launcher is does not. Same thing with wget it doesn't say that it redirects.

but if I add ~ before the location like this:
```
        location ~ /mods/journeymap/journeymap-5.1.0rc3-unlimited.zip {
            return 301 http://minecraft.curseforge.com/mc-mods/32274-journeymap$
        }
```
 it works in the browser, etc but not in the launcher, it shows up as an error
wget -S tells me that it does redirect.

**Comment by Razorskills** [comment]
So I was having issues getting this working. GenPage explained that there is not supposed to be any kind of file locally, and that it should just get the md5 from curse.

After playing with that, it wasn't able to get the md5, which resulted in the downloads not working. here is a pastebin with the logs when you try to add the version: http://pastebin.com/WU2KYSKy

I'm not sure if that is a problem with anyone else, or if it is just a problem with me and one of my settings. But I found that if I download the proper file, then place it in my repo, get the md5 of the mod, then delete the mod from my repo. it will be able to download the file from curse forge no problem. So until someone tells me they have it working and perhaps has any idea of how to fix it. this is a good enough work around for me. :)

**Comment by GenPage** [comment]
The problem from the pastebin is that it never attempts the actual URL over http:// and keeps attempting to index mods internally through a file path. So it never hits the nginx server to redirect.

**Comment by Razorskills** [comment]
hmmm is that a solder limitation? Or a settings I might have wrong?

**Comment by bochen415** [comment]
I also had the same problem, I needed the file locally for md5 hashing but my repository is set as a local repo in /app/config/solder.php so there's that.

**Comment by bochen415** [comment]
If this setting:
https://github.com/TechnicPack/TechnicSolder/blob/master/app/config-sample/solder.php#L11
is set to a local path (/var/www/repo/) the md5 should fail but if that's set to a your repo public url (http://repo.something.xy/) it *should* work without the file present in the repository.

**Comment by GenPage** [comment]
Please see https://github.com/TechnicPack/TechnicSolder/issues/206 for future updates.
