### ISSUE TITLE
Help Please :(

### ISSUE THREAD

**Issue by TheGoldenKibby** [TechnicPack/TechnicSolder#389]
Hello! I have never done a but of modding in my life, but I want to make a modpack. I just can't seem to figure out how to link Solder to the TechnicPlatform. I am very confused and have no idea what is going on. Help is greatly appreciated. :D

**Comment by ET-Bent** [comment]
First of all welcome to TechnicSolder. 

The best way to start is working through the docs: http://docs.solder.io/

There you will find everything you need to know to get started.

Here you will find information on how to connect Solder to your TechnicPlatform account: http://docs.solder.io/v0.7/docs/linking-solder-to-the-technic-platform

But please be aware that solder is not your "double click .exe setup" and should be handled with caution! Excerpt from the solder docs getting started page:

![bildschirmfoto vom 2015-05-03 13 16 23](https://cloud.githubusercontent.com/assets/5788982/7444826/cf246c72-f196-11e4-81bf-d3dc53f1d90c.png)

Have fun and let us know if you need additional information that could not be found in the docs.

**Comment by TheGoldenKibby** [comment]
Thank you for the help! I guess I'll just have to wait until I understand this stuff more so I don't ruin my computer, but thank you again.

**Comment by Razorskills** [comment]
If you don't feel up to using solder, but still want to play around with making your own modpack, you can still do it using the zip method. 

For that all you need to do is make a zip file that the contents will be placed in the base folder of the modpack. So normally it would look like this:

file.zip
   bin
     modpack.jar  (this file is just the forge version you want to use with the name changed to modpack)
   config
     any configs you would like to include/modify
   mods
     modA.jar
     modB.jar
   resourcepacks   (optional, you do not have to include folder you aren't going to use)
     Unity-Complete-1.2.0.zip (example of resource pack)
 options.txt  (these 2 are not in any folders, just in the base zip file)
 server.dat

Here is a picture of my base zip folder to help make more sense:
![zipstructure](https://cloud.githubusercontent.com/assets/6126264/7445197/8804a9d2-f165-11e4-8498-7c0d940d2bad.PNG)

The only folders you really actually need in here is the bin folder with forge inside of it, and your mods. anything that isn't in there will be generated to be default like the options, or all the mod configs. But if you want to edit them, then you need to include the edited configs etc..

After you have your zip file set up, you will need to host the file somewhere that the file download link doesn't change and is a direct download.
(I use dropbox, if you want to use dropbox too, let me know and I will post how I get my direct download links if you want to go that route, but there are other places)
If you can paste your link in the address bar, press enter, and its starts downloading the file right away, then that is the link you need.

once you have that set up and ready, you can now go to http://www.technicpack.net/modpack/create
and start setting it up! Choose a name, select the minecraft version you are using, select hidden pack if you probably haven't gotten any permissions to use the mods yet. You can change it later from hidden as long as you have all the permissions to have the mods in a public pack. But for now, it should be a private pack while you are testing, and getting your permissions page setup etc..
Then you need a small description of the pack, you can change it later so don't worry about it too much.

If you agree to the terms, then check the box and create your modpack page.

Once your modpack page is ready and made, you can click the edit modpack button, and under "Modpack Location" you want to paste the direct download link from earlier there.

You can also go to the "Versions" tab and put in a version number and have your changelog there.
Explore the pages, and fill out any other information you want.

But that is basically the easy way of getting a modpack setup without using solder. If you decide to try this route, and have any questions, I don't mind helping.

**Comment by TheGoldenKibby** [comment]
Thank you so much! I got to the point where I can see my pack in the launcher, but whenever I try to install it, it says there was an error unzipping the file and that the file did not exist. I have the zip in my dropbox and linked as Archive.zip. Do I need to change the name of it for it to work?

**Comment by Razorskills** [comment]
Paste your drop box link

**Comment by TheGoldenKibby** [comment]
Ok, i got to the point where I can install it, thanks to the link, but there's something wrong with the files. When I hit play, it just pauses for a second then goes back to the launcher. Here's the link - https://www.dropbox.com/s/4qoq04y61vh2qd6/Archive.zip?dl=0

That's not the edited link, just the one dropbox gave me. The modpack has the modifed one in it.

**Comment by Razorskills** [comment]
its as simple as you didn't put code chicken core in your modpack..

**Comment by TheGoldenKibby** [comment]
I put codechickencore in the mods folder, but it still isn't working. Sorry for being a noob at this, im still really bad at modding. https://dl.dropboxusercontent.com/s/emtlcagc3oa5t4u/Archive%202.zip?dl=0

**Comment by Razorskills** [comment]
![capture](https://cloud.githubusercontent.com/assets/6126264/7624833/0ef75d1a-f9ac-11e4-82fb-4512a71f0f8d.PNG)

I ran the modpack you have packaged, and that is what pops up. Means it works, but it tells you that the minimu version of codechickencore is 1.0.4. Simple

here is a link to the mod on curse. http://minecraft.curseforge.com/mc-mods/222213-codechickencore/files

Grab the latest for 1.7.10.

I would also update NEI http://minecraft.curseforge.com/mc-mods/222211-notenoughitems/files

**Comment by TheGoldenKibby** [comment]
Thank you for all your help! Sorry I haven't responded sooner, I got slammed with schoolwork. I did what you said, but it still isn't working for some reason. I think it might be my launcher, but the topic has gone a ways away from Solder, so I'll go ahead and close this. Thank you for your help! :)
