### ISSUE TITLE
Internal Server error in TechnicSolder when choosing one of >50 mods

### ISSUE THREAD

**Issue by Roversword** [TechnicPack/TechnicSolder#392]
Hi all

Technicsolder is up and running...I can choose and make modpacks with >50 mods I added to the database. However, there is one particular mod I added (called IronChest) which I cannot add to a modpack.
Whenever I open a modpack and try to add this particular mod, technicsolder tells me internal server error and I cannot choose a version number.

The logs say:
[2015-05-14 17:08:13] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/datadisk/technicsolder/app/storage/cache/9b/12/9b1231fec7273c9dd28c69d46fb01751): failed to open stream: No such file or directory' in /datadisk/technicsolder/bootstrap/compiled.php:4221
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_put_conten...', '/datadisk/techn...', 4221, Array)
#1 /datadisk/technicsolder/bootstrap/compiled.php(4221): file_put_contents('/datadisk/techn...', '1431637993O:3:"...', 0)
#2 /datadisk/technicsolder/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(106): Illuminate\Filesystem\Filesystem->put('/datadisk/techn...', '1431637993O:3:"...')
#3 /datadisk/technicsolder/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(94): Illuminate\Cache\FileStore->put('mod.ironchest', Object(Mod), 5)
#4 [internal function]: Illuminate\Cache\Repository->put('mod.ironchest', Object(Mod), 5)
#5 /datadisk/technicsolder/bootstrap/compiled.php(8300): call_user_func_array(Array, Array)
#6 /datadisk/technicsolder/bootstrap/compiled.php(3271): Illuminate\Support\Manager->__call('put', Array)
#7 /datadisk/technicsolder/bootstrap/compiled.php(3271): Illuminate\Cache\CacheManager->put('mod.ironchest', Object(Mod), 5)
#8 /datadisk/technicsolder/app/controllers/ApiController.php(101): Illuminate\Support\Facades\Facade::__callStatic('put', Array)
#9 /datadisk/technicsolder/app/controllers/ApiController.php(101): Illuminate\Support\Facades\Cache::put('mod.ironchest', Object(Mod), 5)
#10 [internal function]: APIController->getMod('ironchest')
#11 /datadisk/technicsolder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#12 /datadisk/technicsolder/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('getMod', Array)
#13 /datadisk/technicsolder/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(APIController), Object(Illuminate\Routing\Route), 'getMod')
#14 /datadisk/technicsolder/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiController', 'getMod')
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('ironchest')
#16 /datadisk/technicsolder/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#17 /datadisk/technicsolder/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /datadisk/technicsolder/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /datadisk/technicsolder/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /datadisk/technicsolder/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /datadisk/technicsolder/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#22 /datadisk/technicsolder/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 /datadisk/technicsolder/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 /datadisk/technicsolder/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 /datadisk/technicsolder/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 /datadisk/technicsolder/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []

I already deleted the mod and readded it, to no avail....anything I can do?

Thanks a lot!

**Comment by Roversword** [comment]
As I mentioned, I deleted that mod (and mod-slug) and readded it...but still get this error.
Now, the question is...is there a way to delete the "cache" and re-do without a new installation?

**Comment by GenPage** [comment]
"php artisan cache:clear"
