### ISSUE TITLE
API should have a /mods method to list mods

### ISSUE THREAD

**Issue by Graypup** [TechnicPack/TechnicSolder#393]
I'm writing a packaging system for solder mods. With the current API, it's impossible to list all mod slugs. This feature would be immensely useful for not needing to hook into the mod repository directly.

**Comment by cfreear** [comment]
Alternatively ```/api/mod``` could return an array of mods if no mod is specified. Like ```/api/modpack``` currently does.

**Comment by Indemnity83** [comment]
This should be closed, one step closer to 0.7.3 :+1:

**Comment by Indemnity83** [comment]
@GenPage this has been complete for 6 months now, can we close it out?

**Comment by GenPage** [comment]
@Indemnity83 Sorry about that. Thanks for the reminder. Closing
