### ISSUE TITLE
Can't update modpack

### ISSUE THREAD

**Issue by LemonLake** [TechnicPack/TechnicSolder#394]
I'm most likely being stupid here and missing something obvious, however I can't find anything at all in the documentation. I am trying to update my modpack; I have created a build, added all the mods, made it recommended, lastest, published et cetera. However, nothing shows up in the Technic Launcher or on the modpack page. I have restarted, reinstalled the pack, all that but it simply won't update. Is there an update button of some sort that I am missing?

![Image](http://puu.sh/hTLD9/705a3b04f1.png)

**Comment by TheDoctorsLife** [comment]
Sounds like the technic API hasn't updated with the most recent data, I recommend waiting for a day or so to see if this fixes it self, then come back if your still having issues.

**Comment by LemonLake** [comment]
Thank you. My players will be able to download the pack fine in the
meantime, right?

**Comment by LemonLake** [comment]
For reference, I used the zip system prior.

**Comment by LemonLake** [comment]
Just updated the pack after unlinking it for the night, it works now. Thank you!

**Comment by TheDoctorsLife** [comment]
Not a problem

**Comment by TheDoctorsLife** [comment]
Not a problem, for now on I suggest you release a update a day early to make sure the API is updated.

**Comment by LemonLake** [comment]
Will do. Thanks!
