### ISSUE TITLE
[Help] 404 Error After Installing

### ISSUE THREAD

**Issue by Dylan3304** [TechnicPack/TechnicSolder#396]
Hello everyone,
I installed Technic Solder by following the [documentation](http://docs.solder.io) on a CentOS 7 Apache Server. When visiting my [URL](https://repo.minewrath.com), I get:

![Error Message](http://i.imgur.com/TYHJXhf.png)

I'm new to Technic, so tell me what logs I need to provide and such. **Thank you in advance!**

**Comment by ET-Bent** [comment]
Seems to work now, atleast for me, I am getting to your solder login page.

**Comment by Dylan3304** [comment]
Yep, I got everything working. **However,** I encountered another error. Solder can't communicate to the repo over SSL, as it returns a common alrogithm error. I just disabled SSL on the repo and it worked fine ;)

**Comment by MasterWofleh** [comment]
Dylan, Can you assist me? 

I am using the supplied sqlite database, but it keeps telling me that its readonly and I can't fix it.

**Comment by Dylan3304** [comment]
@MasterWofleh is it appearing in your logs, or in browser, or what?

**Comment by MasterWofleh** [comment]
broswer.  http://solder.impact-gaming.net  
try logining in with default login. You'll see it.

**Comment by Dylan3304** [comment]
Try this:
```
chmod 0777 app/database/production.sqlite
```

**Comment by MasterWofleh** [comment]
Did that, rebooted and same error

**Comment by MasterWofleh** [comment]
As a matter of fact, if you wish to look at it closer, I can pm you my ssh details and you can look at it.  if you don't mind of course.

**Comment by Dylan3304** [comment]
![screen shot 2015-05-27 at 7 47 40 pm 2](https://cloud.githubusercontent.com/assets/2935060/7850553/58f0cd7c-04a9-11e5-9cc7-58f181c2e2fd.png)
Works okay for me :).

**Comment by MasterWofleh** [comment]
Try adding another user or updating the admin account yet?

**Comment by Dylan3304** [comment]
Okay, try this:
```
chown apache:apache file /path/to/solder/app/database/production.sqlite
```
**This** is for apache. Let me know if you are using Nginx or Apache, and your VPS OS.

**Comment by MasterWofleh** [comment]
nginx, and ubuntu 14.04

**Comment by Dylan3304** [comment]
Okay, so give me the output of this:
``` bash 
ls -l /path/to/solder/app/database/production.sqlite
```

**Comment by MasterWofleh** [comment]
-rwxrwxrwx 1 www-data www-data 25600 May 21 23:35 /usr/share/nginx/TechnicSolder/app/database/production.sqlite

**Comment by Dylan3304** [comment]
Okay, so try this:
``` bash
chown www-data:www-data /usr/share/nginx/TechnicSolder/app/database/production.sqlite
```

**Comment by MasterWofleh** [comment]
Reboot?

**Comment by Dylan3304** [comment]
No need to.

**Comment by MasterWofleh** [comment]
Done.  Still no work on my end.

**Comment by Dylan3304** [comment]
What about `chmod 0777 /usr/share/nginx/TechnicSolder/app/database/`?

**Comment by MasterWofleh** [comment]
Same thing, done it, no fix.

**Comment by Dylan3304** [comment]
It is some sort of permissions error. Maybe one of the dev has some input. **However,** it doesn't like you followed the [initial configuration](http://docs.solder.io/#initial-configuration) steps, so try that.

**Comment by MasterWofleh** [comment]
I followed it to a tee.  Me and @GenPage was even discussing it while I done it.  He said he would sat down with me this past Monday and redo it, but he was no where to be found.  

I'm to the point to just let someone do it for me. lol

**Comment by Dylan3304** [comment]
@MasterWofleh good luck. I'm out of ideas. xD
