### ISSUE TITLE
HTTPS tunnel support

### ISSUE THREAD

**Issue by taktoa** [TechnicPack/TechnicSolder#399]
Laravel does not account for the fact that you may be running your web server behind a proxy that acts as an HTTPS endpoint, and mistakenly serves content with links to HTTP assets etc.

To fix this, all one would need to do is add a dependency on https://github.com/fideloper/TrustedProxy and configure it with sane defaults (e.g.: trusting localhost only).

**Comment by TheDoctorsLife** [comment]
or maybe set the production url to "https://yourdomain.com"

**Comment by taktoa** [comment]
I've done that, but it doesn't work because Laravel sees the requests as being HTTP and generates the asset links as such.

**Comment by GenPage** [comment]
Interesting find, are you using this in an production setting with Solder? If so, I would like to see examples of it. 

You can very easily force HTTPS within the web server by use of Apache's RedirectSSL module and Nginx's server blocks. 

I opt to force HTTPS for Solder this way as trying to switch between HTTP and HTTPS is very tricky.

**Comment by spannerman79** [comment]
Not to mention the requirements to have valid SSL (Dedicated IP, SSL Cert) for which some don't have a need for.

**Comment by TheDoctorsLife** [comment]
There are free so options, like https://startssl.com. Also with SNI, a dedicated ip isn't really needed.

**Comment by spannerman79** [comment]
StartSSL and CACert options do not validate properly - which is the whole point of having an SSL is to be validated in the first place.  Catch 22

**Comment by ruifung** [comment]
It does validate properly in some browsers anyway.

**Comment by TheDoctorsLife** [comment]
I know both Chrome (Who uses windows cert store) & firefox trust them. Anyhow all modern browsers  support SNI which allows multiple domains on one IP. On the matter of startssl, what modern browser doesn't trust them? Another free ssl alternative is to use a self-signed cert, & have something like [Cloudflare](https://cloudflare.com) fix it with a valid cert coming from them. Or you can pay like $10 for something like a positive ssl from [Namecheap](https://www.namecheap.com/security/ssl-certificates/comodo/positivessl.aspx)

**Comment by GenPage** [comment]
Closing issue since discussion is now outside of the original post
