### ISSUE TITLE
[FEATURE] Merge Minecraft Forge JSON from modpack.jar and normal Minecraft version JSON

### ISSUE THREAD

**Issue by MetalBreaker** [TechnicPack/TechnicSolder#400]
So, a feature that I think may be useful for Technic Solder is to merge the Minecraft Forge JSON from modpack.jar and the normal Minecraft version JSON (add missing libraries from the regular Minecraft version JSON to the Minecraft Forge version JSON. This would make Technic Launcher download libraries required for Forge and the Minecraft-required libraries. This would be a plus because two of the libraries in the regular Minecraft version JSON are outdated (Guava version comparison: 17.0 vs 15.0, Apache Commons-lang 3.3.2 vs 3.3.1). This is what I use for my modpacks. So, if anyone is interested in downloading the already-made JSON, here it is: http://johny-solder.rhcloud.com/mods/minecraftforge/10.13.3.1408/version.json (1408), http://johny-solder.rhcloud.com/mods/minecraftforge/10.13.3.1420/version.json (1420, latest).

SETUP INSTRUCTIONS:
1. Download the already-made JSON corresponding to your Minecraft Forge version.
2. Do the modpack setup normally, but while packing Minecraft Forge, add the version.json in the bin folder. Also add it in the modpack.jar and replace the current file.
3. Distribute your modpack as usual.

What I actually did with the JSON was:
1) Delete the 10th and 11th line in the original JSON (jar and inheritsFrom)
2) Added libraries from 1.7.10 json to Minecraft Forge JSON (skipped adding already-existing libraries, those were Guava and Apache Commons Lang).

**Comment by king601** [comment]
I can't reproduce this bug on my instance. 

Steps I took:
* I downloaded 10.13.3.1420 from files.minecraftforge.net universal download
* I renamed it to modpack.jar and put it inside of a bin folder
* I zipped the bin/ folder with the modpack and uploaded it to my solder repo. 
* I added the Minecraft forge mod 1420 and added it to a clean pack with no other mods. 

I was able to launch Minecraft 1.7.10 and have 10.13.3.1420 enabled. Do you have a specific version of Forge you want me to try and see or was it everyone? I can try 1408 if needed

**Comment by MetalBreaker** [comment]
@king601 , I can reproduce the bug. This is really weird. My modpack won't launch if I don't do the steps I mentioned, it would crash because of missing libraries. :/

**Comment by Razorskills** [comment]
Post a link to download your forge file? Then we can have a look at it.

**Comment by MetalBreaker** [comment]
@Razorskills I downloaded the original forge from files.minecraftforge.net. However, on my Solder, I have only got the modified ones.

**Comment by king601** [comment]
Okay question then: 
What version of MC is listed for your modpack on the TechnicPack website? What version is listed under Solder's settings? 

Try packaging up a fresh jar and sending us a link to download it (the unmodified forge jar that doesn't work for you) and we can try it on our instances.

**Comment by MetalBreaker** [comment]
Version 1.7.10 is listed on both sites.
Just tested it, it works. I don't know what was the problem. But I'm still gonna hold on to my method, cause it contains the updated libraries, and the JSON contains the libraries required for the latest version Forge.
