### ISSUE TITLE
View the latest added version of a mod in the Mod Library

### ISSUE THREAD

**Issue by SunshineHunter** [TechnicPack/TechnicSolder#401]
Hello, a small suggestion,

it would be practical to see the latest added version of a mod already in the mod library. Currently you need to view the mod and then the version tab. This would save only some seconds when updating, but I guess it's worth.

It could be added after the pretty_name [here](https://github.com/TechnicPack/TechnicSolder/blob/master/app/views/mod/list.blade.php#L43), for example "Applied Energistics rv2-stable3".

**Comment by EntranceJew** [comment]
I implemented this, but I couldn't decide where to put it. Which looks better?
It's own column:
![own column](http://i.imgur.com/3OypfyF.png)
In the mod name:
![in the mod name](http://i.imgur.com/FR2wgOM.png)
I implemented the former over at:
EntranceJew/TechnicSolder@04cde34f565689de95919ee79ad3a266e95e7a9e

**Comment by GenPage** [comment]
@EntranceJew Nice! I prefer the latter. that way the column widths are so squished.

**Comment by GenPage** [comment]
:+1: :shipit:

**Comment by spannerman79** [comment]
:+1: I like the latter view as well :smile:

**Comment by SunshineHunter** [comment]
Thank you for implementing this!
