### ISSUE TITLE
Mods Page is not sorting by Mod Name, but by mod Slug

### ISSUE THREAD

**Issue by Razorskills** [TechnicPack/TechnicSolder#402]
Well, basically here is a picture for you:
![capture](https://cloud.githubusercontent.com/assets/6126264/7905555/db67eb2e-07d7-11e5-96a8-3ecc16502f19.PNG)

Notice how it put Minecraft Forge in between Extra Utilities, and Gilded Games Util? 

I believe the alphabet goes a, b, c, d, e, f, g...  not e, m, g

Anyways the reason that happens is because my slug name for the mod in my files is just "forge"
its the short version of the proper name. So I think the list should be changed to sort by Mod name instead.

**Comment by GenPage** [comment]
Can you provide the Solder API link for this modpack? Need to check to see if this is an issue with the Solder API response or how Platform parses the data. Thanks

**Comment by Razorskills** [comment]
Here you go:
http://solder.aimgaming.net/api

Here is the pack if that helps:
http://www.technicpack.net/modpack/the-syndrome

**Comment by Pyker** [comment]
This was a SolderClient issue, fixed in https://github.com/TechnicPack/SolderClient/commit/2ea2e698a166a8818c07bde4c947ca74735f5c13.
