### ISSUE TITLE
SoftException in Application.cpp:350: UID of script

### ISSUE THREAD

**Issue by skulldrago** [TechnicPack/TechnicSolder#403]
Hello i have installed the solder and now when i try to open the webinterface i get error 500 Internal Server Error.

The error.log says:
SoftException in Application.cpp:350: UID of script index.php is smaller than min_uid

Whats going wrong?

**Comment by GenPage** [comment]
Looks like an issue with the hosting you are using. I would contact their support first as this is a PHP error.
