### ISSUE TITLE
Switching existing pack to solder not propagating

### ISSUE THREAD

**Issue by LemADEC** [TechnicPack/TechnicSolder#404]
I've installed Solder, linked it to my account and used same scrub as our existing modpack.
Technic site detects properly the new versions and have a 'solder' tag.
However, the launcher doesn't pickup the solder tag nor the version changes. It still uses the old 'non-solder' way to download the modpack file.

I've tried 'reinstalling' the modpack, deleting its folder and deleting it from the launcher, to no avail.
The launcher doesn't even catch the version list, it's still stuck on the old 'non-solder' version.
Did I miss something in solder setup?

**Comment by GenPage** [comment]
This is most likely an issue with the Technic API not updating immediatelydue to the API cache, since the solder tag appears on the website but not in the launcher.

**Comment by LemADEC** [comment]
It has been 6 days, and our pack still doesn't show up as 'solder' in the launcher.
It does shows as 'solder enabled' on the website.

**Comment by TheDoctorsLife** [comment]
maybe a link to your pack can help.

**Comment by LemADEC** [comment]
Here's the pack in question: http://www.technicpack.net/modpack/tdks-world-war-minecraft-beta.260585

**Comment by maccelerated** [comment]
This might help a little:
I used the Solder URL from the [Platform URL](http://api.technicpack.net/modpack/tdks-world-war-minecraft-beta?build=4.301):
Request GET http://mc.pyrostasis.com/solder/public/index.php/api/
Redirects 301 http://mc.pyrostasis.com/index.php/api
Redirects 302 http://acid3.acidtests.org/

Maybe Solder isn't aware that it exists at /solder/public/?

**Comment by TheDoctorsLife** [comment]
However it seems that the redirect doesn't occur when there isn't a trailing / eg http://mc.pyrostasis.com/solder/public/index.php/api/modpack/tdks-world-war-minecraft-beta/7.0.3 works, but http://mc.pyrostasis.com/solder/public/index.php/api/modpack/tdks-world-war-minecraft-beta/7.0.3/ redirects.

**Comment by LemADEC** [comment]
Removing the /public/.htaccess file solve the issue, as long as disabling the rewrite module, or changing it to off in the public folder.
So it looks like a bug in the .htaccess configuration of the public folder while using the rewrite module.
