### ISSUE TITLE
Unable to link solder api key to solder

### ISSUE THREAD

**Issue by monokin** [TechnicPack/TechnicSolder#405]
Hey when I attempt to link my technic account to my solder install I get this error

[curl] 6: Could not resolve host: solder [url] solder/api/verify/02502e822fbe7cd05a280b5991f19e5c

**Comment by monokin** [comment]
Now im getting 
Client error response [status code] 404 [reason phrase] Not Found [url] http://knoxsolder.tk/solder/api/verify/

**Comment by TheDoctorsLife** [comment]
try this for your API url, http://knoxsolder.tk/solder/public/api/

**Comment by monokin** [comment]
I had to reinstall solder to get it working
