### ISSUE TITLE
Issue with Solder & Modpack

### ISSUE THREAD

**Issue by BlameDylan** [TechnicPack/TechnicSolder#406]
Hello everyone,
I recently setup Technic Solder on a CentOS VPS and I have enjoyed playing my modpack. However, I gave it to my friend and when he attempts to download it he receives a popup that contains something like:
```
Error unzipping mymodpack-1.0.0.zip, file not found.
````
It shouldn't attempt to unzip a modpack file, as it is a Technic Solder pack. Also, the green _Solder Enabled_ tag doesn't show up (on my friends computer). However, my other friend and I can download and play fine. Any ideas?

**Technic Platform URL:** [http://www.technicpack.net/modpack/illuminations-reloaded](http://www.technicpack.net/modpack/illuminations.671037)
**Solder Installation:** [http://repo.minewrath.com](https://repo.minewrath.com)

**Comment by TheDoctorsLife** [comment]
When visting the solder url your provided, I get this page ![picture](https://imgur.com/14Rj1uC)

**Comment by BlameDylan** [comment]
@TheDoctorsLife I changed my solder installation from HTTPS to HTTP because my friend had some SSL error. Therefore, I created a new pack and everything works! It is a shame though that Technic doesn't use SSL.
