### ISSUE TITLE
Error Downloading file for modpack

### ISSUE THREAD

**Issue by monokin** [TechnicPack/TechnicSolder#407]
Im getting a error.

Error downloading file for modpack.

knoxsolder.tk/api works and so does 
knoxsolder.tk/api/

Cant quite figure out why its not working
![image](https://cloud.githubusercontent.com/assets/11347035/8126137/cf16bcc0-10b9-11e5-93cb-a1ede1f345b0.png)

**Comment by monokin** [comment]
When I change it to what it use to be
knoxsolder.tk/solder/public/inxed.php/api works
knoxsolder.tk/solder/public/inxed.php/api/ does not

**Comment by TheDoctorsLife** [comment]
try using  http://knoxsolder.tk/index.php/api

**Comment by monokin** [comment]
That works but that doesn't fix the problem with tha launcher

**Comment by TheDoctorsLife** [comment]
http://www.knoxsolder.tk/mods/ gives me a 403, try fixing the file perms for your repo.

**Comment by monokin** [comment]
This works.
www.knoxsolder.tk/mods/forge/forge-1403.zip

**Comment by monokin** [comment]
now www.knoxsolder.tk/mods works
But I still get the same error

**Comment by monokin** [comment]
When I click the mod in the mod version it sends me here
http://knoxsolder.tk/solder/public/index.php/mod/view/www.knoxsolder.tk/mods/forge/forge-1403.zip
I can download the mod from that file

**Comment by monokin** [comment]
But it should be www.knoxsolder.tk/mods/forge/forge-1403.zip not the other link. Im not sure hot to fix that

**Comment by GenPage** [comment]
Solder currently does not support handling mods from within the same virtual host. You will need to create a seperate vhost for the web server to handle file requests/downloads
