### ISSUE TITLE
Deleting builds/modpacks 

### ISSUE THREAD

**Issue by skittishtrigger** [TechnicPack/TechnicSolder#408]
A small issue where when deleting all the builds in a modpack it redirects you into the "We hit a snag page" instead of modpack list or home page. Have not tested with directly deleting from the modlist page yet.

**Comment by GenPage** [comment]
Please enable the debug variable in your app.php config file, reattempt this, and post the debug exception trace.

**Comment by GenPage** [comment]
No update on issue, closing.
