### ISSUE TITLE
Just a feature... But it's to much code do find the right place... don't know if in Js or php... heres a php sample... maybe its helpfull

### ISSUE THREAD

**Issue by jak1** [TechnicPack/TechnicSolder#409]
it's bad to add every mod 1 time, if you have 100+ mods, and need to add them all with Browser, and need to look about that version...

<?php 

class modHandler{
	
	public function modHandler(){}
	
	public function readMods($mod_directory){
		$mod_folders 	= array(null);
		$c				= 0;
		if (is_dir($mod_directory)){
			if ($dh = opendir($mod_directory)){
				while(($mod_dir = readdir($dh)) !== false){
					if (is_dir($mod_directory.$mod_dir) && $mod_dir != "." && $mod_dir != ".."){
						$mod_folders[$c] = $mod_dir;
						$c++;
					}
				}
				closedir($dh);
			}
		}
		return $mod_folders;
	}
	public function readVersions($mod_directory, $mod){
		$versions	= array(null);
		$c 			= 0;
		if (is_dir($mod_directory.$mod)){
			if ($dh = opendir($mod_directory.$mod)){
				while(($version = readdir($dh)) !== false){
					if (!is_dir($mod_directory.$mod.$version) && (strpos($version,'.zip') !== false)){
						$versions[$c] = $version;
						$c++;
					}
				}
			}
		}
		return $versions;
	}
}
?>

<?
include_once("modHandler.php");
$modHandler = new modHandler();
$mod_directory = "./mods/";
			$mods		= $modHandler->readMods($mod_directory);
			$modcount	= count($mods);
			
			for($i = 0; $i <  $modcount; $i++){
				
				$versions 		= $modHandler->readVersions($mod_directory,$mods[$i]);
				$versionscount	= count($versions);
				
				echo "<b>Name: </b>" . $mods[$i] . " <b>| Versions:</b> ";
				echo "[ ";
				for($j = 0; $j <  $versionscount; $j++){
					echo $versions[$j] . ", ";
				}
				echo "]<br>";
			}
			
		?>

**Comment by GenPage** [comment]
Thank you for your suggestion. Mod uploads are planned but we are not accepting code snippets or PRs for it at this time.
