### ISSUE TITLE
Ability to manually edit md5 hashes

### ISSUE THREAD

**Issue by GenPage** [TechnicPack/TechnicSolder#410]

**Comment by TheDoctorsLife** [comment]
+1

**Comment by spannerman79** [comment]
Just curious - what purpose would manually editing a md5 hash have?

md5 hashes are - what i assume - to ensure a file was downloaded correctly.  Changing even one character in the md5 hash would invalidate that hash and that particular file

Technically a SHA-1 hash would be better but that might put undue overhead on servers hosting files

**Comment by TheDoctorsLife** [comment]
I think the idea is for large zips to be manually md5'd then inputted into solder without having to manually edit the db.

**Comment by GenPage** [comment]
Correct, currently md5-hashing zips are prone to failure if there are over 64MB due to the default memory_limit set in PHP's configuration. (php.ini). 

This is just an easier way to allow mod pack owners to manually md5 the zip and add it, without having to wait for PHP to inefficiently do it.
