### ISSUE TITLE
PHP & Bootstrap

### ISSUE THREAD

**Issue by ConnorHartley** [TechnicPack/TechnicSolder#412]

**Comment by ThePixelPony** [comment]
I also have this issue.

**Comment by JamenMarz** [comment]
+1

**Comment by ConnorHartley** [comment]
Also not keeping the plain bootstrap template and make it more like the technic page.

**Comment by maccelerated** [comment]
I'm currently working on this issue. :3 Almost ready for first release.

**Comment by ConnorHartley** [comment]
Sounds good! Can't wait.

**Comment by GenPage** [comment]
Me neither!
