### ISSUE TITLE
Version comparison

### ISSUE THREAD

**Issue by skittishtrigger** [TechnicPack/TechnicSolder#413]
Recently I ran into a situation where I would have loved to be able to do a side by side comparison of several versions (or just 2) of a modpack.  Like selecting modpack-1.7.0 and modpack-1.7.1 and hitting compare.  The resulting output would display two columns with mods listed side by side with the version of each mod.  I do not know if this would be helpful to others but I would love this feature as a troubleshooting helper. Any thoughts?

**Comment by bochen415** [comment]
https://github.com/TechnicPack/TechnicSolder/issues/129

**Comment by skittishtrigger** [comment]
.......darn it. Close away on this one. Didn't look good enough. :/
