### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Misterio77** [TechnicPack/TechnicSolder#417]
Hey, i would like to ask for help regarding solder.
I've followed this guide: http://docs.solder.io/, After installing all the dependencies, setting up the server, everything went fine, i can see the page but when i try to login using admin@admin.com and admin it doesn't works (Like if the credencials were wrong).
I've tried resetting the MySQL database and re-installing solder from scratch but to no avail.

PS: I can supply logs and config files if needed.

Thanks for your time,
~Misterio77

**Comment by GenPage** [comment]
What error do you get when you attempt to login? "Login failed"?

Please turn set "debug" to true in app/config/app.php and try again.

**Comment by Misterio77** [comment]
I don't get any errrors at all, the email and password fields just reset and nothing happens.
I tried the debug mode but nothing different happened.

Thanks for the help.

**Comment by GenPage** [comment]
Is there any logs in ```app\storage\logs``` that show any errors?

Can you also provide your web server config?

**Comment by Misterio77** [comment]
There isn't any logs in the folder.
And here's my apache configuration for solder: http://pastebin.com/uiPVfbH4

Thanks,
~Misterio77

**Comment by GenPage** [comment]
Hmmm, your config looks fine. Any errors in your apache log?

**Comment by Misterio77** [comment]
Apache's error log is empty, here's the `access.log` if it makes  any difference: http://pastebin.com/mH2hrTZw
The whole log is basically just me trying and trying to log in :c

**Comment by Misterio77** [comment]
Well, here are some files that may help in solving the problem:

`app.php`: http://pastebin.com/ztaeL25n
`database.php`: http://pastebin.com/46xfheDC
`solder.php`: http://pastebin.com/tB4Gt9n3

I removed my dabase's password and app.php's auth key, because it isn't quite safe to post them in a public location :v.

Thanks,
~Misterio77

**Comment by GenPage** [comment]
Hey there Misterio77, What happens if you disable the Cloudflare you have setup in front of Solder?

**Comment by spannerman79** [comment]
For the record and for later reference was it in fact an issue with Cloudflare @Misterio77 ?
Or some other issue so that something can be done about it or referenced for later if anyone else has the same issue you did.

**Comment by Misterio77** [comment]
Sorry i forgot to say, but i got it fixed by disabling cloudflare on my subdomain (solder.fiercelands.com). That can be done by clicking the cloud icon near the DNS record, so it gets gray.

~Misterio77
