### ISSUE TITLE
"404 Not Found " or "No input file specified"

### ISSUE THREAD

**Issue by Neodark7** [TechnicPack/TechnicSolder#418]
i've just installed Solder on ubuntu 14.04 using nginx and now when i go to http://ks28064.kimsufi.com/solder/public/index.php 
i get "404 Not Found"

here's my nginx/sites-enabled/default file http://pastebin.com/wdhw65gG
Any help ?

**Comment by GenPage** [comment]
If you are only going to be using the VPS for solder, modify the default server block file.

``` root /home/neodark7/www/solder/public ```

If you are going to be hosting other sites, create seperate files for each website, this is called virtual hosting.

Solder virtual host config references: http://docs.solder.io/docs/example-web-server-configs

**Comment by Neodark7** [comment]
for now i'll test to getting this work and later i'll modify it if i need more sites.
When i do this ( root /home/neodark7/www/solder/public ) i'm getting the same error :/
Sorry but i'm really not familiar with nginx :/

http://ks28064.kimsufi.com/dashboard

**Comment by bochen415** [comment]
@Neodark7 join #technic on synirc, maybe someone there can point you in the right direction

**Comment by Neodark7** [comment]
yep here ^^ https://gitter.im/TechnicPack/TechnicSolder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge @GenPage helped me and it's working but i have another problem i need to understand how nginx virtual hosts configs works :/

**Comment by Neodark7** [comment]
issue solved thanks to @Misterio77
