### ISSUE TITLE
Error unzipping a file for the following pack:  but it did not exist.

### ISSUE THREAD

**Issue by klahssik** [TechnicPack/TechnicSolder#420]
can someone plzz help me

Error unzipping a file for the following pack: KlahKi Craft

Attempting to extract file klahki-craft-1.0.zip, but it did not exist. 

Please consult the modpack author

Idk what to do!!!!!!! i really want to play this modpack too lol

**Comment by ruifung** [comment]
Uh
```
Please consult the modpack author.
```

**Comment by spannerman79** [comment]
Close, dupe of #422
