### ISSUE TITLE
Attempted to extract file modpack-KlahKi-Craft-1.0.zip, but it did not exist

### ISSUE THREAD

**Issue by klahssik** [TechnicPack/TechnicSolder#422]
SOMEONE PLEASE HELP IDK WHATS GOING ON I GET THIS MESSAGE PLZZZ HELLP!!!!!
 
Error unzipping a file for the following pack: KlahKi Craft 

Atempting to extract file klahki-craft-1.0.zip, but it did not exist. 

Please consult the modpack author 

PLZZZ HELP

**Comment by ruifung** [comment]
Making multiple issues for the same problem isn't going to get you help any faster. It would probably just annoy people.

That being said, would you happen to have the logs for the launcher?

**Comment by klahssik** [comment]
thats me and
 i didnt know how to get to the other one so i made this one

**Comment by ruifung** [comment]
Would you happen to have the technic launcher logs?

**Comment by klahssik** [comment]
i wish i knew what that was can u tell me plzz ? 
:)

**Comment by ruifung** [comment]
Look in the technic launcher folder? I haven't been using it for a long time, but there are log files detailing what happened in that folder.

**Comment by klahssik** [comment]
like i barely made this mod pack but ill try

**Comment by klahssik** [comment]
this is complicated

**Comment by klahssik** [comment]
u have like skype or something? steam?

**Comment by spannerman79** [comment]
solder is meant for advanced users.  Which it's obvious you are not.  Go back to the other non solder method (complete zip & hosted) to distribute your modpack

**This application is intended for experienced system administrators**

@GenPage please close.  Reason: Failed to read initial paragraph on docs.solder.io

**Comment by klahssik** [comment]
idk what u mean can u just like skype me or something plzzz lol

**Comment by spannerman79** [comment]
@klahssik can you understand whats onlined on the solder documentation website here ( http://docs.solder.io/ ) ?

If no - don't use solder and close your multiple open issues

**Comment by klahssik** [comment]
no :(

**Comment by klahssik** [comment]
im so irritated lol

**Comment by spannerman79** [comment]
Then close your multiple open issues @klahssik and follow https://technicpack.zendesk.com/hc/en-us/articles/204879815-How-To-Distribute-a-Modpack-Easy-Guide-for-Dummies

**Comment by klahssik** [comment]
ok

**Comment by klahssik** [comment]
same error didnt help at all nope same thing i even watched it twice

**Comment by klahssik** [comment]
help! lol

**Comment by bochen415** [comment]
@klahssik please stop spamming. Some people get a notification with your every post :/

**Comment by Misterio77** [comment]
As said previously, you're not an advanced user. I don't want to be rude but you should try creating modpacks the old way.
Please close your opened issues, as @bochen415 said we get notifications with all your spam.
