### ISSUE TITLE
Solder CSS And Api Question

### ISSUE THREAD

**Issue by FiberSprite** [TechnicPack/TechnicSolder#425]
When i login to solder on the web page i get "Error in exception handler." on a white screen thats it. the logo doesnt load or anything on the login screen either. Someone please help?

**Comment by spannerman79** [comment]
http://docs.solder.io/docs/faq-frequently-asked-questions

**Comment by FiberSprite** [comment]
Okay, what permissions would i set on ubuntu? and also where is the api folder for linking it to the technic platform

**Comment by spannerman79** [comment]
Did you at all read the documentation located at http://docs.solder.io/docs/getting-started ?
Specifically being;

>**This application is intended for experienced system administrators**

In other words, an experienced system administrator would know *exactly* what user and group to chown without asking.

**Comment by FiberSprite** [comment]
i have it working just do not know where to find the api folder at because their isnt one.
