### ISSUE TITLE
Cannot import from my solder installation.

### ISSUE THREAD

**Issue by zhivotnoya** [TechnicPack/TechnicSolder#429]
I've managed to get my mods properly uploaded to my server, properly named, put in their proper places.  I even have the modpack configured with the beforehand mentioned mods.  Now comes the tricky part.  I've searched the technicpack site to make sure there's no other modpack with my chosen name.  I then create a new modpack, click the "import from solder" tab, enter the information, even select my modpack in the dropdown box, click the appropriate boxes, read the disclaimer.  

Here's the tricky part.  I then hit the "import modpack" button and it tells me "You must enter a Modpack Name."  Ok.  I then go back to solder to make sure I'm not a moron and forgot the name.  Nope.  It's there in all of it's glory.

So, either I'm missing something, or the site just doesn't like me.  Any thoughts?

EDIT:  I just renamed the pack, to see if that would help.  Still a no go.  So it can't be a conflict of name as it's still giving me the same error.

**Comment by zhivotnoya** [comment]
Ok.  So apparently I had a config option wrong.  You could technically see the pack, but it was having issues parsing files--or something because I forgot the trailing slash in the config.  Derp!  

Thanks for the awesome platform.

**Comment by skwerlman** [comment]
I had a similar issue not long ago. Really, there just needs to be a more
descriptive error message on the platform.

**Comment by spannerman79** [comment]
Err it does @skwerlman https://github.com/TechnicPack/TechnicSolder/blob/master/app/config-sample/solder.php#L7

Not sure how much more detailed you want even in the config file your even told so

**Comment by skwerlman** [comment]
The error produced can be caused by several conditions. A comment in the
config doesn't fix that. I specifically said 'on the platform' because I
received the same error text for a totally different reason. (In my case,
it was because I hadn't published any builds)

What's needed is to differentiate between various errors instead of
producing an error message which makes no sense.

**Comment by GenPage** [comment]
Yeah this isn't really a Solder issue, as its highlighted in the GUI to include a trailing slash in your configs. 

Its more on the Platform on how to parse the response and properly display errors if the response from Solder is invalid. (No builds, no recommended, etc)
