### ISSUE TITLE
Tables look bad on mobile

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/TechnicSolder#430]
Tables should have horizontal scrollbars rather than simply running off the screen
![tmp_24075-screenshot_2015-08-07-16-04-55944647236](https://cloud.githubusercontent.com/assets/6954107/9144921/69180fa0-3d1e-11e5-81d0-02566c62592f.png)

**Comment by GenPage** [comment]
Can you provide your mobile device and browser, for future testing purposes?

**Comment by skwerlman** [comment]
Phone: Nexus 6
OS: CyanogenMod 12.1 Nightly 0805
Browser: Firefox 39.0

**Comment by GenPage** [comment]
Thank you

**Comment by skwerlman** [comment]
Should this be closed now that #430 is in?

**Comment by skwerlman** [comment]
This is still an issue in 7.3.1, but it now only affects the "recently added mod versions" table (on the main page, at least)

Phone: Nexus 6
OS: CyanogenMod 13.0 Nightly 1207
Browser: Firefox 42.0.2
