### ISSUE TITLE
"Client error response [status code] 404 [reason phrase] Not Found [url] " when trying to Configure Solder with technic

### ISSUE THREAD

**Issue by Seshpenguin** [TechnicPack/TechnicSolder#432]
I have TechnicSolder install on Ubuntu using Apache2 as the webserver, and I am able to login to Solder dashboard and whatnot, but I am not able to configure it work on Technic's side.
Can someone help?

**Comment by GenPage** [comment]
You need to provide more details bout your issue. Specifically the Technic Solder URL

**Comment by Seshpenguin** [comment]
Issue Fixed, Issue was incorrect configuration for Virtual Hosts.
