### ISSUE TITLE
I'm making a Windows Installer

### ISSUE THREAD

**Issue by GabrielTK** [TechnicPack/TechnicSolder#434]
Hi!
I'm making a windows installer. I've used it to install in a VM, and it worked! I think I will provide windows support if I can.

**Comment by MuhsinunCool** [comment]
Woah! Mind if i get a copy?

**Comment by GeARCraft1** [comment]
Now i'm having some problems on the URL generation (HTTP:\/172.5...\/mods\/...) with the slashes.
Do anyone knows what file generates the URLs???

**Comment by Indemnity83** [comment]
The URL is generated on the fly when needed in multiple locations, but I think the one you're looking for is probably in the mod view.blade.php. 

Out of curiosity, what is the goal/purpose of your installer? Getting Laravel to run in Windows isn't difficult (particularly if you use a something like [XAMPP](https://www.apachefriends.org/index.html) or [Bitnami's WAMP](https://bitnami.com/stack/wamp)), and although I haven't tested it assuming you meet the required dependencies there's no reason TechnicSolder should have any problems running in windows. 

Seems to me that all that *should* be needed is a documentation update, not necessarily a whole installer but maybe I've missed something.

**Comment by Indemnity83** [comment]
Also, check out [Laragon](http://laragon.org/) (good guide [here](https://innopy.wordpress.com/2015/02/07/laravel-windows/))

**Comment by GeARCraft1** [comment]
The installer I've made works with IIS 8, and maybe this is the problem.

**Comment by Pyker** [comment]
Solder on Windows is officially unsupported, so I'm closing this.
