### ISSUE TITLE
Error 500 after installing and configuring a fresh copy

### ISSUE THREAD

**Issue by Lapito** [TechnicPack/TechnicSolder#436]
Hello. I installed a fresh copy of solder, configured it and migrated it. But when I try to acess it on my browser I get a 500 error with no infomation about what happened. What can I do?

**Comment by GenPage** [comment]
Check out: http://docs.solder.io/docs/faq-frequently-asked-questions

I highly recommend turning on "debug" in your app.php config file.

**Comment by Pyker** [comment]
Closing this since it's likely no longer a problem. Feel free to reopen if it's still a problem.
