### ISSUE TITLE
Error while submitting image.

### ISSUE THREAD

**Issue by GabrielTK** [TechnicPack/TechnicSolder#443]
Hi Again!
Now i've reached na error while trying to upload an image. error:

Intervention \ Image \ Exception \ NotReadableException 
Open: C:\Users\Administrator.NATAL\Desktop\TechnicSolder\TechnicSolder\vendor\intervention\image\src\Intervention\Image\AbstractDecoder.php  
287.            case $this->isDataUrl():
288.                return $this->initFromBinary($this->decodeDataUrl($this->data));
289. 
290.            case $this->isBase64():
291.                return $this->initFromBinary(base64_decode($this->data));
292. 
293.            default:
294.                throw new Exception\NotReadableException("Image source not readable");
295.        }
296.    }

**Comment by Indemnity83** [comment]
Couple things to check right off the bat:

1. Does the /public/resources folder exist?
1. Does IIS have write permission to the public/resource folder?
1. Does the temporary upload path defined in php.ini exist?
1. Does the temporary upload path defined in php.ini have IIS_IUSRS permission?

**Comment by Indemnity83** [comment]
Another thing that might be helpful is to turn on debug mode in /app/config/app.php (set 'debug' => true). and copy/paste the whole stack trace into a [gist](https://gist.github.com/), and link it here.

**Comment by GeARCraft1** [comment]
I think the problem is with the permissions in the temp folder. I will try.

**Comment by GeARCraft1** [comment]
Thank you very much

**Comment by skwerlman** [comment]
Can this be closed?
