### ISSUE TITLE
'Rec' and 'Latest' radios don't update across pages

### ISSUE THREAD

**Issue by Indemnity83** [TechnicPack/TechnicSolder#448]
Have two pages of modpack builds, with the recommended or latest build radio enabled on the second page. Update the radio on any of the first page modpacks, the success message is displayed and the db is in fact updated. However, if you move to the second page, the radio option will not have been cleared yet. 

This is a visual glitch only

**Comment by Isigiel** [comment]
If you have two tabs showing the same page and only one updateing the radios that is alright, the page  only gets updated upon refresh.

**Comment by Pyker** [comment]
Not really a visual glitch, it's just how it works. The pages are rendered server-side, so the frontend wouldn't update across pages.
