### ISSUE TITLE
Ability to delete default admin user

### ISSUE THREAD

**Issue by Grinch** [TechnicPack/TechnicSolder#454]
I don't really care for leaving default credential accounts on my server (even with a different password). It's harder for someone to guess a password when they have to guess the username/email as well. :)

Shouldn't be too hard, just make sure there is another super-user when deleting any account to ensure access isn't lost.

**Comment by spannerman79** [comment]
What I usually do is edit the username as well as the email address under User Management to something else - in essence a "Super User"

**Comment by GenPage** [comment]
The check will be changed so that it no longer checks for a particular user id and instead checks that count of super users > 1.

**Comment by EntranceJew** [comment]
I'm was working on this now, doing what @GenPage suggested.

Currently, this creates a handful of bugs in views where we attempt to get user information from a user that no longer exists. Fortunately this happens in few places and is easy to correct.

Additionally, tests specifically request user(1) so those will also need to be modified. Should there be a system user or should it just request the first user it can find?
