### ISSUE TITLE
"Trying to get property of non-object" on /mod/list page.

### ISSUE THREAD

**Issue by Neodark7** [TechnicPack/TechnicSolder#460]
Hi when i go to the modlist page i get this error "Trying to get property of non-object (View: /home/neodark7/www/solder/app/views/mod/list.blade.php)"
i just finished adding all the mods in solder, all the other pages are working fine, i've already chmod 777 -R on the whole solder folder i don't know what i can do to fix it...
i'm using dev 0.7.2.2

**Comment by EntranceJew** [comment]
This is caused 'cause [I checked if the collection object was empty](https://github.com/TechnicPack/TechnicSolder/blob/6e7843077977ad6f1536fcd56ecf3978c7816b50/app/views/mod/list.blade.php#L50) instead of using the collection method for it. Fixed in #461.

**Comment by Neodark7** [comment]
so i just "git pull" right ?

**Comment by Neodark7** [comment]
Thanks man !
