### ISSUE TITLE
 Call to undefined function Illuminate\Support\ctype_lower()

### ISSUE THREAD

**Issue by giogimic** [TechnicPack/TechnicSolder#464]
Not sure what happened last night at some point solder apparently stop working i wasn't on at the time and i came back to this " Call to undefined function Illuminate\Support\ctype_lower()"

**Comment by GenPage** [comment]
Can you provide any log or stacktrace?

**Comment by giogimic** [comment]
Sorry meant to close this found out the issue after and it wasn't anything to actually do with solder.
