### ISSUE TITLE
Incremental Downloads

### ISSUE THREAD

**Issue by Redlotus99** [TechnicPack/TechnicSolder#468]
I can't seem to get Solder to do incremental downloads. I don't see any documentation on how to make this happen. Can someone explain to me how to make this happen?

**Comment by Isigiel** [comment]
Could you please specify your idea of incremental downloads?

**Comment by Redlotus99** [comment]
I have read that instead of downloading the whole pack every time I read you could just download the changed/updated mods and not the entire pack is this possible

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Sat, Sep 26, 2015 at 1:58 PM -0700, "Isigiel" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please specify your idea of incremental downloads?

-

**Comment by EntranceJew** [comment]
@Redlotus99 This is the default behavior provided by solder when using the Technic Launcher.

**Comment by spannerman79** [comment]
Did you read the documentation over at solder.io?  

Do you have a solder setup? Do you have your required zip files with the internal structure as stated in the documentation ?

**Comment by Redlotus99** [comment]
Yea I have solder working fine with technic and I read the documentation but if I create a new build ppl have to download the full pack, but I assume if I keep the build number and just update a mod that should be an incremental change,  I'd that correct?

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Sat, Sep 26, 2015 at 2:55 PM -0700, "Spanner_Man" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you read the documentation over at solder.io?

Do you have a solder setup? Do you have your required zip files with the internal structure as stated in the documentation ?

-

**Comment by disconsented** [comment]
You need to use a different build number for each new build. Then the launcher will only download what has changed

**Comment by spannerman79** [comment]
On a side note, you need to look at your Outlook app to quote original messages inline when you reply to github emails @Redlotus99 or use [github via mobile web browser](https://github.com/blog/1559-github-s-on-your-phone)

**Comment by Redlotus99** [comment]
Will do.
