### ISSUE TITLE
Minecraft Version Keeps Reverting to 1.0

### ISSUE THREAD

**Issue by J-Lowe** [TechnicPack/TechnicSolder#474]
I updated to the latest version of Solder today, and when trying to create a new build for my modpack, I noticed that the MC version kept reverting to 1.0, even when setting it to 1.7.10 (and any other version).

![editscreen](https://cloud.githubusercontent.com/assets/4039694/10288233/98de32da-6b65-11e5-875a-fe519f9494bc.png)
Here I have selected MC version 1.7.10

![managementscreen](https://cloud.githubusercontent.com/assets/4039694/10288234/9bca5104-6b65-11e5-92b8-b3a19467a6bd.png)
And here is the screen after I hit update build.  Notice the Minecraft Version: 1.

**Comment by J-Lowe** [comment]
It appears to be fixed in commit d75a54b.

**Comment by GenPage** [comment]
@J-Lowe That is correct, it is fixed in dev branch currently
