### ISSUE TITLE
Hash value vanishes

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/TechnicSolder#479]
When rehashing a mod version that is not first in the list, the hash value fades out, but does not fade back in.

I am using Google Chrome 45.0.2454.101 m 
My server is behind CloudFlare, if that helps at all.

**Comment by Andreas-Halemba** [comment]
i have the same problem. 

but i get a error "Error: Missing Post Data"

and all my mods do have the same hash. 

i had a look inside the code. and it is trying to call /mod/rehash/ via ajax. but there is no view for this url.

i did enter the hash when i created the modversion.

**Comment by GenPage** [comment]
@Andreas-Halemba Your issue is fixed in dev and will be push released soon. CloudFlare redirecting without the POST data fucks things up

@skwerlman What message do you get when you rehash?

**Comment by skwerlman** [comment]
"MD5 hashing complete."

Just realized I forgot to mention this, but refreshing the page shows the hash again.

**Comment by skwerlman** [comment]
Screenshots of the issue:

![solderbug-1](https://cloud.githubusercontent.com/assets/6954107/10422345/f706c31a-7086-11e5-8884-175f3f056e08.png)
![solderbug-2](https://cloud.githubusercontent.com/assets/6954107/10422346/f707486c-7086-11e5-8e23-3cafec31246c.png)

**Comment by GenPage** [comment]
@skwerlman Sorry for the delay! Can I get more info about the individual rehash request? I need info/screenshots from Chrome Dev Tools, specifically the Network tab, with the individual rehash request selected. I can details steps to do so if needed. Thanks!

**Comment by skwerlman** [comment]
Looking at the response, it looks like I'm getting the hash for the first mod listed rather than for the mod I'm rehashing.

I'll test again with developer mode enabled on cloudflare to see if that's the issue.

**Comment by GenPage** [comment]
interesting, can you dump an output of the html code of that page then?

**Comment by skwerlman** [comment]
https://github.com/skwerlman/solder-page-dump

**Comment by skwerlman** [comment]
any progress on this? anything else i can provide to help out?

**Comment by GenPage** [comment]
@skwerlman Apologies for the delays. IRL work has affected my workflow. I will be revisiting this.

**Comment by Pyker** [comment]
> Looking at the response, it looks like I'm getting the hash for the first mod listed rather than for the mod I'm rehashing.

Same problem as https://github.com/TechnicPack/TechnicSolder/issues/545, closing this one as duplicate.
