### ISSUE TITLE
.htaccess rewrite to wrong url

### ISSUE THREAD

**Issue by CrazyCodeUK** [TechnicPack/TechnicSolder#481]
if sodler is put as a subfolder of the host eg http://hostname.tld/solder/
when trying to access hostname.tld/solder/api/ you get redirect to hostname.tld/api

RewriteRule ^(.*)/$ /$1 [L,R=301]

rewrites the url incorrectly and is not needed in the .htaccess file as solder/api/ works for interaction with the technic platform.

I have tested this with a now fully function solder installation.

**Comment by GenPage** [comment]
Solder is not intended to be setup as a subfolder of a host, but rather a subdomain with its own virtual host.
