### ISSUE TITLE
Technic Solder option for Digital Ocean

### ISSUE THREAD

**Issue by TheDoctorsLife** [TechnicPack/TechnicSolder#482]
Before I go much farther I think this would definitely be further down the lane, eg v1.0. I'd also like to point out that this might seem like Technic supports Digital Ocean in some forum.

Onto the meets, for unrelated reasons I was patrolling the Digital Ocean uservoice forums, and I happened to find this https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/10132773-technic-solder-preinstall. Potential problems I see with this are updating, and inexperienced users asking for help with problems they have with Technic solder because they have no idea how to use Linux.

I would like to see this, but I think it should be further down the line.

**Comment by sct** [comment]
With the massive Solder updates coming down the line setting up Solder will be easier than ever. We will also have Docker support as well so if you want to go that route you could just set up a docker droplet on Digital Ocean and load the image.

**Comment by TheDoctorsLife** [comment]
That also sounds cool, & with above, I was trying to accommodate possible comments in relation to that.
