### ISSUE TITLE
Private/hidden packs/builds showing without authentication

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/TechnicSolder#483]
When making an unauthenticated API request to `/api/modpack`, hidden packs are not shown. However, if you make a request to `/api/modpack/hidden-modpack-name`, the API gives you details about the pack, even if you shouldn't have access.

Similarly, when you request `/api/modpack/public-pack-name`, unpublished and private builds are not shown. However, if you request `/api/modpack/public-pack-name/hidden-or-unpublished-build`, the API again lists full details about that build, even though you shouldn't be able to see it.

Additionally, both the recommended and latest builds are shown to unauthenticated users, even if both builds are private or unpublished.

For an example, look at these:
http://solder.tetrarch.co/api/modpack/cc-testbed/ (a hidden pack)
http://solder.tetrarch.co/api/modpack/cc-testbed/0.0.0.4 (a private build)
http://solder.tetrarch.co/api/modpack/cc-testbed/0.0.0.2 (an unpublished and private build)

**Comment by sct** [comment]
This is working as intended.
