### ISSUE TITLE
External URL fails to update with config

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/TechnicSolder#484]
I recently moved my solder install to a new external URL, but despite changing the URL in the config, it still points to the old URL when referencing uploaded pack resources that have not been replaced since before the URL change.

**Comment by sct** [comment]
URLs are generated on the fly so this shouldn't be happening. You changed the mirror URL right? Could it be caching the responses? Have you checked after some time has passed?

**Comment by skwerlman** [comment]
I updated the URL in the config ~3 months ago, but didn't realize they hadn't updated until now. I've cleared both my browser and CF cache, and neither fixed it. Is there a cache used by the solder install that I can clear?

Link to API call with bad URL: http://solder.tetrarch.co/api/modpack/cc-testbed/
Link to API call with correct URL: http://solder.tetrarch.co/api/modpack/minetek/

**Comment by GenPage** [comment]
This is a bug, it should be handled differently in the API controller. PR incoming soon(tm).

**Comment by GenPage** [comment]
@skwerlman Actually I was wrong, this is intended. The full urls are stored in the DB for pack resources because some people use external hosting for the images. Since the full urls are stored, they won't change with the config. I'm open to suggestions on how to better handle this.

**Comment by TheDoctorsLife** [comment]
Maybe check the config for changes when a user runs `php artisan migrate` then write the changed url to the DB?

**Comment by skwerlman** [comment]
What if pictures uploaded through the UI had partial paths saved in the DB, and then when pulling the picture location later, add the current scheme+hostname if the entry isn't a full URL (i.e. doesn't match `r"^https?://"`).

**Comment by Pyker** [comment]
Closing this issue since modpack art isn't handled in Solder anymore
