### ISSUE TITLE
Stuck with this after running it on Apache.

### ISSUE THREAD

**Issue by ThaVenom23** [TechnicPack/TechnicSolder#490]
Fatal error: require(): Failed opening required 'C:\xampp\htdocs\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\bootstrap\autoload.php on line 17

**Comment by EntranceJew** [comment]
Did you do composer install?

**Comment by TheDoctorsLife** [comment]
That looks like windows file paths, going to note that windows installs are NOT officially supported. (Although still possible)

**Comment by LeviTheOtaku** [comment]
I also get the same errorr. Please help us.

**Comment by GenPage** [comment]
Most likely either a permissions issues or composer was not run properly.

**Comment by Pyker** [comment]
Missing `composer install`.
