### ISSUE TITLE
[Enhancement] Script to migrate from sqlite to MySQL

### ISSUE THREAD

**Issue by spannerman79** [TechnicPack/TechnicSolder#495]
For those that by mistake (like myself) or for others that wish to move away from sqlite to MySQL could there be a script - either php or otherwise that could be performed on `php artisan migrate`?

This would be useful as (for example) I have several modpacks and several mods with all their individual information added into the flatfile db (sqlite)

**Comment by skwerlman** [comment]
http://stackoverflow.com/a/1067365 may help, if this is still an issue for you

**Comment by GenPage** [comment]
@spannerman79 Might be an good idea, but it would be buried in the IceBox for a while. I would recommend @skwerlman's route of thinking.
