### ISSUE TITLE
Remote MD5 failed

### ISSUE THREAD

**Issue by Ionaru** [TechnicPack/TechnicSolder#498]
I updated to the latest Solder version (v0.7.3.0) and now I get this error when trying to add or rehash a mod.

"Error: Remote MD5 failed. C:/wamp/www/solder/repo/mods/agricraft/agricraft-1.7.10_1.4.5.zip is not a valid URL."

The file does exist in that location.
Everything worked fine on the previous version I used (v0.7.2.1) and I didn't change any settings.
The update to v0.7.3.0 was successful and I did the database migrate.

**Comment by GenPage** [comment]
Can you check the error logs located at "app/storage/logs" for any errors/warnings about that file?

**Comment by keptdream** [comment]
Same problem here
my app/storage/logs

is just repeating 
[2015-12-06 11:08:58] production.ERROR: /var/www/TechnicSolder/public/modpack/mods/forge/forge-11.14.4.1577.zip is not a valid URI [] []
with different time obviously

this path is correct, and file exists. 

i'm using nginx + php-fpm
all permissions are set corectly (worked with earlier versions)

I'm also having another issue

File sizes in "file list in the library" are showing always 0.00MB

i'm using CentOS 7 with php 5.4

**Comment by keptdream** [comment]
Found the problem

app/controllers/ModController.php 
Showing the top match. Last indexed 12 hours ago.

305			if(filter_var($URI, FILTER_VALIDATE_URL)) {
306				if (file_exists($URI)) {
307					Log::info('Found \'' . $URI . '\'');

This checks only for remote repositories. I have changed my repo_location to http://solder... one(over internet (not local one) and it worked

I think this code should first check if it's local repository or remote... or something like this.... maybe that would help:D i might also be wrong

I'll leave this as "remote" repository for now until it's fixed

**Comment by GenPage** [comment]
I swore I tested this successfully....son of a gun :angry: 

Hot fix inbound later today.

**Comment by Ionaru** [comment]
Thank you guys for looking into this so quickly. :+1:

**Comment by GenPage** [comment]
No problem, thank you for the quick report!

**Comment by xxAtrain223** [comment]
Is it safe to update to 471f43f?

**Comment by leonh-au** [comment]
@xxAtrain223 No. The issue is still present in the as of 2 hours ago.

**Comment by GenPage** [comment]
@leonh-au @xxAtrain223 Apologies but, it was my call on not saying anything. The issue does not break MD5 hashing completely, just local hashing.

The hotfix the being actively work now and should be released soon.
