### ISSUE TITLE
Launcher not reading from Solder

### ISSUE THREAD

**Issue by falconraptor** [TechnicPack/TechnicSolder#500]
My modpack was linked to solder and worked fine but I moved solder from one server to another with the same url and now it is trying to install from a zip not solder. The modpack name is TechRaptorServer.

**Comment by spannerman79** [comment]
Logs? More details needed. Detailed in a way that can be followed step by step just from a print out so to speak

**Comment by falconraptor** [comment]
Moved Solder from one web server at http://techraptor.us to a different one with the same domain (http://techraptor.us). If you try to install to install the pack it says "failed to unzip modpack. modpack not found". But before I moved web servers the modpack was installing correctly.

**Comment by spannerman79** [comment]
As you didn't outline how you moved hosts I am going to assume you are using shared hosting.

While some users have reported they have been able to get their setup working on shared hosting it is not officially supported.

As you gave no logs as was requested helping is going to be an issue if you are unable to provide the information that is requested.

What you gave was just as informative as someone saying "Oh my windows broke and won't start"

**Comment by falconraptor** [comment]
There is no logs. The server I moved from was a cloud VPS to a dedicated server. Solder works and the website is loading all the api stuff correctly but the launcher is not.

**Comment by falconraptor** [comment]
techraptor.us/solder/public/api redirects to techraptor.us/api. I forgot I need to set solder up with a subdomain solder.techraptor.us
