### ISSUE TITLE
Deleting a mod version from /mod/view/<id> will result in a notification that says "error: Not Found"

### ISSUE THREAD

**Issue by FNCxPro** [TechnicPack/TechnicSolder#503]
As the title says, when deleting a mod version from /mod/view/<id> will show a notification that says "error: Not Found"
To reproduce, delete a mod version from the mod view page then watch the top right corner.
![Reproduction Steps](https://i.gyazo.com/0f649aaddf159ae104369c005d23f073.gif)

**Comment by Tomson124** [comment]
Same problem here :/

**Comment by socialretard** [comment]
Here is the error message I receive from the log.

[2015-12-21 23:53:29] production.WARNING: File '[link]' was not found. [] []

**Comment by sjennison** [comment]
I found the source of the issue - it's in `app/views/mod/view.blade.php` on line 201.

I've submitted a pull request to fix it, alternatively you can just modify that file on your install and do what I did to fix it in the PR

**Comment by JamiePhonic** [comment]
This doesn't seem to work for me. My server still logs 404's when i try to delete a mod even after applying your tweak. Do i need to be on the dev branch for this to work?

**Comment by SyriusTank** [comment]
This fix worked for me. +1

**Comment by GenPage** [comment]
Fixed in #552
