### ISSUE TITLE
only 5 modpacks on the launcher

### ISSUE THREAD

**Issue by heartofstone63** [TechnicPack/TechnicSolder#508]
Hi I have a problem I just downloaded the technic launcher, I loaded it up then clicked on modpacks and I only had :
attack of the b-team
blightfall
hexxit
vanilla
and tekkit legends.
how do I get more modpacks.

**Comment by Razorskills** [comment]
First off.. This is a repository for Technic Solder.. it is server software. So wrong place to be asking questions that you could probably google.

Here, click this link: http://lmgtfy.com/?q=how+to+use+technic+launcher

**Comment by ike709** [comment]
Here's the URL for the main Tekkit modpack, just paste it into the launcher's modpack searchbar.
http://api.technicpack.net/modpack/tekkitmain
