### ISSUE TITLE
cant open any modpacks not even standard ones

### ISSUE THREAD

**Issue by Fearless96** [TechnicPack/TechnicSolder#509]
i cant open any modpacks not even standard ones i have played a lot of tekkit classic but if i press play the loading line starts and when its a 100% it just dissapears and nothing happens what is cousing this?? please help me 
(sorry for bad english but i'm dutch)

**Comment by skwerlman** [comment]
This is a repo for TechnicSolder, which is not the client. You'd probably be better off asking for help here:

http://technicpack.net/help
