### ISSUE TITLE
Rehash creates internal error

### ISSUE THREAD

**Issue by falconraptor** [TechnicPack/TechnicSolder#511]
my solder is saying: production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 33554432 bytes exhausted (tried to allocate 14936506 bytes)' when I try to rehash botania version: 1.7.10-r1.8-243.

**Comment by GenPage** [comment]
The issue is that your PHP install has a memory limit. You will need to up the limit to hash big mod zips. The default limit is usually 64MB.

https://www.digitalocean.com/community/questions/how-do-i-increase-php-memory-limit-on-ubuntu-14-04
