### ISSUE TITLE
Cannot run any installed modpacks

### ISSUE THREAD

**Issue by 14Hunter14** [TechnicPack/TechnicSolder#517]
Ive tried for the past 6 hours going through folders and i cant find out why technic launcher will not open my modpacks. when i click play it just opens and closed immediately, please help

**Comment by Lucianonafi** [comment]
Me too, at first i downloaded a modpack and it didn't work, but now EVERY. SINGLE. ONE wont work, as soon as it's done starting it up, nothing starts up, the launcher just closes and opens itself in a milisecond. no matter how many times i try it wont work.

**Comment by 14Hunter14** [comment]
Yea exactly I've even tried going through files to look for the problem and it won't work. I've tried everythjng

**Comment by 14Hunter14** [comment]
I when I opened this technic thing where it shows all these commands and stuff it said every time I tried to run a mod pack that version.json was missing from the modpack.jar file

**Comment by Lucianonafi** [comment]
mine doesn't even show anything, it just reopens instantly as soon as i try and start a modpack

**Comment by spannerman79** [comment]
This is for Solder, not the launcher. For the launcher go to http://www.technicpack.net/help
