### ISSUE TITLE
Launching Any Modpack

### ISSUE THREAD

**Issue by Masterdiger** [TechnicPack/TechnicSolder#519]
Hello, for the last few months whenever I launch a mudpack on both of my two computers the launcher stops disappears and then comes right back it has kept happening and though eventually it was a common issue that a patch would be sent out and fix. Sadly nothing I have found anywhere has helped and I was hoping someone would be able to help me find a solution. Thank You for anything you can find or help me do to fix this problem.

This is what pops up : [
B#339]  Error occurred during initialization of VM
[B#339]  Could not reserve enough space for object heap
[B#339] Analytics Response [runModpack]: 200
[B#339] Starting download of http://cdn.technicpack.net/platform2/pack-icons/2607.png?1436527764, with 3 tries remaining

**Comment by Razorskills** [comment]
Unless this is an issue with a solder pack, then this is a launcher issue and your in the incorrect repository.

**Comment by Masterdiger** [comment]
What does that mean?

**Comment by spannerman79** [comment]
This is for Solder, not the launcher. For the launcher go to http://www.technicpack.net/help
