### ISSUE TITLE
A 500 error when adding a modpack build

### ISSUE THREAD

**Issue by RubenRME** [TechnicPack/TechnicSolder#522]
I hit a 500 error while trying to add a new build for a modpack
> "curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set"

General Information:
- Linux server, shared webhost
- Latest version of Solder

**Comment by RubenRME** [comment]
Fixed it by changing
```php
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
```
to
```php
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
```
in **UrlUtils.php**

**Comment by GenPage** [comment]
This happens when Solder is hosted on a shared/restricted PHP host. There are no plans currently to fix this at this time.

**Comment by RubenRME** [comment]
@GenPage Figured, doesn't really matter since most people won't host it on a shared host and there are no other things that stop working because of it. Only this which can easily be fixed.

**Comment by GenPage** [comment]
Right, its very minor. Thank you for the report tho
