### ISSUE TITLE
It says im offline

### ISSUE THREAD

**Issue by MohMoney** [TechnicPack/TechnicSolder#527]
When I get on technic it will let me get into the launcher I login and when I go to play any of my modpacks hexxit, pixelmon, walking dead, ext... it says I'm offline. I know I'm not offline because when I go to play actual minecraft it lets me play on servers. so I go onto the technic website to try to redownload it and it says theres a snag and I cant get into the technic download page but I could get onto the wiki. Is there something I can do to fix this?

**Comment by spannerman79** [comment]
This is for Solder, not the launcher. For the launcher go to http://www.technicpack.net/help

**Comment by MohMoney** [comment]
spannerman79 that's the problem I cant go on there it says theres a snag and wont let me do anything on the technic website

**Comment by spannerman79** [comment]
Again - you don't read.  If you read the README.md you would know that this is the GibHub for Solder, not to do with the launcher.

https://github.com/TechnicPack/TechnicSolder/blob/master/README.md

http://docs.solder.io/

**Comment by GenPage** [comment]
The issue is that Technic servers are down to Linode being DoS'd. Please monitor twitter for updates. http://www.twitter.com/technicpack
