### ISSUE TITLE
Unable to open modpacks?

### ISSUE THREAD

**Issue by JTElizabeth6400** [TechnicPack/TechnicSolder#528]
Hi, I searched all over the web, and I can't seem to find some type of within-2015/2016 answer to my issue. Just a few weeks ago, my launcher and all packs were working perfectly. Now, I can download packs, but when I click play/launch, the bar at the bottom of the launcher loads up, then the launcher closes out and reopens immediately. So in short, no packs will launch. 

Sidenote: I have tried reinstalling/updating Java
Also tried deleting TechnicLauncher, restarting computer, then reinstalling launcher

Nothing seems to work.
Thank you so much

**Comment by Razorskills** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher
