### ISSUE TITLE
Modpack Corrupt

### ISSUE THREAD

**Issue by CrafterSB** [TechnicPack/TechnicSolder#530]
Whenever I try to install or play one of my modpacks it says "ModPack is either corrupt or not installed and is not available for offline play". I do not know how to fix this issue but the computer Im using is a Mac Book.  Also when I try to search for other mod packs it only shows up the ones I already have. It fails to open up nay modpacks. 
I will appreciate your help.

**Comment by spannerman79** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher

**Comment by CrafterSB** [comment]
Do you know how I could fix this I do not know a lot about technic.

**Comment by spannerman79** [comment]
Re read what I have already commended.

This is **not** the issue tracker for the launcher.

I gave the two links that you needed to look at - **NOT HERE**

**Comment by CrafterSB** [comment]
I'm sorry but I'm really new and i don't know how these links are meant to help me I did make a support forum

**Comment by skwerlman** [comment]
close this issue and reopen it here: https://github.com/TechnicPack/TechnicLauncher/issues
