### ISSUE TITLE
Failed Initialization of the pack

### ISSUE THREAD

**Issue by KazTheDuelist** [TechnicPack/TechnicSolder#531]
Whenever I try to open a solderpack or any other for that matter, it will show its usual opening and closes the launcher/hides it (the setting I have it on), then reappears with no mine craft. Any Ideas how to fix this issue?

**Comment by Lucianonafi** [comment]
me too bud, it's a shame, i felt like coming back to playing after a long while, but it wont work!

**Comment by spannerman79** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher

**Comment by KazTheDuelist** [comment]
spanner both of these cites didnt offer help from what was instructed

**Comment by spannerman79** [comment]
> spanner both of these cites didnt offer help from what was instructed

It doesn't matter.  Its like i would expect help to (example) understand French from someone that doesn't speak nor write french - the same applies to this issue tracker.

You were told @KazTheDuelist of what this issue tracker is for. Hence why this issue is now closed.
