### ISSUE TITLE
Copying OSX Native 0%

### ISSUE THREAD

**Issue by Wazzie** [TechnicPack/TechnicSolder#532]
I got a mac and when I'm trying to start a mod called ez pixelmon it is loading everything except (Copying OSX Native) .. i've been waiting for 3 hours and nothing is happening..

PS. I tried to Delete and reinstall TechicLauncher..

Hope you can help me :D

**Comment by spannerman79** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher
