### ISSUE TITLE
No Modpacks Starting up

### ISSUE THREAD

**Issue by Lucianonafi** [TechnicPack/TechnicSolder#533]
So, i click "play", the bar on the launcher loads, and when the minecraft screen is supposedly going to pop up it doesn't. no loading no nothing, it just closes the launcher for a milisecond and reopens it instantly

**Comment by spannerman79** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher
