### ISSUE TITLE
linking the mod to the repository (MD5)

### ISSUE THREAD

**Issue by SunNetwork** [TechnicPack/TechnicSolder#536]
When I'm trying to link the mod the the repository in the step of adding a version I get an error... A simple URL error. Well that doesn't sound like a bug first but when I tried to download it from the download URL which is provided for testing purposes(or at least I think it is) the folder downloaded smoothly like it should without any problems. Again spamming the add button and still getting the missing URL. That looks like that and after a while I saw something which I'm pretty sure is causing this and is a bug. If you look closer at the picture it says in the error message: 
Error: Remote MD5 failed. /var/www/html/soldermods/waila/waila-1.2.2.zip is not a valid URI
Now what I noticed a slash is missing between the solder and mods and I'm not aware of a fix on the client side if anyone knows how to fix this I would appreciate your help.
![bildschirmfoto 2016-01-09 um 07 49 26](https://cloud.githubusercontent.com/assets/16620181/12214878/9899deba-b6a5-11e5-9ac4-8c93226aaecd.png)

**Comment by skwerlman** [comment]
What is the `repo_location` in `app/config/solder.php` set to?

**Comment by SunNetwork** [comment]
I have it set to: /var/www/html/solder but adding a / at the end wont help it then it causes an internal server error.

**Comment by spannerman79** [comment]
> I have it set to: /var/www/html/solder

repo needs to be seperate to actual solder install.

Re read the actual docs http://docs.solder.io/

non-solder issue @GenPage

**Comment by SunNetwork** [comment]
I'm well aware that the repo needn't to be in the TechnicSolder folder but my repo location is called solder...I don't think me naming the repo folder how I like should be a problem. 

Also if this is a non-solder problem then please tell me @spannerman79  why can I click on the download URL you see in the pic and it downloads it but can't add it cause then it either gives me the issue you see the or with a / at the end of the absolute path an internal server error.

**Comment by skwerlman** [comment]
You can download it successfully because there is nothing wrong with your  `mirror_url`

`repo_location` MUST end in a `/`

**Comment by SunNetwork** [comment]
I thought you're right but when I add the / I get an internal server error which doesn't make any sense to me.

**Comment by nathreed** [comment]
I'm getting this error as well. I can't seem to find any details being logged anywhere. From browsing the issues here, I've seen a lot of people linking/quoting a log file that looks like a solder log file, but I can't seem to find this. Where should Solder be logging errors like this to? I'd like to see exactly what's causing the error.

**Comment by nathreed** [comment]
After finding my logs and checking them, I noticed that I am getting the same error as #523 describes. It has to do with a missing column in the database table and can apparently be fixed by adding the column manually.

**Comment by GenPage** [comment]
@SunNetwork To troubleshoot this further, we'll need the solder logs from `app/storage/logs`. Since this does not appear to be a technical issue, but a setup/cnonfiguraiton issue. I recommend taking it to: http://docs.solder.io/discuss

**Comment by SunNetwork** [comment]
I'm having the same error as nathreed described and was thanks to his issue description able to fix it. But I don't think the column is missing is a set up issue...since there is no part to set that up excepts to manually add the column .
