### ISSUE TITLE
Filesize of modversions all at 0.00 MB

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#537]
For some reason, all modversions are showing up as being 0.00 MB large.

<img width="1440" alt="screen shot 2016-01-09 at 5 33 14 pm" src="https://cloud.githubusercontent.com/assets/2921172/12218804/b6f884fe-b6f7-11e5-9855-e468ccff3590.png">

**Comment by GenPage** [comment]
Until you rehash the mods, these will be no data about the size since the Filesize feature is new.

**Comment by fcpwiz** [comment]
What exactly will rehashing do? @GenPage

**Comment by spannerman79** [comment]
I assume replacing the database fields to do with the md5 hash and also replace the null/0 value with the mod filesize.

**Comment by GenPage** [comment]
@fcpwiz Calculating the mods filesize is done in parallel with mod hashing, since the the file is grabbed completely. Its convenient to perform both operations at the same time.
