### ISSUE TITLE
URGENT: Trying to get property of non-object

### ISSUE THREAD

**Issue by fcpwiz** [TechnicPack/TechnicSolder#539]
This only occurs when I view the dashboard page.

<img width="1436" alt="screen shot 2016-01-10 at 3 33 03 pm" src="https://cloud.githubusercontent.com/assets/2921172/12223824/b529396c-b7af-11e5-9a38-573baefe0387.png">

ErrorException thrown with message "Trying to get property of non-object (View: /home/mannyrothman/public_html/TechnicSolder/app/views/dashboard/index.blade.php)"

Stacktrace:
#20 Illuminate\View\Engines\CompilerEngine:handleViewException in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#19 ErrorException in /home/mannyrothman/public_html/TechnicSolder/app/storage/views/7eb5698398ce52e3bfee217b849c35e9:81
#18 Illuminate\Exception\Handler:handleError in /home/mannyrothman/public_html/TechnicSolder/app/storage/views/7eb5698398ce52e3bfee217b849c35e9:81
#17 include in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#16 Illuminate\View\Engines\PhpEngine:evaluatePath in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#15 Illuminate\View\Engines\CompilerEngine:get in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/View.php:134
#14 Illuminate\View\View:getContents in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/View.php:102
#13 Illuminate\View\View:renderContents in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/View/View.php:76
#12 Illuminate\View\View:render in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Http/Response.php:43
#11 Illuminate\Http\Response:setContent in /home/mannyrothman/public_html/TechnicSolder/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:202
#10 Symfony\Component\HttpFoundation\Response:__construct in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1501
#9 Illuminate\Routing\Router:prepareResponse in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1036
#8 Illuminate\Routing\Router:dispatchToRoute in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#7 Illuminate\Routing\Router:dispatch in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#6 Illuminate\Foundation\Application:dispatch in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#5 Illuminate\Foundation\Application:handle in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /home/mannyrothman/public_html/TechnicSolder/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /home/mannyrothman/public_html/TechnicSolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /home/mannyrothman/public_html/TechnicSolder/public/index.php:49

**Comment by Razorskills** [comment]
have you tried doing any chmod or chown commands then restarting the server? Perhaps a file is "locked" I feel like I have had an issue like this before, and solved it by fixing my permissions.

Could always rule it out by trying the 777, but then changing it back afterwards. If it works. Then its a permission issue, if it don't, then its something else. But if you try that, make sure to change it back asap.

**Comment by fcpwiz** [comment]
@Razorskills The odd thing is that all I did was delete a modversion, refreshed the page, and saw this.
