### ISSUE TITLE
Rehashing not working as expected

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/TechnicSolder#545]
If you rehash any mod version, solder rehashes the topmost entry instead.

Before rehashing:

![](http://puu.sh/mzRGw/c7e33f632e.png)

After rehashing 0.3.1.33 (the second entry):
![](http://puu.sh/mzRT5/6c7332667b.png)

Possibly related to #479

**Comment by Isigiel** [comment]
Although I'm not really sure this solves the issue, https://github.com/TechnicPack/TechnicSolder/blob/master/app/controllers/ModController.php#L170-L190
THe above lines make me think, if a mod was to be rehashed and the original file changed, the rehash wouldn't work, but use the one supplied in the input field again.

**Comment by GenPage** [comment]
@Isigiel Ping me on discord to discuss this further.

**Comment by Isigiel** [comment]
I think, there should be the input field, filled with the current vaue, leaving the behaviour, if nothing is supplied
Next to the input, an update button, which will save the current value directly, and then an option to paste the current calculated md5 into the input
So it's very clear, whatever is in the field gets saved, but you have an option to use the _auto-hashing_

(Discord copy)

**Comment by Pyker** [comment]
This is fixed in https://github.com/TechnicPack/TechnicSolder/commit/37e8858e81e5ded50f791cd49c223b6d7c579969 (`feature/laravel-6` branch)
