### ISSUE TITLE
Let approved clients view unreleased versions of a public modpack

### ISSUE THREAD

**Issue by Kostronor** [TechnicPack/TechnicSolder#546]
In the modpack section, you can set a version to "not released". But only when setting the modpack private you can give selected clients access to unreleased versions.

The documentation is extremely unclear about what is what and means what.

People like me, who want to test their new version out with some friends before releasing it to the public seem to not be able to.

**Comment by skwerlman** [comment]
Not released simply means that it exists, but isn't available to anyone at all. Private means exactly that: only certain people can see it. To allow someone to see a private version, you should check the box next to their client in the 'Edit Modpack' view.

**Comment by Kostronor** [comment]
The boxes to view private versions only appear when the whole pack is set to private. That was my first thought. But setting the pack to private, checking the boxes and the setting it to public again does not work. It seems to forget/ignore the checked boxes.

**Comment by Kostronor** [comment]
It seems that when one version is private, a logout and login makes the boxes appear, seems to be a caching issue.
