### ISSUE TITLE
Stuck IN Ground

### ISSUE THREAD

**Issue by SubSilencer** [TechnicPack/TechnicSolder#548]
I got stuck in the ground in the safezone on US server 1. My buddy RibidKG also experianced this bug. We both tried to get into a vehicle in the safezone. On our screens we were NOT in the car. But on my other friends' we were IN the car. We both won't die as we r in the safezone. We have no way of getting out. Help admins?? Thank you! :)

**Comment by SunshineHunter** [comment]
What does TechnicSolder have to do with it?

**Comment by skwerlman** [comment]
You are in the wrong place, friend

**Comment by spannerman79** [comment]
This is the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher

**Comment by khionu** [comment]
Not to mention, this sounds like you need the *server admins*, who are not affiliated with Technic in any way, shape, or form, even if they do use the Launcher for their modpack.
