### ISSUE TITLE
Modpacks are not launching for me

### ISSUE THREAD

**Issue by DriftingTheater** [TechnicPack/TechnicSolder#558]
Pls fix it

**Comment by skwerlman** [comment]
... sigh

This is the Solder Repository and is not an issue tracker for the launcher. Also 'pls fix it' is not a good way to get someone to help you.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher

**Comment by ET-Bent** [comment]
@skwerlman such a polite answer to that.... :+1:

**Comment by skwerlman** [comment]
I, unfortunately, have had lots of practice.

**Comment by tankerkiller125** [comment]
@skwerlman Now only if the @DriftingTheater or a Technic Dev would close these issues...
