### ISSUE TITLE
SQLITE filesize column missing

### ISSUE THREAD

**Issue by Aaesos** [TechnicPack/TechnicSolder#559]
Since the addition of file sizes to Solder, the SQLITE default database was never modified to add support for this.

The main issue is that any server that installs any versions of Solder since the file size feature was added, and those that use SQLITE instead of an external database are unable to add any mods.

`[2016-02-27 06:32:53] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 table modversions has no column named filesize' in /home/aaesos/public_html_2/solder/TechnicSolder/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369`

You can manually add a filesize column to the database, or even easier, move to an external database.

**Comment by spannerman79** [comment]
Dupe #523

**Comment by Aaesos** [comment]
Then fix it. They reported it on December 28th. It's been almost two months. Adding a column to a table shouldn't be rocket science for the people who have made this complicated project.

**Comment by spannerman79** [comment]
Demanding something to be fixed that is offered freely isn't exactly the correct way to go about things.

> Adding a column to a table shouldn't be rocket science for the people who have made this complicated project.

Well create a fork and do a PR if its not rocket science.

**Comment by GenPage** [comment]
Closing since duplicate
