### ISSUE TITLE
"error: Not Found" when deleting modversion

### ISSUE THREAD

**Issue by leptun** [TechnicPack/TechnicSolder#564]
When i try to delete a modversion I get "error : not found" message.
You can delete modversion by deleting the mod itself and readding it to solder.
Hope you can fix this bug. I am using solder v0.7.3.1
![screenshot 2016-03-13 09 49 49](https://cloud.githubusercontent.com/assets/17808203/13727605/736d2294-e901-11e5-8c81-fd2f3b24a0fe.jpg)

**Comment by spannerman79** [comment]
Log files?

**Comment by leptun** [comment]
There isn't any error in the log file except for a bad filename that I had to fix
[solderlog-2016-03-13.txt](https://github.com/TechnicPack/TechnicSolder/files/170882/solderlog-2016-03-13.txt)

**Comment by leptun** [comment]
I've found this error in pull requests (wired location for an error)
https://github.com/TechnicPack/TechnicSolder/pull/552/files
