### ISSUE TITLE
Technic Website

### ISSUE THREAD

**Issue by benjisoft** [TechnicPack/TechnicSolder#565]
When adding solder server to the technic website. It is required to enter http:// prior to the URL. This is not stated anywhere.

**Comment by tankerkiller125** [comment]
The example URL on the technic site (the placeholder) does have http:// this should be enough of a hint for most people.

**Comment by skwerlman** [comment]
Also, this is the tracker for the solder software itself; platform support is handled here:

http://www.technicpack.net/help

**Comment by benjisoft** [comment]
@skwerlman Will post it there
