### ISSUE TITLE
S3 MD5 error

### ISSUE THREAD

**Issue by benjisoft** [TechnicPack/TechnicSolder#567]
When I try to add a new mod version I receive the error: `Error: Remote MD5 failed. mods/damage-indicators/damage-indicators-3.2.0.zip is not a valid URI`. I am running Solder on Ubuntu 14.04.4 and it is linked to an S3 bucket on AWS. I have also created and linked an IAM role (Policy "S3FullAccess" Included) to solder

**Comment by benjisoft** [comment]
When I click on  the download link on the solder panel it throws this message at me: 'Mod not found'

**Comment by skwerlman** [comment]
what do you have in `mirror_url` in app/config/solder.php?

**Comment by benjisoft** [comment]
`https://s3-eu-west-1.amazonaws.com/soldermods/stampys-lovely-modpack/`

**Comment by skwerlman** [comment]
ok; make sure that `repo_location` is set to the same thing.

**Comment by benjisoft** [comment]
It is

**Comment by benjisoft** [comment]
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/8136412/13892108/177c5086-ed4d-11e5-8e5b-6c473646eb03.png)

**Comment by GenPage** [comment]
@benjisoft What is the `repo_location` set to? It does not appear to be anything

**Comment by benjisoft** [comment]
I have given up on this.
