### ISSUE TITLE
Slow Pack syncing

### ISSUE THREAD

**Issue by Stokykyle** [TechnicPack/TechnicSolder#568]
I have just started using TechnicSolder i have linked my packs but new builds seem to take a long time to sync across to the client and technic pack website any ideas?

**Comment by skwerlman** [comment]
This is normal; updates can take up to one hour to propagate to the website.

Also, support for the website is handled here:

http://technicpack.net/help

**Comment by Stokykyle** [comment]
Sometimes they can take 3 hours to propogate

**Comment by skwerlman** [comment]
Well, nothing we can do for you here. As I said, support for the website is handled elsewhere. A 3hr wait sounds like the platform is under heavy load; nothing to do there but let support know.
