### ISSUE TITLE
/api folder is missing

### ISSUE THREAD

**Issue by Luck9r** [TechnicPack/TechnicSolder#569]
I'm sure, I'm doing something not right. Anyway /api folder is missing. Can somebody tell what's wrong?

**Comment by Isigiel** [comment]
Assuming, that's an error message thrown by your webserver, I'd think, that you don't route all requests via the index.php.
Another possibility is, that you actually looked for the api folder in public and didn't find it. Thtn, let me tell you: That's not how routing works, the idea is to not user folders but to resolve all requests via the index.php, which decide what's to display.

**Comment by Luck9r** [comment]
Sorry, I said not right... I have no /api folder at all, and I can't write www.mydomain.com/api/ because I don't have this folder! The real error is "Client error response [status code] 404 [reason phrase] Not Found [url] https://www.vortex-servers.com/TechnicSolder/api/verify/mysecretkey" Maybe I don't understand something...

**Comment by skwerlman** [comment]
there is no `/api` folder. in php, parts of a url can be considered to be arguments to an application. 

looking at your site, it looks like you tried to set solder up in a subfolder, but this is not how solder was designed to be used. solder should be run on a virtual host, with the root directory pointing at solder's public folder.

**Comment by Luck9r** [comment]
Thanks. I'll fix that.
