### ISSUE TITLE
ErrorException Laravel Framework Illuminate Foundation

### ISSUE THREAD

**Issue by giogimic** [TechnicPack/TechnicSolder#570]
{"error":{"type":"ErrorException","message":"Undefined index: timezone","file":"\/home\/admin\/web\/solder.servername.net\/public_html\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}> php artisan optimize
{"error":{"type":"ErrorException","message":"Undefined index: timezone","file":"\/home\/admin\/web\/solder.servername.net\/public_html\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}[root@servername public_html]# php -v

**Comment by giogimic** [comment]
Error appears after installing not sure what to make of it never had this issue last time i install solder on the same server. Running CentOS 7 php 5.5

**Comment by giogimic** [comment]
http://i.imgur.com/3fjnEyj.png

**Comment by giogimic** [comment]
Turned out i didnt have php55w-fpm installed installed with no errors after fixing that.

**Comment by ChipCustomizer** [comment]
gloglmic - I'm having the same problem on a Mac machine where I'm running PHP-5.6.11 - I'm not sure what php5w-fpm is and how to install it - can you elaborate on your fix and how I can get this fixed as well?  Thanks!

**Comment by skwerlman** [comment]
@ChipCustomizer open a new issue, since you are on a different platform from giogimc. when you open the new issue, please specify whether you are using homebrew or macports, and i'll see if i can't help.
