### ISSUE TITLE
Issue with framework i think

### ISSUE THREAD

**Issue by giogimic** [TechnicPack/TechnicSolder#571]
So im trying to figure this out I've reinstalled CentOS and installed both php5.5 and tried php7.0 after that both come up with the same issues.

If i try to install with the latest version of Composer i get an error so i go down 1 version no errors but when i go in to solder it's self this is what happens

http://i.imgur.com/TwHT4Y7.png

As you can see debug is on and no errors are being printed. I've also made sure the public and app/storage have the right permissions. 

Any clue what im doing wrong? i've had it running before on CentOS 6 but for some reason on CentOS7 it doesn't seem to want to work.

**Comment by TheDoctorsLife** [comment]
Are you hosting this with https?

**Comment by giogimic** [comment]
No.

**Comment by skwerlman** [comment]
can you upload the source of that page as a [gist](https://gist.github.com/) and link it here?

you can view the source of the page by hitting <kbd>ctrl</kbd><kbd>u</kbd>

**Comment by giogimic** [comment]
https://gist.github.com/giogimic/774be34fdee868b0a6f6

Sure thing feel free to sign in to the solder to view it yourself aswell i havent changed the default password

**Comment by skwerlman** [comment]
tbh, i'm stumped.

the first image (@giogimic's site) shows that all of the .css files and title.png are initially canceled, then successfully loaded later (but not applied?).

the second image (my site) shows how the page normally loads (through cloudflare, at least) (ignore the failed ga.js; adblock).

![image](https://cloud.githubusercontent.com/assets/6954107/14058375/4bc6de9a-f2f4-11e5-8f64-bb86810894d6.png)

![image](https://cloud.githubusercontent.com/assets/6954107/14058352/cdd65a1a-f2f3-11e5-93cb-cc212615241b.png)

 i have no idea what would cause an issue like that...

**Comment by TheDoctorsLife** [comment]
To add insult to injury
I don't have those cancelled requests
![solder](https://cloud.githubusercontent.com/assets/7450443/14062890/dc75959e-f385-11e5-9e06-95d197ed1b5e.PNG)

**Comment by TheDoctorsLife** [comment]
To add insult to injury
I don't have those cancelled requests
![solder](https://cloud.githubusercontent.com/assets/7450443/14062890/dc75959e-f385-11e5-9e06-95d197ed1b5e.PNG)
@giogimic Can you hop on the discord server? maybe we can get it fixed through the live/voice chat.

**Comment by giogimic** [comment]
Sure. I'm Chuck on Discord.

**Comment by skwerlman** [comment]
you guys ever get this figured out? i'm genuinely curious what the issue was...

**Comment by giogimic** [comment]
Nope still having the issue not resolved yet.

**Comment by giogimic** [comment]
No one's messaged me on discord so please if you find a solution post here.

**Comment by Isigiel** [comment]
So @giogimic I can offer you a dirtx solution to this, which is.
Replace the href in this line `https://github.com/TechnicPack/TechnicSolder/blob/master/app/views/layouts/master.blade.php#L13`
with `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css`in your local installation, that seems to fix the issue of not loading bootstrap properly
