### ISSUE TITLE
Composer Required Package Issue

### ISSUE THREAD

**Issue by Mac898** [TechnicPack/TechnicSolder#574]
So, im having a issue with composer. It keeps having http request failed errors for the file ""http://packagist.org/p/illuminate/cookie%243989eaaa6d018ca55f2075677fff25bd2f536f27f80a0937a9e69f87e36c9.json" Trying it in chrome or firefox or opera results in a 404 error.
And btw it seems like the bootloader is requiring illuminate/html which is now replaced by larvarel/html.

Background Information:
Linux Ubuntu 10.4.2 LTS
PHP5, (all things installed)
TechnicSolder Latest
NGNIX

**Comment by TheDoctorsLife** [comment]
I would double check you have the latest composer version.

**Comment by Mac898** [comment]
I downloaded composer 0.7 then used composers inbuilt updater. should have latest v

**Comment by GenPage** [comment]
Are you able to attempt the install again? If so, is there any more information pertaining to the failed package install?

**Comment by Mac898** [comment]
Attempting the install again, same issue. And no thats all the error said. Exactly this:
""http://packagist.org/p/illuminate/cookie%243989eaaa6d018ca55f2075677fff25bd2f536f27f80a0937a9e69f87e36c9.json" : HTTP REQUEST FAILED. Thats it. Should i try running it in a debug mode if there is one?

**Comment by Mac898** [comment]
Actually, This time it came up with the error "Cannot create cache directory /home/mac.composer/cache/repo/https---packagist.org/, or directory is not writable proceeding without cache

Repeats twice.

**Comment by skwerlman** [comment]
Try rerunning as root. That should fix the cache error, though that's not your main issue.

**Comment by Mac898** [comment]
Trying that the yellow message was gone, the red message continues: 
![capture](https://cloud.githubusercontent.com/assets/9291773/14230815/c984c398-f9ab-11e5-9a73-289717639ba8.PNG)

**Comment by Mac898** [comment]
This is getting a little old now(30 days) but I really need some help to get this working. My new modpack depends on me getting it working. Thanks in advance -Mac

**Comment by skwerlman** [comment]
actually, now that i look back at this, it probably has something to do with you using an os that eol'd 4 years ago...

**Comment by Mac898** [comment]
Ok i will try updating the OS to the latest ubuntu LTS.

**Comment by Mac898** [comment]
Answer: use sudo apt-get upgrade.
