### ISSUE TITLE
SunCertPathBuilderException when using Let's Encrypt SSL

### ISSUE THREAD

**Issue by Ionaru** [TechnicPack/TechnicSolder#575]
Heya guys,

When serving my Solder installation with SSL encryption, the Technic client gives me this error:
http://pastebin.com/unW5DwAe and it will not connect.

I used Let's Encrypt to generate the required certificate.

**Comment by TheDoctorsLife** [comment]
Sounds like java doesn't have the certs to verify it. I would post this in the launcher though.
"unable to find valid certification path to requested target"

**Comment by GenPage** [comment]
@Ionaru @TheDoctorsLife This is correct. The issue is most likely an outdated Java version/keystore that does not contain the Root CA certs for Lets Encrypt, so Java refuses the HTTPS/SSL connection.

**Comment by Ionaru** [comment]
So this issue will happen for every client that uses outdated Java/Keystore versions?

Is there any way to add trust for these certificates through the client (without people having to manually perform an action)?
