### ISSUE TITLE
API for the server downloads

### ISSUE THREAD

**Issue by totokaka** [TechnicPack/TechnicSolder#577]
Hi,

I realize this might be a bit out of scope for Solder, but I also think this is the most appropriate place to ask. All the modpacks on (technic pack's) solder have server downloads available on technicpack.net, but no way to programatically get these. 
I would like links to the server downloads under each build on the `api/modpack/:slug/:build` endpoint.

If this is not the right place, I would appreciate a heads-up if someone knows of an API listing server builds of popular modpacks. Information about why Tekkit and other packs disappeared from solder.technicpack.net would also be nice.

The motivation for this is letting users choose what server version to run in [SpaceCP](https://spacecp.net/). To allow for this, we need to be to centralize all servers in [SpaceGDN](https://github.com/XereoNet/SpaceGDN), and for that we need an api to fetch the versions.

**Comment by Isigiel** [comment]
Well, for official servers, there's a pretty easy scheme for the server locations. I'm not sure if an api endpoint for solder would be the best idea ...
The older packs went private but are still on the solder http://solder.technicpack.net/api/modpack/tekkitmain

Lastly, I haven't heard of such an api yet, I assume, you'd just have to map those servers yourself.

**Comment by totokaka** [comment]
I see.

I'll just go for manually listing the modpack names, and mapping their download URLs.

Thanks for the help!
