### ISSUE TITLE
Invalid Link on Links that used to work.

### ISSUE THREAD

**Issue by Acdrybones** [TechnicPack/TechnicSolder#582]
Some Direct Download links simply do not work, and some dont work with ones that used to work.
Also, we need to be able to use https://disk.yandex.com as a modpack host.

**Comment by spannerman79** [comment]
I don't use yandex but I would assume file access is via cookie. You can't use that. You need to have **direct** url file access. Hence why the solder docs specify an apache or ngix webserver

**Comment by GenPage** [comment]
@spannerman79 Is correct, you'll need a direct download link from disk.yandex.com for it to work as a host.
