### ISSUE TITLE
SSL problems

### ISSUE THREAD

**Issue by NEXUS2345** [TechnicPack/TechnicSolder#583]
Essentially, all resources (images, stylesheets, redirects, etc.) need to be updated to support both http and https (ssl) if possible. SSL is becoming more and more common and the lack of support in this project is annoying and a risk, especially for modpack developers who may wish to ensure they cannot be subjected to a MitM attack.

**Comment by Goldman60** [comment]
Can't reproduce, mine works on SSL just fine (now if only Java supported the Lets Encrypt CA)

**Comment by skwerlman** [comment]
@NEXUS2345 this was fixed in #562. Consider updating to master.

**Comment by NEXUS2345** [comment]
Attempting it now after pulling from master. Will close ticket once I have confirmed SSL is working correctly.

**Comment by NEXUS2345** [comment]
I can confirm that SSL is working, however all of the stylesheets are being served over HTTP still, meaning Chrome and many other browsers will block them.

**Comment by NEXUS2345** [comment]
Javascript files are also not being served via HTTPS

**Comment by skwerlman** [comment]
That's not the case on my install... Can you link to your install so we can help debug?

**Comment by NEXUS2345** [comment]
https://solder.preludegaming.net/dashboard

**Comment by NEXUS2345** [comment]
Do you mind linking your own install as well? @skwerlman

**Comment by skwerlman** [comment]
https://solder.tetrarch.co

it looks like something is wrong with how you're redirecting to ssl. login.css is not being 301'd

**Comment by NEXUS2345** [comment]
It looks like you are using Cloudflare, have you enabled strict SSL on that subdomain?

**Comment by NEXUS2345** [comment]
Do you want a copy of the nginx config?

**Comment by skwerlman** [comment]
no; cf has issues with my letsencrypt cert. However, ssl does still work with cf disabled.

**Comment by NEXUS2345** [comment]
https://gist.github.com/NEXUS2345/2d37869119e76be36efa26e6923da181

**Comment by skwerlman** [comment]
Try using a seperate block for ssl redirection:
```nginx
server {
    listen 80;
    server_name solder.preludegaming.net;
    return 301 https://$host$request_uri;
}
```

**Comment by NEXUS2345** [comment]
That is leading to a problem of too many redirects on dashboard... Might try reinstalling Solder altogether.

**Comment by skwerlman** [comment]
did you remove the `listen 80;` from the original block?

**Comment by Willsr71** [comment]
Yes but it is still redirecting.

**Comment by skwerlman** [comment]
What does your config look like now? Do you have any sort of redirect in the original block?

**Comment by NEXUS2345** [comment]
https://gist.github.com/NEXUS2345/a21afdb8b1c8a109ac52cd3ea87a46fc

**Comment by NEXUS2345** [comment]
Ok, I did the reinstall, and it made no difference. Pulled directly from master, and still having the issue.

**Comment by skwerlman** [comment]
Well, i'm at a loss, since I don't see anything in your config that would cause a redirect loop like that...

[Here](https://gist.github.com/skwerlman/71129448aed0f5e4aa783856d228e0a3) is my nginx conf if it proves useful. Sorry I can't be of more help...

**Comment by NEXUS2345** [comment]
I noticed that you are using PHP 5. We are running PHP 7, could this be the issue?

**Comment by NEXUS2345** [comment]
Nevermind, I fixed it, apologies for wasting your time, I had a misconfigured page rule.
