### ISSUE TITLE
500 Database [] not configured.

### ISSUE THREAD

**Issue by lbpfan950** [TechnicPack/TechnicSolder#585]
Sorry for my poor report, I'm new to this, my database config is displayed and ive hit a snag with the eror above.

You can see the error, ive turned on debug, at http://office.lbpfan950.net:81 if you sign in with the default credentials

**Comment by spannerman79** [comment]
Use gist - it's part of github.

I won't and I'm sure many others won't access a strange url like what you
provided

**Comment by lbpfan950** [comment]
the error isnt simply one, it is the debug screen
