### ISSUE TITLE
Problem with solder making modpacks not open

### ISSUE THREAD

**Issue by Dhkavka** [TechnicPack/TechnicSolder#586]
http://pastebin.com/1yShfvZ6
This is the full console from start up to when I tried loading the modpacks.
I have posted this problem on the forums and a nice gentleman pointed out that it seemed to be a problem with solder and that I should get help from someone who knows more about solder. Any help would be appreciated and additional information is available upon request.

**Comment by skwerlman** [comment]
Did you close this intentionally? If so, would you mind posting your solution for the benefit of future searchers?
