### ISSUE TITLE
Technic Client Refuses to see pack as solder enabled

### ISSUE THREAD

**Issue by GeekBroadway** [TechnicPack/TechnicSolder#588]
Ive been experimenting around with Technic solder for a while now, and ran into a peculiar issue where the Technic launcher doesn't see my pack as solder enabled and tries to download a non existent ZIP. The webpage on http://technicpack.net shows my pack as being solder enabled and has the mods tab with the current mod list, so I know the platform can talk to my solder repo. I've tried on multiple computers, I've deleted the .technic folder and reinstalled. Still same issue.

Pack URL: (http://www.technicpack.net/modpack/mondoseverythingpack.868158)

**Comment by skwerlman** [comment]
According to your solder install's api, you don't have any public modpacks on solder, though I was able to access the modpack by slug.
I'm guessing the modpack is marked as "Private". This mean you will need to make sure your Technic Client's UUID is allowed to access the modpack. (The UUID changes on each install, and can be found in the client settings.)
You can add a new UUID at `Configure Solder > Client Management > Add Client`.

**Comment by GeekBroadway** [comment]
Thanks for the quick reply, I don't believe I have it set to private, here's some screenshots

![modbuilds](https://cloud.githubusercontent.com/assets/4131281/16549308/19d88cda-41e1-11e6-88d8-16c428a6402b.PNG)
![modpage](https://cloud.githubusercontent.com/assets/4131281/16549312/2a3b558a-41e1-11e6-8bfe-0db24413ced8.PNG)

**Comment by skwerlman** [comment]
You need to unhide it on solder.
Hiding a pack on the platform is what you want (and have already done). Hiding it on solder will prevent it from being used.

**Comment by skwerlman** [comment]
Side note: 'Hide Modpack' needs a better name. It's confusing.

**Comment by GeekBroadway** [comment]
That does seem to make more sense after ready the description under hide modpack, I have unchecked that and testing now

**Comment by GeekBroadway** [comment]
Does it take time for the platform to update?, tried removing pack, deleting .technic etc. Still wants to unzip an archive.

![technicscreeno](https://cloud.githubusercontent.com/assets/4131281/16549408/7ca3f6aa-41e2-11e6-94a3-d63f05dfedcc.PNG)

**Comment by skwerlman** [comment]
It can take up to an hour, though closing and reopening the launcher should help.

**Comment by GeekBroadway** [comment]
Alright Ill leave it for an hour and close it if resolved, thanks for your help @skwerlman

**Comment by skwerlman** [comment]
hth :)

**Comment by GeekBroadway** [comment]
Yup working now, cheers
