### ISSUE TITLE
404 addressing the server over its IP or internal hostname on Apache2

### ISSUE THREAD

**Issue by daemonnecis** [TechnicPack/TechnicSolder#590]
I'm getting an 404 error after setting up solder and opening "[...]/public/"
I'm getting redirected to "[...]/public/dashboard", followed by the 404 error.
When I manually correct the browser address to "[...]/public/index.php/dashboard", solder's GUI loads fine and works correctly. It seems to be an error with the redirection. I disabled URL rewrite for troubleshooting reasons but it did not change anything.

My setup:
Debian
Apache2, MySQL, PHP 5.4.45

Apache2 site file:
https://gist.github.com/anonymous/7d75dcec270fa0217d0e31fe578f82cb/raw/4cb109af287df7e244c86c510e9ce531a82ff83a/Apache2

**Comment by skwerlman** [comment]
If you haven't already, read http://docs.solder.io/v0.7/docs/example-web-server-configs#apache

**Comment by daemonnecis** [comment]
Thank you for your response.
I've read it following the "getting started" gude. I must admit that I might had some understanding issues. Is it a normal behavior then, that rewriting the URL doesn't work for addressing the server over its IP adress or internal hostname? (Addressing the server over its public hostname works fine)

**Comment by daemonnecis** [comment]
Issue closed:
The problem only occurs if you address the webserver server using its IP address or its internal hostname. Using the external hostname works fine.

This is because overrides are globally disabled on our server but are enabled on certain virtual host identified by a given "Servername" directive. If the "Servername" doesn't match, overrides are disabled. That is the case when you address the server using its IP address or internal hostname.

To fix that, I think you could enable overrides globally or give the virtual host some aliases, but I didn't test that.

**Comment by skwerlman** [comment]
Glad you figured it out, and thanks for posting your solution
