### ISSUE TITLE
Can't create new modpack (can, just retarded)

### ISSUE THREAD

**Issue by lulzie** [TechnicPack/TechnicSolder#592]
![2016-07-07 15_42_46-application error - technic solder](https://cloud.githubusercontent.com/assets/5831879/16655298/f438cfbe-4459-11e6-80a7-ca801f817e1e.png)

After a move I can't seem to establish new modpacks and edit old ones.
I even tried to move it back but the error persists, so I'm actually not sure it happend at the move.
All other functionality is flawless, just the Create/Edit Modpack throws this error.

Permissions are set, I've even tried 777 for the entire tree but same error is provided. 
I've noticed the Edit Modpack throws error "Unable to write to 'public/resources/<modpack>'. Please check your file/folder permissions."

public it refers to is the old folder, whilst the new one is public_html.
The rest of the structure is identical.
Appconfig, database entries, and Solder config has been edited to reflect the changes but this bit seems to still have the old config. What have I missed?

Thanks in advance.

**Comment by lulzie** [comment]
Godf-ckingdamnit.
bootstrap/paths.php

Case closed, much love.

**Comment by skwerlman** [comment]
If your issue is resolved, please close this ticket.
