### ISSUE TITLE
Issue with laravel (probably)

### ISSUE THREAD

**Issue by awesomeness872** [TechnicPack/TechnicSolder#593]
After using `composer install --no-dev --no-interaction` and `php artisan migrate` and configuring the files in app/config when i got to the page hosting solder i get this http://i.imgur.com/BsDpfIc.png It was working and then one day it stopped. I have reinstalled solder twice thinking it would fix it but got not results, only wasted time.

**Comment by skwerlman** [comment]
What web server are you using? Have you configured it to run php files?

**Comment by awesomeness872** [comment]
as i said it was fully working so yes, and I am running apache with ubuntu 16.04

**Comment by skwerlman** [comment]
Did you fix this? If you did, could you leave your solution for future googlers?
