### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by BearbaBear** [TechnicPack/TechnicSolder#594]
I got Technic Solder set up to the point that I could connect to the login screen through my external ip address.  As soon as I login with the default credentials (admin@admin.com, admin), it says this: "`Error in exception handler: The stream or file "/home/pi/TechnicSolder/app/storage/logs/solderlog-2016-07-09.txt" could not be opened: failed to open stream: Permission denied in /home/pi/TechnicSolder/bootstrap/compiled.php:9144`"  What does this mean?

**Comment by Isigiel** [comment]
Have you set the permission on the `/storage` directory?

**Comment by BearbaBear** [comment]
What level of permissions?  I was thinking of 775, but it didn't work the first time I attempted Solder.

**Comment by Isigiel** [comment]
Just make sure the webserver has full read and write perms, you can also look up permissions here https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-permissions *(taken from the installation guide)*

**Comment by BearbaBear** [comment]
Ok, thanks!  I wasn't sure if I just needed to fix the perms.

**Comment by Isigiel** [comment]
If that fixed your problem, please close this issue

**Comment by BearbaBear** [comment]
Now it's saying this: "`Error in exception handler: The stream or file "/home/pi/TechnicSolder/app/storage/logs/solderlog-2016-07-09.txt" could not be opened: failed to open stream: Permission denied in /home/pi/TechnicSolder/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107`"  I thought I set up the perms right, but does this mean otherwise?

**Comment by Isigiel** [comment]
Seems like there's still something wrong

**Comment by BearbaBear** [comment]
Oh oh oh OH!!  I figured it out.  I had changed the perms of the project to 775 instead of 777.  Works now.  Thanks for all your help!
