### ISSUE TITLE
Mod installation problem

### ISSUE THREAD

**Issue by BearbaBear** [TechnicPack/TechnicSolder#597]
I set up my mod library with the instructions in the [docs](http://docs.solder.io/docs/adding-mods-to-the-mod-library), with the .zip structured like this:
![before-zip](https://cloud.githubusercontent.com/assets/15389659/16711439/61aa257c-4629-11e6-9b8b-3dd820c6be44.png)
 But when I test out my modpack installation, it extracts the .zips into the main MC directory, like so, instead of distributing the contents to the appropriate folders:
![ext-fin](https://cloud.githubusercontent.com/assets/15389659/16711423/3a172ba0-4628-11e6-81c7-d4afb2e61892.png)

**Comment by spannerman79** [comment]
http://docs.solder.io/docs/zip-file-structure

**Comment by BearbaBear** [comment]
I meant that this one was the zipped file:
![before-zip](https://cloud.githubusercontent.com/assets/15389659/16711484/01331796-462c-11e6-9d15-effe37fca1df.png)

**Comment by skwerlman** [comment]
remove the versions from the folder names

**Comment by BearbaBear** [comment]
Thank you both for your help!  Finally realized what I was doing wrong...
