### ISSUE TITLE
Error when using tail slash in /api/

### ISSUE THREAD

**Issue by checkplys** [TechnicPack/TechnicSolder#598]
I got my solder instalation running at http://solder.reloadcraft.ga/, and all is working fine.
But I've got an issue with /api/
"http://solder.reloadcraft.ga/public/api" works fine.
but "http://solder.reloadcraft.ga/public/api/" gives me a 500 error.
I've searched and dind't find any thing to fix that, so, I'm asking here.

**Comment by skwerlman** [comment]
If you've found a solution to your problem, would you mind posting it for the benefit of others?
