### ISSUE TITLE
Images bug when modpack is renamed.

### ISSUE THREAD

**Issue by fuwwy** [TechnicPack/TechnicSolder#599]
When you have images in any modpack and rename it. 
The images will still have the old URL and will look like this:
![image](https://cloud.githubusercontent.com/assets/9268058/16764418/edb562d6-4825-11e6-8597-a9b6bd914d48.png)

**Comment by skwerlman** [comment]
possibly related: #484

**Comment by Pyker** [comment]
Closing since images are no longer a thing
