### ISSUE TITLE
Application Error - 500

### ISSUE THREAD

**Issue by CourtArtanis** [TechnicPack/TechnicSolder#603]
I attempted to try to be clever and edited the production.sqlite database to batch input mods/mod versions, since I have over 100 mods.
However, after doing so, and being careful to preserve the structure/columns/format of the data, I now receive this error on clicking the dashboard:

I used .csv files to import the data to the correct columns.

 500  Unexpected data found. Unexpected data found. Unexpected data found. Trailing data (View: /home/sanitysu/public_html/TechnicSolder/app/views/dashboard/index.blade.php)

Is it even possible to batch input the records this way? Or will this error always appear? This has taken more time than if I used the panel to add the mods one by one, but I figured it was worth a try.

Thanks.

**Comment by spannerman79** [comment]
It might be "easier" if you started with MySQL instead of sqlite - you could have used http://forums.technicpack.net/topic/81569-modpack-helper-pack-modpacks-check-permissions-upload-to-web-update-solder-automatically/

**Comment by CourtArtanis** [comment]
Thanks for pointing me towards that, friend. I'll let you know how it works out.
