### ISSUE TITLE
artisan migrate undefined variable

### ISSUE THREAD

**Issue by JonDaHackingWiz** [TechnicPack/TechnicSolder#605]
When I try to run the command "php artisan migrate:install" or "php artisan migrate" both with and without super user, I get the following error message:
{"error":{"type":"ErrorException","message":"Undefined variable: aliases","file":"\/var\/www\/html\/TechnicSolder\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":180}}

Is this an unknown issue or do I need to identify the variable somewhere in a configuration file, because I have no idea what to identify

**Comment by skwerlman** [comment]
Which configs did you edit and can you post them here? (after scrubbing sensitive info, ofc)

**Comment by JonDaHackingWiz** [comment]
@skwerlman 
[/vendor/laravel/framework/src/Illuminate/Foundation/start.php.txt](https://github.com/TechnicPack/TechnicSolder/files/402921/start.php.txt)
[/app/config-sample/app.php.txt](https://github.com/TechnicPack/TechnicSolder/files/402922/app.php.txt)
[/app/config-sample/database.php.txt](https://github.com/TechnicPack/TechnicSolder/files/402923/database.php.txt)
[/app/config-sample/solder.php.txt](https://github.com/TechnicPack/TechnicSolder/files/402924/solder.php.txt)

**Comment by JonDaHackingWiz** [comment]
I have figured out the problem. It has to do with incorrectly installing TechnicSolder. I used "config-sample" and not "config". I'm sorry if this has lost some of your time, but thank you for stopping by anyway @skwerlman
