### ISSUE TITLE
internal server error 

### ISSUE THREAD

**Issue by runescapejon** [TechnicPack/TechnicSolder#606]
Hello when i added Pixelmon 1.8.9 to solder i am having an "Internal server Error"
i look around Technic Solder and saw that it's a memory limitation, i had edit this file php.ini 
i had edit with this 
`upload_max_filesize = 1000M
post_max_size = 2000M
memory_limit = 3000M
file_uploads = On
max_execution_time = 180`
then the problem still happening is there anyway to fix this problem ?

**Comment by skwerlman** [comment]
Is your issue fixed? If not, please attach logs and reopen.

**Comment by runescapejon** [comment]
its fixed i got it but thanks
