### ISSUE TITLE
500 error when adding build

### ISSUE THREAD

**Issue by LordOfLegends** [TechnicPack/TechnicSolder#607]
Hello,
When I try to add a build on my solder server, I get a 500 error because of my server being hosted as a HVM instance (server shared with other users). I know that the solution lies in changing the php curl option 'followlocation'. Someone else had this problem and fixed it by changing the option to false, but I do not know how to do that. Thanks in advance.
![curl](https://cloud.githubusercontent.com/assets/21269571/18021557/2c85f88c-6bb6-11e6-80f5-6f5b36ec7f98.JPG)

**Comment by skwerlman** [comment]
alright, so first off, if you can, you should really look into getting a non-shared hosting solution, because solder is not supported on shared hosts.

as for changing `curlopt_followlocation` to false, its located at `app/libraries/UrlUtils.php` line 38.

hopefully this helps.

**Comment by LordOfLegends** [comment]
Thank you so much. Everything is working now.
