### ISSUE TITLE
[Bug/Error] No styling

### ISSUE THREAD

**Issue by Kongzted** [TechnicPack/TechnicSolder#608]
I've just installed Solder, but there is no styling/design on the site..

Example: 
![no-styling](https://cloud.githubusercontent.com/assets/5521003/18356728/3c616b1e-75ee-11e6-81df-e7924030a71b.png)

What can i do to fix this?

**Comment by SLemons13** [comment]
Are the permissions on the public folder 777?

**Comment by Kongzted** [comment]
Yes they are :+1:

**Comment by skwerlman** [comment]
Would you mind providing a link to your solder install so we can debug?

**Comment by Kongzted** [comment]
http://solder.kongzted.net/

**Comment by skwerlman** [comment]
I'm getting a cloudflare error 520 for your site...

**Comment by spannerman79** [comment]
@Kongzted your ADSL connection isn't stable enough to run a (web) server on.

Your ISP is either filtering or throttling.  Obtain a VPS *at least* that isn't filtered.

Non-solder issue.
