### ISSUE TITLE
Error Downloading a File

### ISSUE THREAD

**Issue by GambarojaLP** [TechnicPack/TechnicSolder#611]
Hello Guys.
I ran into an Error today that i can't explain myself. 
Yesterday i was working on getting Solder up and running and it worked, downloading of the Modpack worked too. So far so good. Then i've gone to sleep and logged in today, try to re-download it (to make sure there are still no bugs) and now i get the following the Error Message "Error downloading a file for the following modpack: xxx)

So i checked the Link, it was alright,
i checked the MD5 and it was alright
i've rehashed every single mod and it still didn't worked. (Screenshots Attached)

So, now i've got the Problem, that there's a correctly file Setup, an correct MD5 and an Correct Repo but somehow i can download it in my Browser for example but the Launcher cant...

I disabled my Firewall and i don't have any other Antivirus running (other modpack tried, and it worked).
So... Does anybody have an idea what the hell iam doing wrong?

Thanks in Advance.

PS: Files got reuploaded, deleted and rehashed = Still same

**Comment by Pyker** [comment]
```bash
$ curl -q http://repo.gvrftb.kozow.com/mods/wr-cbecore/wr-cbecore-1.7.10-1.4.1.9.zip

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<!-- WEB REDIRECTION PROVIDED BY DYNU.COM http://www.dynu.com/ -->
<head>
  <title>Repo</title>
  <link rel="icon" href="http://89.163.209.122:91/mods/wr-cbecore/wr-cbecore-1.7.10-1.4.1.9.zip/favicon.ico" type="image/ico">
  <link rel="shortcut icon" href="http://89.163.209.122:91/mods/wr-cbecore/wr-cbecore-1.7.10-1.4.1.9.zip/favicon.ico">
  <meta name="keywords" content="repo">
  <meta name="description" content="repo">
</head>
<!--
<script language="JavaScript">
  if(window != top) {
    top.location.href = location.href;
  }
</script>
-->
<frameset marginwidth=0 marginheight=0 frameborder=0 border=0 rows =" 1,*">
  <frame src="emptypage">
  <frame src="http://89.163.209.122:91/mods/wr-cbecore/wr-cbecore-1.7.10-1.4.1.9.zip" name="main">
  <noframes>This browser does not support frames. Please <a href="http://89.163.209.122:91/mods/wr-cbecore/wr-cbecore-1.7.10-1.4.1.9.zip" target="_top">click here</a> to access the website.</noframes>
</frameset>
</html>
```

**Comment by GambarojaLP** [comment]
#Closed thanks for the Info 👍
