### ISSUE TITLE
Creating new pack build error

### ISSUE THREAD

**Issue by MrFrostmaul** [TechnicPack/TechnicSolder#615]
Hi, when trying to create a new pack build, we are faced with the following error: http://image.prntscr.com/image/805f284ec6d94a51834635d194adc84a.png

We have tried turning off open_basedir and disabling in php.ini but still no joy, any ideas how to resolve this?

Thanks

**Comment by skwerlman** [comment]
Dupe #314, #378, #522, #607

Please see [this comment](https://github.com/TechnicPack/TechnicSolder/issues/607#issuecomment-242909263) for the fix.
