### ISSUE TITLE
Updating issued and finding api.

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicSolder#616]
Hello, I have two main issues currently with solder and updating our modpack. In this picture below, solder/technic does not seem to be updating the launcher at all with build information even though it is apeparing on the technic site and has been over 72 hours at writing this. (took minutes to update to the website)
![image](https://cloud.githubusercontent.com/assets/4203009/19977538/cf4da77a-a1eb-11e6-95ca-9c6035bbd13a.png)

Also, needing some advice on launching the pack, the urls are set correctly with the api below, but in the pack launcher it cannot access.. any ideas with this? :

![image](https://cloud.githubusercontent.com/assets/4203009/19977639/2165b2fa-a1ec-11e6-8f60-48ac0aaccdb6.png)

![image](https://cloud.githubusercontent.com/assets/4203009/19977650/2693819e-a1ec-11e6-84e0-8e8dd4c413d1.png)

Thanks

**Comment by skwerlman** [comment]
You need to use a vhost so that the webroot points to the public folder. Otherwise people can download your config files (which have credentials for your db!!)

If you're still having issues once that's fixed, let us know.

**Comment by MrFrostmaul** [comment]
Hi, Thanks I have changed that and showing update (D0.0.1) on TechnicPack site at the top, but not under the updates section yet.
When launching the pack, now getting the following error: http://prntscr.com/d3cwbo

**Comment by skwerlman** [comment]
That's normal; though technically a problem with the launcher and not solder.
