### ISSUE TITLE
Does The links works for chormebooks ?

### ISSUE THREAD

**Issue by AutisticMC** [TechnicPack/TechnicSolder#620]
https://github.com/TechnicPack/TechnicSolder.git

**Comment by skwerlman** [comment]
TechnicSolder needs to be run on a public-facing server.
Your best bet is to rent a small box from somewhere like DigitalOcean to host it. Once you've got it set up, any computer with a web browser should be able to interact with it, although you'll probably need to find a chromeos-compatible FTP client.
