### ISSUE TITLE
could not find driver error

### ISSUE THREAD

**Issue by tomgie** [TechnicPack/TechnicSolder#621]
Getting this error on a fresh install please help!

**Comment by TheDoctorsLife** [comment]
You have provided zero information for anyone to help you with. Please at least provide the error/issue you are having (and logs too).

**Comment by skwerlman** [comment]
and also information about the platform you're using (os, nginx or apache, mysql or postgresql, etc)

**Comment by skwerlman** [comment]
Did you get this fixed? If so, could you put your solution here so people who have this error in future can see how you fixed it?

**Comment by tomgie** [comment]
chmod the public/ folder
