### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by LewisTehMinerz** [TechnicPack/TechnicSolder#624]
Cannot access the Solder that is at my domain. Running on a dedicated VPS.

/var/log/apache2/error.log:

```
[Mon Feb 06 11:04:45.161915 2017] [:error] [pid 19916] [client 141.101.98.117:23058] PHP Warning: require(/var/www/xenosolder/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/xenosolder/bootstrap/autoload.php on line 17
[Mon Feb 06 11:04:45.161952 2017] [:error] [pid 19916] [client 141.101.98.117:23058] PHP Fatal error: require(): Failed opening required '/var/www/xenosolder/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/xenosolder/bootstrap/autoload.php on line 17
```

All permissions are set to 755 on EVERY file and folder in the Solder directory (xenosolder).

Also occurs when attempting to use `php artisan migrate`.

Side note: I ran `php composer.phar install --no-dev --no-interaction` without any issues.

**Comment by skwerlman** [comment]
Is `/var/www/xenosolder/bootstrap/autoload.php` actually there? If not, you can redownload it from here: https://raw.githubusercontent.com/TechnicPack/TechnicSolder/master/bootstrap/autoload.php

**Comment by LewisTehMinerz** [comment]
Yup, it's there.

**Comment by tomgie** [comment]
chmod the bootstrap folder and everything in it, that's what worked for me. Might not be the best practice but it worked.

**Comment by skwerlman** [comment]
DON'T `chmod 777`! 755 is correct.

Do you have logs from `php composer.phar install --no-dev --no-interaction`?

**Comment by LewisTehMinerz** [comment]
I would give you them but my VPS provider decided to screw me over, so you'll have to wait for a bit.
