### ISSUE TITLE
No api/ folder? Resulting in 404

### ISSUE THREAD

**Issue by Aphyxia** [TechnicPack/TechnicSolder#625]
I've setup Solder on my server and wanted to link it in http://www.technicpack.net but have come across a problem. This doesn't seem common at all and so I can only assume I've done something wrong.
Trying to enter the url "http://aphyxia-solder.tk/api/" gives the following error:
Request to verify Solder API failed. HTTP returned 404

This seems natural to me, since there is no api/ folder there (or anywhere, for that matter). I've done everything to the point in this guide and everything else seems to work but this has me puzzled.

This is the contents of the folder where http://aphyxia-solder.tk heads:
[https://gyazo.com/da81dd75ee1c38d14be06c3ca2a11249](https://gyazo.com/da81dd75ee1c38d14be06c3ca2a11249)

The only thing I had to do different was disable E_DEPRECATED exceptions because I'm using PHP 7.1.1 and mcrypt is deprecated.

A few things I think are strange but might not be the cause:

- app/config/app.php the url I've set to "http://aphyxia-solder.tk:8000". I've no idea if this is correct. The default was using port 8000 so I left it at that. Artisan seems to have migrated the database so that is fine I guess.
- app/config/solder.php the mirror_url I've set as my_external_ip/Solder/Modpack since it is before the "aphyxia-solder.tk" folder.
- when using composer, I at first neglected the "--no-dev --no-interaction" attributes of composer and ran it without them. After that I ran it with them, no errors though so I imagine it was okay.

Probably a simple solution to this but it's out of my reach.

**Comment by Aphyxia** [comment]
Ok, so the required folder was /public/api/, so that's good to know. good for anybody facing the same problem as me.

**Comment by GenPage** [comment]
@Aphyxia There is no API folder on purpose. Solder handles any link not in the base url as an application route.

all api endpoints should be redirected to the index.php in the public folder as arguments for the application to handle

Example of this can be found on the Solder docs page: http://docs.solder.io/docs/example-web-server-configs

**Comment by evernife** [comment]
@Aphyxia 
How to disable  E_DEPRECATED exceptions ?

![image](https://cloud.githubusercontent.com/assets/11357801/22912114/81183d18-f24a-11e6-8f90-ec9a90e01ddd.png)

**Comment by Aphyxia** [comment]
I don't know if I should give the rod or fish here but whatever.
The way I did it was put `error_reporting(E_ALL ^ E_DEPRECATED);` after <?php in app/config/app.php
It shows all errors but the deprecation ones.

**Comment by evernife** [comment]
i had put `error_reporting(~ E_DEPRECATED);` and did not worked..

it was a bit similar, but thank you :V

**Comment by GenPage** [comment]
@Aphyxia @evernife This is because you guys are using PHP 7.1, only 7.0 is supported.

**Comment by Aphyxia** [comment]
The requirements clearly state PHP 5.5+ (meaning all newer versions) so that should be fixed if PHP 7.1 is not supported I guess.

**Comment by GenPage** [comment]
@Aphyxia The requirements state PHP 5.5+ this means all versions of PHP 5 above 5.5, not PHP7. While PHP 7.0 is support and baked into the testing, 7.1 is a much newer release and is not.

**Comment by spannerman79** [comment]
> The requirements state PHP 5.5+ this means all versions of PHP 5 above 5.5

While I agree with you @GenPage security updates for 5.5+ will end in a little over a year.

Current "supported" PHP is 7.0 ([Source](https://secure.php.net/supported-versions.php))

**Comment by GenPage** [comment]
@spannerman79 I'm well aware PHP 7.0 is currently supported and the EOL timeline for PHP5. This is why work on v0.8 has already begun.
