### ISSUE TITLE
no textures for solder...

### ISSUE THREAD

**Issue by loander** [TechnicPack/TechnicSolder#626]
so I installed everything by the instructions also gave the permissions 777 to all of the solder folder and subfolders and files. and this shows up when i go into solder: http://i.imgur.com/4GOhXrW.png

**Comment by skwerlman** [comment]
can you link to your solder install so we can take a look?

**Comment by loander** [comment]
http://www.ngames.ga/TechnicSolder/ 
somehow to get to login screen i have to go into server.php

**Comment by loander** [comment]
things like forum works and im not getting anything like this from anything else hosted on server

**Comment by skwerlman** [comment]
You missed a few steps when configuring. Apache should be configured so that `TechnicSolder/public/` is the root directory, and there are a few Apache-specific steps listed [here](http://docs.solder.io/v0.7/docs/example-web-server-configs#apache).

**Comment by loander** [comment]
how do i do that exacly... Im new to ubuntu and linux together :(

**Comment by skwerlman** [comment]
I personally am not _super_ familiar with Apache, but [this guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts) might be able to help with setting up the example vhosts, which you can tweak for your particular setup.

**Comment by loander** [comment]
now I have other problem...

  sudo a2ensite solder.ngames.ga.conf
Enabling site solder.ngames.ga.
To activate the new configuration, you need to run:
  service apache2 reload
root@euve252374:~# sudo service apache2 restart
 * Restarting web server apache2                                         [fail]
 * The apache2 configtest failed.
Output of config test was:
AH00112: Warning: DocumentRoot [/var/www/solder.ngames.ga/public/] does not exist
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/solder/' for error log of vhost defined at /etc/apache2/sites-enabled/solder.ngames.ga.conf:1
AH00014: Configuration check failed
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by loander** [comment]
I reinstalled the solder in www directory with name solder.ngames.ga and made the config file in /etc/apache2/sites-enabled/
