### ISSUE TITLE
ddos protection?

### ISSUE THREAD

**Issue by jon100456** [TechnicPack/TechnicSolder#627]
hello some people are looking into client logs on technic and started ddos my solder link because i am using digital ocean is there a way to have ddos protection that great with technic Solder.
thanks

**Comment by spannerman79** [comment]
DDoS protection needs to be on the network side - not client/end user.
In other words you yourself need to organise DDoS with Digital Ocean.

Also a quick 3 second google search came up with https://www.digitalocean.com/community/tutorials/how-to-mitigate-ddos-attacks-against-your-website-with-cloudflare

**Comment by jon100456** [comment]
I did setup cloudflare but however wont work with Technic stop user from getting modpack and stop them from downloading mods

**Comment by spannerman79** [comment]
downloading != DDoS

**Comment by jon100456** [comment]
what do you mean ?

**Comment by spannerman79** [comment]
[downloading](https://en.wikipedia.org/wiki/Download) `does not equal` [DDoS](https://en.wikipedia.org/wiki/Denial-of-service_attack)

**Comment by jon100456** [comment]
okay but what i am saying that once i setup CloudFlare users are unable to download the mods from the modpacks

**Comment by jon100456** [comment]
if i stop cloudflare users can download it

**Comment by spannerman79** [comment]
You know if you actually **searched** [already existing issues](https://github.com/TechnicPack/TechnicSolder/issues?utf8=%E2%9C%93&q=cloudflare) you would come across https://github.com/TechnicPack/TechnicSolder/pull/572

Make the change yourself

**Comment by jon100456** [comment]
sorry i been searching is that the issue you gave me to look at i don't fully understand, is there a guide to fix this issue with cloudflare ?

**Comment by sct** [comment]
There is a guide posted like 5 comments up. This isn't the place to discuss this.
