### ISSUE TITLE
Forced https for technicpack.net/api/minecraft breaks older versions

### ISSUE THREAD

**Issue by schrej** [TechnicPack/TechnicSolder#629]
I just wanted to let you know that the automatic redirect to https on http://www.technicpack.net/api/minecraft breaks the adding of new builds on older versions (in our case 0.6) of solder. The `getMinecraft()` method in the `Modpack_Controller` returns null as the string received from the api endpoint is empty. Switching to https for the api url fixed it for us.

We know we are not really up to date, we made some customizations to solder that we would have to redo if we update though, which is why we are still on version 0.6.

**Comment by sct** [comment]
Not really an issue since you know.. its fixed in the current version but this is a good issue for people to reference if they run into the same problem I suppose. Either way, closing this.
