### ISSUE TITLE
Broken Download for WAILA Harvestability

### ISSUE THREAD

**Issue by ThisIsMARS** [TechnicPack/TechnicSolder#630]
Trying to download the Mianite Reborn modpack, and it appears that the download link for WAILA Harvestability is down. 

http://solder.endermedia.com/repository/mods/wailaharvestability/wailaharvestability-1.7.10-1.1.6.zip

I've tried substituting the downloads in for other mods and it works fine for others - is there a way I can get the file by other means, or if the download link could be fixed?

**Comment by GenPage** [comment]
@ThisIsMARS You would need to contact the maintainer of the EnderMedia Solder to get it fixed.

**Comment by ciak2009** [comment]
Ahahaha, I was working on a new project and when adding a new version of that I accidentally nuked the old one, feel free to mark this as resolved, even though it's invalid for this GitHub.
