### ISSUE TITLE
SQL error 500

### ISSUE THREAD

**Issue by cocomine** [TechnicPack/TechnicSolder#631]
I will sql database to my server built-in sql database.
I think the database is not fully moved to my server's database.
How to solve?

Error Log:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'solder.users' doesn't exist (SQL: select * from `users` where `email` = admin@admin.com limit 1)`

**Comment by khionu** [comment]
That is not a Solder issue. You need to learn how to do proper database management.

**Comment by cocomine** [comment]
I have succeeded
