### ISSUE TITLE
Why No Windows Support?

### ISSUE THREAD

**Issue by kenijey** [TechnicPack/TechnicSolder#632]
I am using Windows 10 and I want to make my modpack Solder enabled. Can i?

**Comment by spannerman79** [comment]
http://docs.solder.io/docs/getting-started#before-you-begin

**Comment by kenijey** [comment]
i already saw this 
> Warning:
> 
> Windows installation is not supported (No help will be provided.)
and i ask why no windows support

**Comment by spannerman79** [comment]
Windows 10 is not a server environment.
Seems you missed one important thing right at the top of the getting started docs

> Warning:
> 
> This application is intended for experienced system administrators and is not intended to be setup on a local home computer.
