### ISSUE TITLE
Technic Site Broken when Using Solder

### ISSUE THREAD

**Issue by Ra-Zim** [TechnicPack/TechnicSolder#633]
I am just about to launch my new modpack: https://www.technicpack.net/modpack/zgf-mustelid.898857

However, when I have the pack linked to the Solder, it works fine on the launcher, but I get an error of "Whoops, looks like something went wrong." when going to the link above. If I do NOT have the modpack linked to Solder, then it works fine (aside from being unable to download since there's no large zipped folder). I'm not sure where else to get support with this, but it breaks with Solder, so here I am.

**Comment by sct** [comment]
Something is wrong with your Solder which is causing this to happen. I thought we fixed this to fail more gracefully but I guess not yet.

Link your Solder.

**Comment by Ra-Zim** [comment]
http://192.198.88.70

**Comment by sct** [comment]
Everything looks in order which makes me think the Platform is having trouble connecting to that IP for whatever reason. For me it took awhile to load the latest build. The platform might be timing out? Unfortunately SolderClient isn't properly catching this error so I will have to do some deeper digging to uncover the cause.

**Comment by Ra-Zim** [comment]
I've run Solder on this IP before, it worked fine before, but I decided to reformat the server and set things back up now. Just an fyi. Thank you for looking into this

**Comment by sct** [comment]
A fresh load of your 0.9.2 version of your modpack takes up to 12 seconds to load for me sometimes.

See here: ![example image](http://puu.sh/uGRTq/95336c0cc0.png)

The platform would definitely time out trying to connect to that.

**Comment by Ra-Zim** [comment]
I'm not sure what would be causing that... Though I have noticed that it takes a few seconds to ping the servers when going to connect. The server itself has no lag and runs great, but I'll see if I can find out something here as well.

**Comment by Ra-Zim** [comment]
I've been doing my own investigating all day, and I can't find a single problem. I've run traceroutes and pings and double checked resource usage, but everything seems fine on my end as well as the data center's end. Could I ask where, exactly, Solder sends the info for the page? Because connecting to technicpack.net is really fast.

**Comment by Ra-Zim** [comment]
So... For posterity's sake, I'm posting this here. It turns out the problem was actually due to me attempting to host the database on a separate server from where Solder was. Its possible that can be done, but the server I was hosting the database on was apparently not up to the task. Just in case anyone else runs into this problem, things are working now that Solder and the database are on the same box!
