### ISSUE TITLE
Version added, mod not found.

### ISSUE THREAD

**Issue by kylanrock8** [TechnicPack/TechnicSolder#636]
So, very new to solder and I spent a while learning the file structure. I'm 90% sure I've got everything right. So I go add a version for Ars Magica 2 just to test it out, and it works great up until the point of me testing the download link. I get "Mod not found" yet a file size is shown and a hash is generated. I'm assuming the download link is generated wrong? I've also tested with another mod and it does not work for that one either. https://gyazo.com/ae7617537e4ec21044bd54f113cc21e4
https://gyazo.com/b8886163b63367ef3aa68025b9322190

**Comment by nbartokos** [comment]
Did you set the repo_location and mirror_url properly in the app/config/solder.php file? If yes, please try to set the right permissions with: chmod -R 777 /var/www/html/TechnicSolder (or your path). Maybe this helps!

**Comment by Pyker** [comment]
Closing this since it's likely no longer a problem. Feel free to reopen if it's still a problem.
