### ISSUE TITLE
Technic Launcher unable to download solder pack

### ISSUE THREAD

**Issue by mjra007** [TechnicPack/TechnicSolder#637]
I have set solder with nginx and it seemed to be working fine. I was able to add all the mods I wanted, create a modpack and succefully link the solder modpack to the technic launcher modpack.
I have also looked at the api endpoints and all of them seem to be working fine:

- 192.99.59.1/api/
- 192.99.59.1/api/modpack/enchanted-world-oasis
- 192.99.59.1/api/modpack/enchanted-world-oasis/2.6

Although technic always gives me an error whenever I try to download the modpack.

![](http://i.imgur.com/N1dSI81.png)

`[B#349] net.technicpack.rest.RestfulAPIException: Invalid URL [192.99.59.1/api/modpack/]
[B#349] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:153)
[B#349] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#349] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#349] 	at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
[B#349] 	at java.lang.Thread.run(Unknown Source)
[B#349] Caused by: java.net.MalformedURLException: no protocol: 192.99.59.1/api/modpack/
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:132)
[B#349] 	... 7 more
[B#349] net.technicpack.rest.RestfulAPIException: Invalid URL [192.99.59.1/api/modpack/]
[B#349] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:153)
[B#349] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#349] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#349] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#349] 	at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
[B#349] 	at java.lang.Thread.run(Unknown Source)
[B#349] Caused by: java.net.MalformedURLException: no protocol: 192.99.59.1/api/modpack/
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at java.net.URL.<init>(Unknown Source)
[B#349] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:132)
[B#349] 	... 7 more`

**Comment by skwerlman** [comment]
![image](https://cloud.githubusercontent.com/assets/6954107/24835945/3ce9fc9a-1cdd-11e7-8b27-ebe98c027dbd.png)
is not the same address as
![image](https://cloud.githubusercontent.com/assets/6954107/24835946/46d55c36-1cdd-11e7-95fb-1bd36129ed19.png)

**Comment by mjra007** [comment]
That was just me typing it, sorry

**Comment by skwerlman** [comment]
Looks like you're missing the protocol and a trailing slash in your config:
```json
{"name":"animationapi","version":"1.2.4","md5":"45a805381001e529197acba4462fdce0","filesize":"13427","url":"192.99.59.1mods\/animationapi\/animationapi-1.2.4.zip"}
```
Note the url: `192.99.59.1mods`

Try setting `repo_location` to `http://192.99.59.1/`.

**Comment by mjra007** [comment]
Just fixed that, It doesn't seem to be working still. What do you mean by protocol?

**Comment by skwerlman** [comment]
the protocol is the `http://` bit. It looks like you might have forgot that on technicpack.net as well, judging by the client error

**Comment by mjra007** [comment]
Just changed it. It doesn't seem to have fixed the problem but the technic launcher console doesn't give the error that It used to anymore,  but it still fails to download it

`[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 2 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 1 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 3 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 2 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 1 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 2 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 1 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 3 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 2 tries remaining
[B#349] Starting download of http://192.99.59.1/api/modpack/enchanted-world-oasis, with 1 tries remaining
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/437620.png?1491729721, with 3 tries remaining`

**Comment by mjra007** [comment]
![image](https://cloud.githubusercontent.com/assets/8156651/24836307/a83ba27c-1d10-11e7-8682-a6b0136e24bc.png)
![image](https://cloud.githubusercontent.com/assets/8156651/24836310/b1aa351c-1d10-11e7-81fa-da86586c34e1.png)

Just because I am doubting everything, are those alright?

**Comment by skwerlman** [comment]
Your configs look fine.

It looks like you have a download url set for your modpack. The download url is really only for non-solder modpacks, and its confusing the launcher, which thinks it can grab the full modpack as a .zip from `http://192.99.59.1/api/modpack/enchanted-world-oasis`.

What do you see for this option in Modpack Settings on the platform?
![image](https://cloud.githubusercontent.com/assets/6954107/24836404/eadd1804-1ce8-11e7-8bd5-d5b20fdcd3bc.png)

**Comment by mjra007** [comment]
It shows the same thing in the Modpack Settings  when I have solder linked but if I unlink Solder it shows http://192.99.59.1/api/modpack/enchanted-world-oasis . I just removed it and linked solder again. It still thinks I am not using solder but I think the changes don't have immediate effect so I'll just wait a bit. Thank you for the help

**Comment by skwerlman** [comment]
It seems like you stumbled onto 2 bugs here, which combined to break downloads:
1. The platform was still serving the .zip url even though solder is enabled
2. The launcher tries the .zip url before trying solder

@GenPage This seems like a pretty easy trap to fall into, especially for users who are migrating to solder from the .zip method. Maybe the platform should act as though `url` is null even when it isn't, as long as solder is enabled and working?

**Comment by mjra007** [comment]
That does seem to be the problem. It works now :D It recognizes the modpack as a solder modpack. Thank you.

**Comment by skwerlman** [comment]
Glad you got it sorted!

I'd leave this issue open for now, since the platform issue still exists.

**Comment by mjra007** [comment]
I wont close it

**Comment by Shmeeb** [comment]
Yup, still have users experiencing this bug, even though "Modpack Location" shows "Modpack is linked to Solder"

**Comment by Pyker** [comment]
Closing this since the Platform issue is resolved.

**Comment by Shmeeb** [comment]
How is this resolved when I literally just said it's not?

**Comment by Pyker** [comment]
Because I literally just resolved it.
