### ISSUE TITLE
Solder error

### ISSUE THREAD

**Issue by crazyhorse961** [TechnicPack/TechnicSolder#639]
Hello everyone!
I just setted up solder, and when i connect to it, i get an error:
Live error: http://solder.mcwownetwork.net
Someone haves a fix?

**Comment by skwerlman** [comment]
That doesn't look like a solder install...

**Comment by crazyhorse961** [comment]
What do you actually mean..? It is!

**Comment by skwerlman** [comment]
The error page is not an error generated by solder. Something else in your setup is producing that error.

**Comment by spannerman79** [comment]
I see no error - *and* while using Internet Exploder

![capture](https://cloud.githubusercontent.com/assets/7542384/25681844/31941dc4-3099-11e7-8d56-a61d72fc73a4.PNG)
