### ISSUE TITLE
MCrypt is deprecated on PHP 7.1+

### ISSUE THREAD

**Issue by evilarceus** [TechnicPack/TechnicSolder#640]
Noticed this while installing TechnicSolder on my Arch Linux machine with PHP 7.1. Downgrading to PHP 7.0 packages fixed it.

**Actual error:** Function mcrypt_get_iv_size() is deprecated

**Comment by Goldman60** [comment]
To workaround this for now you can put

`error_reporting(E_ALL ^ E_DEPRECATED);`

at the top of your app.php in your config folder

**Comment by GenPage** [comment]
Because of this, the current version of Solder is only supported on 5.6 or 7.0. To use Solder with 7.1 will require the newer/dev version currently being made.

**Comment by Yomanz** [comment]
@GenPage Can't see a branch with the dev version on it?

**Comment by Pyker** [comment]
> @GenPage Can't see a branch with the dev version on it?

It's not a branch here, it's over at https://github.com/TechnicPack/solder.

**Comment by Indemnity83** [comment]
This probably shouldn't be an open issue...

**Comment by Yomanz** [comment]
@Pyker Appreciate it
