### ISSUE TITLE
Solder with TechnicLauncher

### ISSUE THREAD

**Issue by DvnBthlo** [TechnicPack/TechnicSolder#644]
Hello, I needed to help connect the solder to TechnicLauncher - https://github.com/TechnicPack/TechnicLauncher

**Comment by spannerman79** [comment]
Its all in the docs - if you bothered to actually read them

http://docs.solder.io/docs/linking-solder-to-the-technic-platform

**Comment by DvnBthlo** [comment]
But i want to create my own Launcher
