### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by Rmarmorstein** [TechnicPack/TechnicSolder#646]
Based on the dependencies, solder requires PHP 5.6+, not 5.4+ as noted in the system requirements.

See this excerpt from the composer install"

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mockery/mockery master@dev -> satisfiable by mockery/mockery[dev-master].
    - mockery/mockery dev-master requires php >=5.6.0 -> your PHP version (5.4.16) does not satisfy that requirement.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requireme       nts are blocking the update you have to resolve those problems.
```

**Comment by GenPage** [comment]
Not really sure where you are seeing 5.4+, that is what is installed on your system. The Readme.md states 5.5+ 

The composer does not hard require a PHP version

**Comment by Rmarmorstein** [comment]
This page: http://docs.solder.io/v0.7/docs/getting-started

As you can clearly see, it states PHP version 5.4+

![System Requirements](https://i.imgur.com/nCEyeBj.png)

**Comment by spannerman79** [comment]
Yes the docs are a but out of date in that regard but considering that;
Ubuntu - https://packages.ubuntu.com/xenial/php/php - Uses php7
Fedora 25 - http://rpmfind.net/linux/RPM/fedora/updates/25/x86_64/p/php-7.0.23-1.fc25.x86_64.html - uses php7

Splitting hairs over this seems a bit...pointless don't you think @Rmarmorstein ? 
Time to update to **at least** the minimum supported php version as 5.4 is considered EOL - in fact php 5.4 was considered EOL **3 Sep 2015**

**Comment by Rmarmorstein** [comment]
@spannerman79 CentOS 7's default php version is 5.4, everyone uses a different OS. I normally use php7 on most projects, but solder only required 5.4 on the docs, go ahead call me lazy I didn't go through the extra steps.

If the EOL was that long ago, why is solder using it as the required version in the docs? If it's THAT old then why haven't the docs been updated since? I think it is important to keep docs up to date.

**Comment by spannerman79** [comment]
> If the EOL was that long ago, why is solder using it as the required version in the docs? If it's THAT old then why haven't the docs been updated since? I think it is important to keep docs up to date.

I agree - Its not quite simple for anyone that doesn't have access to update readme.io docs.  I have made edit suggestions before and they were left or ignored.

If they were using https://readthedocs.org/ it would be easier - all I (or anyone else) would need to do is do a PR with the changes and those in control here in this github org will get notified.

I think this is why the README.md in the github repo is more up to date in this regard.
