### ISSUE TITLE
When I click Create new build I get this everything is linked.

### ISSUE THREAD

**Issue by skylarcoolya** [TechnicPack/TechnicSolder#649]
Picture below but the error is:

Looks like we hit a snag
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

Everything else has worked but this even adding the mods etc

http://prntscr.com/h1mxl1

**Comment by skwerlman** [comment]
Dupe #314 #522 #607 

Please search for your issue on the tracker before creating a new issue.
