### ISSUE TITLE
Can't access on my solder server

### ISSUE THREAD

**Issue by antonioltg91** [TechnicPack/TechnicSolder#656]
Hello
I had a working solder server a year ago, but now that i want to start to use it again i cannot access.
If I try to go on my server page it just start a download of a file (that is the /public/idex.php file)
I try to reinstall solder but nothing changed, what could be the problem?

**Comment by Indemnity83** [comment]
This doesn't sound like an issue with Solder directly; it sounds like you're either missing PHP on your webserver, or your webserver isn't configured properly to serve PHP pages. 

Please see the following documentation to confirm your web server is configured properly: http://docs.solder.io/docs/example-web-server-configs
