### ISSUE TITLE
MongoDB Support?

### ISSUE THREAD

**Issue by FireController1847** [TechnicPack/TechnicSolder#658]
Solder Repo Hash: N/A

  Operating System and version: Ubuntu 18.04 LTS

  PHP version: 7.0

  Composer version: 1.6.4

  Server type: ??

  Type of database: N/A

  Type of hosting: Dedicated

  Link to the affected install's public url: N/A

---------------------------------------------------------

Is it possible to get MongoDB support added? I've never been a big fan of MySQL, and I've never had a good experience setting it up.

**Comment by Pyker** [comment]
There are no plans to support MongoDB now or in the future. The reality is that, which you can freely switch between MySQL, Postgres and SQLite, since they're all SQL, MongoDB is NoSQL, which has a completely different reality to it.
