### ISSUE TITLE
Solder redirects to HTTP on HTTPS-supporting server

### ISSUE THREAD

**Issue by golyalpha** [TechnicPack/TechnicSolder#662]
Solder Repo Hash: `139e88e`
  Operating System and version: Heroku-16 stack (Ubuntu 16.04 based)
  PHP version: 5.6.32
  Composer version: 1.6.5
  Server type: Virtual
  Type of database: PostgreSQL
  Type of hosting: Shared
  Link to the affected install's public url: http://fierce-reaches-35013.herokuapp.com

Heroku supports HTTPS on it's domains (domains with .herokuapp.com) by default.
When I access the affected install over HTTPS, I get redirected to HTTP, and when I force HTTPS once more, the browser refuses to load certain resources due to them being accessed over HTTP.
![Exhibit A - Content Access Restrictions forcibly disabled](https://user-images.githubusercontent.com/8203992/42755148-6e381c78-88f7-11e8-8063-a5899c6a6389.png)

And the moment I press "Log In", the data gets sent over HTTP anyways.
In theory, I could try using addons, that force HTTPS upgrades whenever a server supports it (and frankly, even those seem to not work), but shouldn't Solder just stop forcing HTTP on HTTPS capable servers?

This is what Solder looks like with "HTTPS Everywhere" default ruleset (no manual rules):
![image](https://user-images.githubusercontent.com/8203992/42755490-b2248164-88f8-11e8-8502-9c7c5fa976be.png)

**Comment by spannerman79** [comment]
```
curl -I -L https://fierce-reaches-35013.herokuapp.com/
HTTP/1.1 302 Found
Connection: keep-alive
Date: Mon, 16 Jul 2018 11:02:24 GMT
Server: Apache
Cache-Control: no-cache
Set-Cookie: laravel_session=eyJpdiI6IjB5WnZsOFJMUnUxaUtoTVVDSnhsZGN4ZVhuVERyTktpVzd2MW9KN2RMTFk9IiwidmFsdWUiOiJHRGJhTVBwNUt1YkZsMXNNTTJpQUVSSVpZaGlXMTJtZHE4V3o0aVNJZFhYZnhBbzVJckR3dGJmN2x1Tk5HelMwblRnUXhjZVwvK0liaUJZQXNMTWREWXc9PSIsIm1hYyI6ImJhMGY3ODBjMzFiN2RkNjE2ZmRiZjQyZjYzYjUyZDEzNDNhYjMxZGVjNmMxOWVlZjg1ZTMxMjNkNzk0YzVlYTcifQ%3D%3D; expires=Mon, 16-Jul-2018 13:02:24 GMT; Max-Age=7200; path=/; httponly
Set-Cookie: 3ee96dd2f96ab84cd06877da2b398fbe130c207b=eyJpdiI6Im0wWGV3U0ZIeHdvME95VnhWVnNzcnhEZzFLazJDZkczcE1Rc0JicVhHSFU9IiwidmFsdWUiOiJxVWNFaEdrSWRpdDhTczV5RWNTbTVLbkh0SHI2ZTlCVm1SQ1NFZXpFelhMa1diemtDSnE3THhGK3hPUVdKWE1uNnhnRUhcL0xTRXJ0NkhhREVNbDNLVmcwV1wvVDlSUkYxaEd2NmZWYVNiSFNBNlFmVjFKc1cwT096TWJkU1J0ZjQxSjZSWWFXY1hpUUJlemZCeGtHTzVpQlBocEhCeUNjdlR0VE5QUFJndDV5bXVSdVhWVGErQXFNS3I0cTZuK2U1OTFTRlZMeEtxcXd1NUgzTisyZ2UxQTZWOVYreDJiZ0FjZzVXVHJ0dEpqaFwvTmVRY21oVTlaZkl5SEY5eWhNNG52Mm5LT3RzZ0oyU0twdGdPVzJcLzNmdW1vb1wvbHNxd1wvWG9lQitvRW1GTVpWaz0iLCJtYWMiOiI2NGNlZWYwZjk5OGYyZjVhYzU5OTNmMDBkYmQ5OGZjMmFjNzNkMzJhMDZhZWE3MjJjYWZlMjI1OWRmNmI0YTFjIn0%3D; expires=Mon, 16-Jul-2018 13:02:24 GMT; Max-Age=7200; path=/; httponly
Location: http://fierce-reaches-35013.herokuapp.com/dashboard
Content-Type: text/html; charset=UTF-8
Via: 1.1 vegur

HTTP/1.1 302 Found
Connection: keep-alive
Date: Mon, 16 Jul 2018 11:02:25 GMT
Server: Apache
Cache-Control: no-cache
Set-Cookie: laravel_session=eyJpdiI6Ijh6T0lUNk1wVHVieHI2ZTE3VzRyVkxqNzlUdWY4WlA0RHdGK0x0eDFyVm89IiwidmFsdWUiOiJ0eDRkZW16WUVLSVFMY0pDV012YmxidWRTQXBSdlE2QkYzUWFzbHdhalF1VllUdWFPZ2M4a1hGU1dqbEhtUEZSalZJN2hEZVpVRXFLdENHMU0xYTB5Zz09IiwibWFjIjoiZjY2NGMzN2RjODhhZjJiY2VkM2JhY2YwZDMxNjA1YWI0MDExMzJjOTMxNzdkNmViYzAzZTU5ZmVhOTVjZjNhMyJ9; expires=Mon, 16-Jul-2018 13:02:25 GMT; Max-Age=7200; path=/; httponly
Set-Cookie: b9d322c94d0c6095ba328fdd33557212d7771ea8=eyJpdiI6IlEyUUthemJVUmx3QmRMXC9ScHU5THJPMXI5bjRwNktleHRGU0hzUDJLb1RFPSIsInZhbHVlIjoiN2pud3ZodGxUSTF5ZHg0Y2dTQzQrVWsraEx4UzRvcTZUNkZNaE5lWmd0ZkJGS2NxRVNSM2RkRGZkNzFVZG1aS3NuN2loV2hrTTVUUTgwQzU3YWNBeG9tRUVOUlAySmJocnpXQXo5RSszTlByc3NjUmJ0RlRTTldWbU9WS24xS2VVXC92em9KczRVM1ExSnFMd1I4UXhGU2ROUHRBQmEwN2gzNnZPZFwvTlArQlwvYUVrdVhkV2N3dDFOR3hnMnR1ZEkrTjhEN0VtNk9zTW1XYXdJR0doS1VpbDZcL3pzQTZ0cW5pUlpZamFmVmJuTmZMUmliOEFSXC9rME5uM0xmN053akVZbGRJNllncEw4K3djUUZDeDhPYW9iT3FGejZWbDN2cGJTaW5JOFBSQWZaU0FBMHVCZGVZQ0J5SG50RUdqVFBHcDJkUDR5STUrTkVWXC9sYTRscGpNUFpYakY4Mld3K25pYk8zUjJrc1p5WjFtT05HSGhFbTZySVVxclwvYTc2RzZSTHFcL3RsZEJxOHRYdHBrdkpGRkVPRjE1eDE1a0RuN2xjcitnbHFkQU5cLzA4TT0iLCJtYWMiOiJlNjM0YzdhOWRkODQyNGNiYzQ2OTViMGMwYmU5NDU4M2MyZmU1YmJkZjAxZGVjN2FhZjAyNGJhMTMwMGMxOWVlIn0%3D; expires=Mon, 16-Jul-2018 13:02:25 GMT; Max-Age=7200; path=/; httponly
Location: http://fierce-reaches-35013.herokuapp.com/login
Content-Type: text/html; charset=UTF-8
Via: 1.1 vegur

HTTP/1.1 200 OK
Connection: keep-alive
Date: Mon, 16 Jul 2018 11:02:25 GMT
Server: Apache
Cache-Control: no-cache
Set-Cookie: laravel_session=eyJpdiI6IjNzVGt0T2JlQkVrZUdpSHBCZ1wvY2pTbUVjc1ZUYmM3TUlPaHI3QTJ5MFwvdz0iLCJ2YWx1ZSI6IkV6Sk5rdjNLazVYVGdwaG4reml1T2N6NlBWYnhNRjZacGc0a3B4ZEpFSk5lQ0RIR1NOT3dsTWcrZ2tCU2NmZDljYlNubnVsOTE0emFUUVRDNlFsVVN3PT0iLCJtYWMiOiIzNTc4ZTVhMjM4ODBmNzgzMTBmODE0YjZiYTdiZTZhNTEyYmRhMGRmZGRmYzNlODVhNTkzODRkYjEwNjBmZWYzIn0%3D; expires=Mon, 16-Jul-2018 13:02:25 GMT; Max-Age=7200; path=/; httponly
Set-Cookie: c287731a495996f693829ba1339f64c7a7b3d5dd=eyJpdiI6IjN0WXNGUmNcL0pLcHl1ektORFBuSzM5dlBScWI1bVhBcm5WVHdBYmNyejZZPSIsInZhbHVlIjoiTFNXT3hxeEJoa1A2TlRjeUt6eVQ1a3hJb01xaCt4cVJtaWNRc1hURUE1SytCU3ZkRW5teFVcL1pFRUc4XC9ON3BZMjg5b0UyXC9vRzFjSlBNeSt4ZUM4TG5LdE8wNHE5ZlcyWG9QSURsM1ZTQ1g0SDRJUU5FQ2NBR1pvTFZGM1wvUWV0aWk1aFwvV2hodDNDU2NZM2VcL2pnVnBGQzJBeThudGtFQVlmcWY5ODdGODI3YWZ3QU5zb1dxRzR6MVRcLzBha0FDbFpIYTNWQWFoR280WEhHQlpJTjZNTStxOTNJZEFVWG1LYkZteTFmZkZYdEdCV0ViK21Pc2xBWDlTeW8relJSbXY1ZVJ2K2NoSXMrVFVcL2R1d0lSeFFnZlBTMVFtYzNERjVncE1QbXhQODhSbz0iLCJtYWMiOiJhMTE5MDZkNWMyMzY1Zjc3MmM4MzkyZDRmNGQ1YTI4Y2FkMDNjMTlhNjZhZTk1ZWZiZTE4ZWE4YzE3MzBmN2UyIn0%3D; expires=Mon, 16-Jul-2018 13:02:25 GMT; Max-Age=7200; path=/; httponly
Content-Type: text/html; charset=UTF-8
Via: 1.1 vegur
```

Not a solder issue - server misconfiguration/shared (aka "free") hosting issue.

Shared hosting is not suitable for solder/laravel project hosting.

Get a VPS or dedi and set it up properly as per outlined in the docs http://docs.solder.io/docs/getting-started

**Comment by golyalpha** [comment]
Thank you for linking me to docs that have literally nothing to do with my issue, but, server misconfiguration it is.
Interesting how all my apps can be connected to via both HTTP and HTTPS, but when your app can't be connected to via HTTPS, it's a hosting issue. How's the sand by the way?

Just wanted to check if you noticed something in the redirect response:
![image](https://user-images.githubusercontent.com/8203992/42757698-3bfe22ca-8901-11e8-8e43-9433bf81fadf.png)

**Comment by spannerman79** [comment]
Because vegur adds one of two header responses when https is involved.

`X-Forwarded-Proto` and/or `X-Forwarded-Port` which by the way you would have taken some notice of if you took notice of the little bit of text being `Via: 1.1 vegur`

**Comment by golyalpha** [comment]
Really, are you 100% positive that that's something vegur does?
```
curl -I -L https://galacticity.herokuapp.com
HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn/19.7.1
Date: Mon, 16 Jul 2018 12:18:23 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3428
Access-Control-Allow-Origin: *
Via: 1.1 vegur
```
![image](https://user-images.githubusercontent.com/8203992/42758328-6c78cfc0-8903-11e8-898b-36b04f428c2d.png)

**Comment by Pyker** [comment]
Did you set it to the HTTPS URL in `app/config/app.php`?

**Comment by golyalpha** [comment]
`'url' => 'https://fierce-reaches-35013.herokuapp.com/',`
Yup, it's right there.

**Comment by golyalpha** [comment]
@Pyker is it possible that solder is redirecting to HTTP because it's being queried over HTTP? The hosting's frontend handles the SSL, internally, the traffic travels as HTTP to the server that Solder is running on.

**Comment by golyalpha** [comment]
By the way, the icon resource (wrenchIcon.svg) loads just fine over HTTPS:
![image](https://user-images.githubusercontent.com/8203992/43071421-11d5bb76-8e73-11e8-8649-d6634883c6fa.png)

**Comment by golyalpha** [comment]
And asking HTTPS Everywhere to block non-HTTPS requests makes the entire website go SSL (with no mixed-content issues).
![image](https://user-images.githubusercontent.com/8203992/43071714-edf5b3f4-8e73-11e8-88eb-35d9eae0543c.png)

Main issue there is that resources and what not, are requested over HTTP, resulting in mixed-content issues, unless you ask HTTPS Everywhere to actively rewrite HTTP requests to HTTPS and block HTTP requests for all sites that support HTTPS:
![image](https://user-images.githubusercontent.com/8203992/43071802-27af88fe-8e74-11e8-995c-85fa53e2854b.png)

**Comment by golyalpha** [comment]
@Indemnity83 
That is correct.
Thanks for the link, will try when I have the chance.

**Comment by golyalpha** [comment]
Alright, I can confirm that that has fixed my issue with being redirected to HTTP and mixed content when forcing HTTPS.
