### ISSUE TITLE
Can't download mods from link

### ISSUE THREAD

**Issue by Rainverm38** [TechnicPack/TechnicSolder#663]
I have just recently started using TechnicSolder.  So as a quick test I threw a bunch of mods in a folder titled mods and then zipped it up. I then placed it in the right folders. I am now being told by TechnicSolder that there was an application error as shown in the included screenshot. Am I doing something wrong or is there an issue with Solder?
`<blockquote class="imgur-embed-pub" lang="en" data-id="a/XrIjeur"><a href="//imgur.com/XrIjeur"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

[https://imgur.com/a/XrIjeur](url)

Here is a screenshot of the file as well as it's location in command line: https://imgur.com/a/oV88DrH

**Comment by Rainverm38** [comment]
Stopped using solder

**Comment by Jerlag01** [comment]
depends to where you pointed the repo directory to in the config file of solder

**Comment by Pyker** [comment]
`1.6.1` vs `1.6.2`. Anyway, this is not an error with Solder.
