### ISSUE TITLE
Login Page loop

### ISSUE THREAD

**Issue by ToyPower** [TechnicPack/TechnicSolder#664]
I am running mysql, with the solder setup. But i am stuck in the login screen every time i login it refreshes back to the login screen nothing else. The php version i am using is 7.2, (found a way to get mcrypt to work with it). Directionary of technicsolder is in the root. su admin then ~/web/ipaddress/public_html/TechnicSolder. Any ideas why it gets stuck?. I enabled the debug menu, i also checked for any errors none, any ideas?

**Comment by ToyPower** [comment]
it is also using Ubuntu Linux

**Comment by Pyker** [comment]
The underlying framework (Laravel 4.2) only supports up to PHP 7.0, that's why you're having issues.

**Comment by Pyker** [comment]
This version isn't being maintained anymore, and migrating the entire codebase to Laravel 5 would be a huge undertaking, so I'm considering this issue a "won't fix".

**Comment by Jerlag01** [comment]
@ToyPower 
This version can't run on php 7.2 as mentioned in the documentation of this repo.
i recommend to install php5.6 and the required dependencies on your ubuntu machine and set php 5.6 as default version to use if you have no other web applications running that require php7.2. if you have done that then you normally won't have any problems anymore

**Comment by Pyker** [comment]
I recommend PHP 7.0, there's no need to run outdated and slow PHP versions
