### ISSUE TITLE
Solder Update =|= Technicpack Update

### ISSUE THREAD

**Issue by nbartokos** [TechnicPack/TechnicSolder#665]
Hello!

I'm very new to solder (just downloaded it yesterday). It was really weird for me to set it up (I'm really dumb sometimes lol). But now everything is working.. Except updates?

I added 2 new builds to my modpack and in the TechnicLauncher it updates too.. everything fine.. But on my Modpack Website on technickpack.net, it still says "Version 1.0". But I already have build 1.2 (yes I've published it, recommended and latest).

Even the mod list on the website isn't correct anymore (added new mods and removed some). Did I forget something or is this a bug? 

---------------------------------------------------------
  Operating System and version: Linux - Debian 9
  PHP version: 5.6
  Composer version: 1.2.2
  Server type: Apache 2
  Type of database: sqlite
  Type of hosting: vServer
  Link to the affected install's public url: http://185.223.31.18
---------------------------------------------------------

**Comment by nbartokos** [comment]
Ahh.. I just have to wait.. Now, a hour later it's correct

**Comment by Indemnity83** [comment]
Right, TechnicPack.net caches results; the launcher is talking directly to your Solder install though so changes there are reflected immediately.
