### ISSUE TITLE
1.7.10 Pack: Failed to Download (Wr-CBE 1.4.1.11). Please need Help

### ISSUE THREAD

**Issue by neysonb** [TechnicPack/TechnicSolder#667]
I have a Problem with my Minecraft Technicklauncher. First i started the Launcher and i can't start the 1.7.10 Modpack. I thought it's an Bug, so i deleted this Pack. Then i Tried to Download it, but everytime I get an Error, with the mod WrCbe. 

Please help me,
Thanks.

**Comment by neysonb** [comment]
https://gyazo.com/02573fc49d463387700ac25961354b12

**Comment by neysonb** [comment]
[B#407] 2019/08/03 12:30:10 [INFORMATION] Starting download of https://crafatar.com/avatars/b2fc0d2c9bc448ec9d5022f3757c9ae7?size=100&helm, with 3 tries remaining
[B#407] 2019/08/03 12:30:10 [INFORMATION] Starting download of https://www.gravatar.com/avatar/777da0eed8908835b1e9e08204f5beb2?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/2a29f323eddf3410fb1b531b10f7df6f?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/4c9b9cd817e62d043070a821551c04f0?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/07b1950664b5569324a88727516e761d?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/417979e451a4ed37c22f5340a9c3cd4a?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/417979e451a4ed37c22f5340a9c3cd4a?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Analytics Response [runLauncher]: 200
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-logos/453902.png?1540643525, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of https://www.gravatar.com/avatar/d593acb99c078196c657559168b57a6e?s=60&d=retro, with 3 tries remaining
[B#407] 2019/08/03 12:30:11 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-backgrounds/453902.jpg?1540643525, with 3 tries remaining
[B#407] 2019/08/03 12:30:12 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1540643525, with 3 tries remaining
[B#407] 2019/08/03 12:30:14 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1540643525, with 3 tries remaining
[B#407] 2019/08/03 12:30:14 [SCHWERWIEGEND] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#407] 2019/08/03 12:30:14 [SCHWERWIEGEND] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#407] 2019/08/03 12:30:14 [SCHWERWIEGEND] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[B#407] 2019/08/03 12:30:14 [INFORMATION] Starting download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip, with 3 tries remaining
[B#407] 2019/08/03 12:30:14 [SCHWERWIEGEND] Download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip Failed!
[B#407] 2019/08/03 12:30:14 [INFORMATION] Starting download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip, with 2 tries remaining
[B#407] 2019/08/03 12:30:15 [SCHWERWIEGEND] Download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip Failed!
[B#407] 2019/08/03 12:30:15 [INFORMATION] Starting download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip, with 1 tries remaining
[B#407] 2019/08/03 12:30:15 [SCHWERWIEGEND] Download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip Failed!

**Comment by neysonb** [comment]
[B#407] 2019/08/03 12:21:51 [SCHWERWIEGEND] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#407] 2019/08/03 12:21:51 [SCHWERWIEGEND] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#407] 2019/08/03 12:21:51 [SCHWERWIEGEND] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[B#407] 2019/08/03 12:21:51 [INFORMATION] Starting download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip, with 3 tries remaining
[B#407] 2019/08/03 12:21:51 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1540643525, with 3 tries remaining
[B#407] 2019/08/03 12:21:51 [SCHWERWIEGEND] Download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip Failed!
[B#407] 2019/08/03 12:21:51 [INFORMATION] Starting download of http://solder.endermedia.com/repository/mods/wr-cbe/wr-cbe-1.4.1.11.zip, with 2 tries remaining

**Comment by Pyker** [comment]
This is not a big with Solder. Go complain to the owner of that Solder repo.
