### ISSUE TITLE
This is not a big with Solder. Go complain to the owner of that Solder repo.

### ISSUE THREAD

**Issue by neysonb** [TechnicPack/TechnicSolder#668]
This is not a big with Solder. Go complain to the owner of that Solder repo.

_Originally posted by @Pyker in https://github.com/TechnicPack/TechnicSolder/issues/667#issuecomment-517915118_

But how

**Comment by neysonb** [comment]
but how? im new

**Comment by Pyker** [comment]
Leave them a message over at their modpack Platform page.
