### ISSUE TITLE
Minecraft Version Field doesn't have any options.

### ISSUE THREAD

**Issue by BinaryAura** [TechnicPack/TechnicSolder#676]
Solder Repo Hash:

  Operating System and version: Fedora 30 (server)

  PHP version: 7.3.7

  Composer version: 1.9.0

  Server type: 

  Type of database: SQLite

  Type of hosting: Personal Shared

  Link to the affected install's public url: solder.binaryaura.net/

 repo.binaryaura.net/solder
---------------------------------------------------------

I'm not sure if I'm doing something in the wrong order, or I've put something in the wrong place, but the field 'Minecraft Version' the field below has no options to choose. I was give more information but, I'm getting no errors and I have no documentation to point me in the right direction. Any direction at all would be appreciated.
Thank-you.

**Comment by Pyker** [comment]
You might need to refresh the Minecraft version cache in the settings page. Let me know if that works.

**Comment by BinaryAura** [comment]
Ok it said Versions were not being cached, I Clicked the button to cache them and it gave: "Error caching Minecraft versions. An unknown error has occur has occured.

**Comment by Pyker** [comment]
What do the Solder logs say about it?

**Comment by Pyker** [comment]
Not sure how, but at one point we started commenting on the wrong issue. Just leaving the link here so the trail can be followed: https://github.com/TechnicPack/TechnicSolder/issues/675#issuecomment-520182595.

Also closing since this is solved.
