### ISSUE TITLE
Migrate to Laravel 6.x to support PHP 7.2+

### ISSUE THREAD

**Issue by skid9000** [TechnicPack/TechnicSolder#683]
Hello,

Since PHP 5.6 and 7.0 are in EOL for already 9 months according to [PHP Website](https://www.php.net/eol.php), it's pretty important to upgrade the Laravel base to the 5.x branch.

I know that's not an easy task, but the security risk is high since there is no security patch for theses versions.

So please, to avoid security hazards consider the upgrade instead of taking the issue as a "won't fix".

**Comment by Pyker** [comment]
Already in progress

**Comment by Pyker** [comment]
Status update on this: the code has been updated to [Laravel v6.4.1](https://github.com/laravel/framework/releases/tag/v6.4.1), but the auth system (and possibly some other things that haven't been tested yet) haven't survived the massive successive upgrades, so there's some work to do still before I can push it to a new branch.

**Comment by Pyker** [comment]
PHP 7.1 is EOL soon (on 1 Dec 2019), so we're going to target PHP 7.2 instead.

**Comment by andreaspalmer** [comment]
Hello, are there any updates yet to make this compatible with the newer versions of PHP?

**Comment by Pyker** [comment]
A beta of sorts is available in the `feature/laravel-6` branch. Instructions to set it up are available at https://docs.solder.io/v0.7.6/docs/getting-started.
