### ISSUE TITLE
API Endpoints missing

### ISSUE THREAD

**Issue by Toothwitch** [TechnicPack/TechnicSolder#685]
Solder Repo Hash: e929330b379b20334b70e56e56ce9000f6dbfa74 
pulled 29. Mar from master

  Operating System and version: Debian 9.11 
Linux main1 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

  PHP version: 7.2.24 FPM (sury)

  Composer version: 1.9.1

  Server type: Nginx

  Type of database: MariaDB/MySQL

  Type of hosting: dedicated HW

  Link to the affected install's public url:  https://solder.fritten.net/ (root is public folder)

---------------------------------------------------------

Some API Endpoints in the v7 API are missing. 
The issue got visible when trying to link the solder instance to the technicplattform. 

e.g.
https://solder.fritten.net/api/ delivers json output
https://solder.fritten.net/api/modpack delivers json output
https://solder.fritten.net/api/modpack/onedotfifteen delivers json output

https://solder.fritten.net/api/modpacks delivers a 404 (v8 test)
https://solder.fritten.net/api/mod delivers a 404
https://solder.fritten.net/api/verify delivers a 404

If this is caused by running the 0.8.0-beta please close this issue

Best regards

**Comment by Pyker** [comment]
> If this is caused by running the 0.8.0-beta please close this issue

There is no 0.8.0-beta. Are you perhaps referring to https://github.com/TechnicPack/solder?

**Comment by Toothwitch** [comment]
Oh. Thats correct. Can this issue be moved there?

Other question is which repository should be compatible with technic plattform?

**Comment by Pyker** [comment]
> Can this issue be moved there?

Feel free to open an issue over there.

> Other question is which repository should be compatible with technic plattform?

This one (https://github.com/TechnicPack/TechnicSolder).
https://github.com/TechnicPack/solder is still under development and shouldn't be used for production.
