### ISSUE TITLE
Mockery dependency unresolvable

### ISSUE THREAD

**Issue by hecksadecimal** [TechnicPack/TechnicSolder#690]
Solder Repo Hash: 2fa6f028e5a4b3fd3a062f428015c8d359ee717f

  Operating System and version: Manjaro Linux 64-bit (Kernel 5.7.0-3)

  PHP version: 7.0.33

  Composer version: 1.10.8

  Server type: Desktop

  Type of database: SQLite

  Type of hosting: Home

---------------------------------------------------------

![image](https://user-images.githubusercontent.com/20251491/85962612-93360e80-b97f-11ea-8ce5-8bb00013986e.png)

As of release 1.4.0 of mockery, PHP < 7.3.0 is no longer supported. Trying to set up TechnicSolder through composer will fail.
The dependency should be changed to require 1.3.1 instead until TechnicSolder can be upgraded to support PHP > 7.0

**Comment by Pyker** [comment]
Please see https://github.com/TechnicPack/TechnicSolder/pull/689 for a more up-to-date version that will work with PHP 7.2+.

**Comment by Pyker** [comment]
This is now also resolved in the old/current Laravel 4.2-based branch, as of aa49d33a809aa550c0ec89d825fb42c9830119d0.
