### ISSUE TITLE
Mods folder can't be reached.

### ISSUE THREAD

**Issue by mentimjojo** [TechnicPack/TechnicSolder#691]
So I used https://docs.solder.io/v0.7.6/docs/getting-started to install solder, because the previous version is old so thought why not. Although everything works, with nginx there is no way to access to mods map. 

Lets say you install solder on domain.com, and you configured nginx on that. The mods folder on domain.com/mods doesn't work. Tried everything but nginx just doesn't want to allow /mods map to work properly. 

So mods can't be downloaded right now. for example domain.com/mods/forge/version.zip doesn't work. Any solutions to this?

**Comment by Pyker** [comment]
Just.... create the folder? Also, those configs are only a suggestion on how to set it up.

**Comment by mentimjojo** [comment]
I did, but nginx tries to read it within the solder app. So the result is as the following: 

![image](https://user-images.githubusercontent.com/4374706/87251797-a8766700-c46e-11ea-9f40-b59eafdb02d7.png)

**Comment by Pyker** [comment]
Just to check, you are creating this mods folder inside the public folder, as the configs say, right?

**Comment by mentimjojo** [comment]
I've tried both inside root/public/mods as just in root/mods/

**Comment by Pyker** [comment]
Then it seems you're doing things right? If you try to access an URL that doesn't exist, then you'll just get a "not found" error page. I really don't see what's wrong here.

**Comment by mentimjojo** [comment]
So, I reran some setups, recreated nginx config files, and restarted, and now it works :') I've absolute no idea what was wrong, I must be stupid. 

Thanks for the help eitherway
