### ISSUE TITLE
Add support for PHP 8.0

### ISSUE THREAD

**Issue by Pyker** [TechnicPack/TechnicSolder#694]
Currently PHP 8.0 isn't supported (we limit to `^7.2`), and one of the dependencies (`knplabs/github-api`) is also blocking it.

**Comment by soulgriever** [comment]
Incase anyone needs to install solder on 8.0 in the meantime do the following steps

Add "--ignore-platform-reqs" to your composer arguement
Example: composer install --no-dev --no-interaction --ignore-platform-reqs

Replace the following in your NGINX/Apache config:

Replace
fastcgi_pass                    unix:/run/php/php7.4-fpm.sock;
With
fastcgi_pass                    unix:/run/php/php8.0-fpm.sock;

Still setting up my solder instance but doing this I haven't discovered any problems so far. If you forget to update your php8.0-fpm you will get a 502 error

**Comment by Pyker** [comment]
That WILL cause issues.

**Comment by Pyker** [comment]
Solved in da98e26e629826fb7bd5002ab5d8e1a32dc59512
