### ISSUE TITLE
Config option to disable rate limit for certain users

### ISSUE THREAD

**Issue by kmecpp** [TechnicPack/TechnicSolder#703]
Laravel has a built in rate limiter which Solder uses and makes it annoying to programmatically manage modpacks. It would be great if there was a config option to disable this rate limit for certain users: https://stackoverflow.com/questions/43058219/disable-rate-limiter-in-laravel

**Comment by Pyker** [comment]
There is no authenticated api, and there are no plans to make it authenticated.

**Comment by Pyker** [comment]
If the rate limit is an issue for you, you can adjust it in the config.

**Comment by kmecpp** [comment]
Disabling the rate limiter for everyone isn't ideal. Couldn't something [like this](https://stackoverflow.com/a/62424730/3476226) work fine where you just check if the user is logged in and specified in the config, and if so, skip the rate limit check? It's unrelated to the API

**Comment by Pyker** [comment]
No, that wouldn't work.
