### ISSUE TITLE
Invalid Username or Password

### ISSUE THREAD

**Issue by SethPederito2023** [TechnicPack/TechnicSolder#716]
![OCjh2CXf](https://github.com/TechnicPack/TechnicSolder/assets/127005043/a291fafc-d095-4731-bdc5-7ca0d49275ac)
How am i supposed to login to Technic Solder? Please comment.

**Comment by Pyker** [comment]
The default credentials are listed in the setup guide.

**Comment by Pyker** [comment]
You should obvious change those, since they're not secure.
